export const ADDRESS_CONVERTER_COPY = {
  en: {
    eyebrow: "Address tools", title: "One account. Two address formats.",
    lead: "YNX uses ynx1 as its native address format. The EVM equivalent represents the same 20 account bytes. Converting formats does not change assets, keys or account state.",
    boundary: "0x is the EVM compatibility format used by tools such as MetaMask, Solidity and EVM JSON-RPC.",
    inputLabel: "Account address", placeholder: "ynx1… or 0x… address", convert: "Convert",
    nativeLabel: "YNX native (default)", compatibilityLabel: "EVM compatibility / MetaMask", explorer: "View account data in Explorer",
    copy: "Copy address", copied: "Address copied",
    errors: { invalid: "Enter a valid ynx1 address or a 0x address with 40 hexadecimal characters.", checksum: "The YNX address checksum is invalid. Check the address and try again.", mixedCase: "A YNX address cannot mix uppercase and lowercase letters.", clipboard: "Clipboard access is unavailable. You can select and copy the address." },
  },
  "zh-CN": {
    eyebrow: "地址工具", title: "一个账户，两种地址格式。",
    lead: "YNX 使用 ynx1 作为原生地址格式。对应的 EVM 地址表示同样的 20 字节账户标识，转换格式不会改变资产、密钥或账户状态。",
    boundary: "0x 是 EVM 兼容地址格式，适用于 MetaMask、Solidity 与 EVM JSON-RPC 等工具。",
    inputLabel: "账户地址", placeholder: "ynx1… 或 0x… 地址", convert: "转换",
    nativeLabel: "YNX 原生地址（默认）", compatibilityLabel: "EVM 兼容地址 / MetaMask", explorer: "在浏览器中查看账户数据",
    copy: "复制地址", copied: "地址已复制",
    errors: { invalid: "请输入有效的 ynx1 地址，或以 0x 开头、包含 40 个十六进制字符的地址。", checksum: "YNX 地址校验和无效，请检查地址后重试。", mixedCase: "YNX 地址不能混用大小写字母。", clipboard: "暂时无法访问剪贴板，你可以选中地址手动复制。" },
  },
  "zh-TW": {
    eyebrow: "地址工具", title: "一個帳戶，兩種地址格式。",
    lead: "YNX 使用 ynx1 作為原生地址格式。對應的 EVM 地址表示相同的 20 位元組帳戶識別碼，轉換格式不會改變資產、金鑰或帳戶狀態。",
    boundary: "0x 是 EVM 相容地址格式，適用於 MetaMask、Solidity 與 EVM JSON-RPC 等工具。",
    inputLabel: "帳戶地址", placeholder: "ynx1… 或 0x… 地址", convert: "轉換",
    nativeLabel: "YNX 原生地址（預設）", compatibilityLabel: "EVM 相容地址 / MetaMask", explorer: "在瀏覽器中查看帳戶資料",
    copy: "複製地址", copied: "地址已複製",
    errors: { invalid: "請輸入有效的 ynx1 地址，或以 0x 開頭、包含 40 個十六進位字元的地址。", checksum: "YNX 地址檢查碼無效，請檢查地址後重試。", mixedCase: "YNX 地址不能混用大小寫字母。", clipboard: "目前無法存取剪貼簿，你可以選取地址手動複製。" },
  },
  ja: {
    eyebrow: "アドレスツール", title: "ひとつのアカウント、ふたつのアドレス形式。",
    lead: "YNX のネイティブアドレス形式は ynx1 です。対応する EVM アドレスも同じ 20 バイトのアカウントを表します。形式を変換しても、資産、鍵、アカウントの状態は変わりません。",
    boundary: "0x は MetaMask、Solidity、EVM JSON-RPC などのツールで使う EVM 互換アドレス形式です。",
    inputLabel: "アカウントアドレス", placeholder: "ynx1… または 0x… アドレス", convert: "変換",
    nativeLabel: "YNX ネイティブ（標準）", compatibilityLabel: "EVM 互換 / MetaMask", explorer: "Explorer でアカウントデータを見る",
    copy: "アドレスをコピー", copied: "アドレスをコピーしました",
    errors: { invalid: "有効な ynx1 アドレス、または 0x に続く 40 桁の 16 進数アドレスを入力してください。", checksum: "YNX アドレスのチェックサムが無効です。アドレスを確認して再試行してください。", mixedCase: "YNX アドレスでは大文字と小文字を混在できません。", clipboard: "クリップボードを利用できません。アドレスを選択してコピーしてください。" },
  },
  ko: {
    eyebrow: "주소 도구", title: "하나의 계정, 두 가지 주소 형식.",
    lead: "YNX의 기본 주소 형식은 ynx1입니다. 대응하는 EVM 주소도 동일한 20바이트 계정 식별자를 나타냅니다. 형식을 변환해도 자산, 키, 계정 상태는 바뀌지 않습니다.",
    boundary: "0x는 MetaMask, Solidity, EVM JSON-RPC 등의 도구에서 사용하는 EVM 호환 주소 형식입니다.",
    inputLabel: "계정 주소", placeholder: "ynx1… 또는 0x… 주소", convert: "변환",
    nativeLabel: "YNX 기본 주소", compatibilityLabel: "EVM 호환 주소 / MetaMask", explorer: "탐색기에서 계정 데이터 보기",
    copy: "주소 복사", copied: "주소가 복사되었습니다",
    errors: { invalid: "유효한 ynx1 주소 또는 0x 뒤에 40자리 16진수가 오는 주소를 입력하세요.", checksum: "YNX 주소의 체크섬이 올바르지 않습니다. 주소를 확인하고 다시 시도하세요.", mixedCase: "YNX 주소에는 대문자와 소문자를 섞어 쓸 수 없습니다.", clipboard: "클립보드를 사용할 수 없습니다. 주소를 선택해 직접 복사할 수 있습니다." },
  },
  es: {
    eyebrow: "Herramientas de direcciones", title: "Una cuenta. Dos formatos de dirección.",
    lead: "YNX usa ynx1 como formato de dirección nativo. Su equivalente EVM representa los mismos 20 bytes de la cuenta. La conversión no cambia los activos, las claves ni el estado de la cuenta.",
    boundary: "0x es el formato compatible con EVM que usan herramientas como MetaMask, Solidity y EVM JSON-RPC.",
    inputLabel: "Dirección de la cuenta", placeholder: "Dirección ynx1… o 0x…", convert: "Convertir",
    nativeLabel: "Nativa de YNX (predeterminada)", compatibilityLabel: "Compatible con EVM / MetaMask", explorer: "Ver datos de la cuenta en el explorador",
    copy: "Copiar dirección", copied: "Dirección copiada",
    errors: { invalid: "Introduce una dirección ynx1 válida o una dirección 0x seguida de 40 caracteres hexadecimales.", checksum: "La suma de verificación de la dirección YNX no es válida. Revisa la dirección e inténtalo de nuevo.", mixedCase: "Una dirección YNX no puede mezclar mayúsculas y minúsculas.", clipboard: "El portapapeles no está disponible. Puedes seleccionar y copiar la dirección." },
  },
  fr: {
    eyebrow: "Outils d’adresses", title: "Un compte. Deux formats d’adresse.",
    lead: "YNX utilise ynx1 comme format d’adresse natif. Son équivalent EVM représente les mêmes 20 octets du compte. La conversion ne modifie ni les actifs, ni les clés, ni l’état du compte.",
    boundary: "0x est le format compatible EVM utilisé par des outils comme MetaMask, Solidity et EVM JSON-RPC.",
    inputLabel: "Adresse du compte", placeholder: "Adresse ynx1… ou 0x…", convert: "Convertir",
    nativeLabel: "Native YNX (par défaut)", compatibilityLabel: "Compatible EVM / MetaMask", explorer: "Voir les données du compte dans l’explorateur",
    copy: "Copier l’adresse", copied: "Adresse copiée",
    errors: { invalid: "Saisissez une adresse ynx1 valide ou une adresse 0x suivie de 40 caractères hexadécimaux.", checksum: "La somme de contrôle de l’adresse YNX est invalide. Vérifiez l’adresse et réessayez.", mixedCase: "Une adresse YNX ne peut pas mélanger majuscules et minuscules.", clipboard: "Le presse-papiers est indisponible. Vous pouvez sélectionner et copier l’adresse." },
  },
  de: {
    eyebrow: "Adresswerkzeuge", title: "Ein Konto. Zwei Adressformate.",
    lead: "YNX verwendet ynx1 als natives Adressformat. Die entsprechende EVM-Adresse steht für dieselben 20 Kontobytes. Eine Formatumwandlung verändert weder Guthaben noch Schlüssel oder Kontostand.",
    boundary: "0x ist das EVM-kompatible Format für Tools wie MetaMask, Solidity und EVM JSON-RPC.",
    inputLabel: "Kontoadresse", placeholder: "ynx1…- oder 0x…-Adresse", convert: "Umwandeln",
    nativeLabel: "YNX nativ (Standard)", compatibilityLabel: "EVM-kompatibel / MetaMask", explorer: "Kontodaten im Explorer ansehen",
    copy: "Adresse kopieren", copied: "Adresse kopiert",
    errors: { invalid: "Gib eine gültige ynx1-Adresse oder eine 0x-Adresse mit 40 Hexadezimalzeichen ein.", checksum: "Die Prüfsumme der YNX-Adresse ist ungültig. Prüfe die Adresse und versuche es erneut.", mixedCase: "Eine YNX-Adresse darf Groß- und Kleinbuchstaben nicht mischen.", clipboard: "Die Zwischenablage ist nicht verfügbar. Du kannst die Adresse markieren und kopieren." },
  },
  pt: {
    eyebrow: "Ferramentas de endereços", title: "Uma conta. Dois formatos de endereço.",
    lead: "A YNX usa ynx1 como formato de endereço nativo. O equivalente EVM representa os mesmos 20 bytes da conta. A conversão não altera ativos, chaves ou o estado da conta.",
    boundary: "0x é o formato compatível com EVM usado por ferramentas como MetaMask, Solidity e EVM JSON-RPC.",
    inputLabel: "Endereço da conta", placeholder: "Endereço ynx1… ou 0x…", convert: "Converter",
    nativeLabel: "Nativo YNX (padrão)", compatibilityLabel: "Compatível com EVM / MetaMask", explorer: "Ver dados da conta no explorador",
    copy: "Copiar endereço", copied: "Endereço copiado",
    errors: { invalid: "Digite um endereço ynx1 válido ou um endereço 0x seguido de 40 caracteres hexadecimais.", checksum: "A soma de verificação do endereço YNX é inválida. Confira o endereço e tente novamente.", mixedCase: "Um endereço YNX não pode misturar letras maiúsculas e minúsculas.", clipboard: "A área de transferência está indisponível. Você pode selecionar e copiar o endereço." },
  },
  ru: {
    eyebrow: "Инструменты для адресов", title: "Один аккаунт. Два формата адреса.",
    lead: "YNX использует ynx1 как нативный формат адреса. Его EVM-эквивалент представляет те же 20 байт аккаунта. Преобразование не меняет активы, ключи или состояние аккаунта.",
    boundary: "0x — формат совместимости с EVM для таких инструментов, как MetaMask, Solidity и EVM JSON-RPC.",
    inputLabel: "Адрес аккаунта", placeholder: "Адрес ynx1… или 0x…", convert: "Преобразовать",
    nativeLabel: "Нативный YNX (по умолчанию)", compatibilityLabel: "Совместимый с EVM / MetaMask", explorer: "Посмотреть данные аккаунта в обозревателе",
    copy: "Копировать адрес", copied: "Адрес скопирован",
    errors: { invalid: "Введите действительный адрес ynx1 или адрес 0x с 40 шестнадцатеричными символами.", checksum: "Контрольная сумма адреса YNX неверна. Проверьте адрес и повторите попытку.", mixedCase: "В адресе YNX нельзя смешивать прописные и строчные буквы.", clipboard: "Буфер обмена недоступен. Вы можете выделить и скопировать адрес." },
  },
  ar: {
    eyebrow: "أدوات العناوين", title: "حساب واحد. صيغتان للعنوان.",
    lead: "تستخدم YNX صيغة ynx1 للعناوين الأصلية. ويمثّل عنوان EVM المقابل معرّف الحساب نفسه المكوّن من 20 بايت. لا يغيّر تحويل الصيغة الأصول أو المفاتيح أو حالة الحساب.",
    boundary: "0x هي الصيغة المتوافقة مع EVM التي تستخدمها أدوات مثل MetaMask وSolidity وEVM JSON-RPC.",
    inputLabel: "عنوان الحساب", placeholder: "عنوان ynx1… أو 0x…", convert: "تحويل",
    nativeLabel: "عنوان YNX الأصلي (الافتراضي)", compatibilityLabel: "متوافق مع EVM / MetaMask", explorer: "عرض بيانات الحساب في المستكشف",
    copy: "نسخ العنوان", copied: "تم نسخ العنوان",
    errors: { invalid: "أدخل عنوان ynx1 صالحًا أو عنوانًا يبدأ بـ 0x ويتبعه 40 رمزًا بالنظام الست عشري.", checksum: "المجموع الاختباري لعنوان YNX غير صالح. تحقّق من العنوان وحاول مجددًا.", mixedCase: "لا يمكن الجمع بين الأحرف الكبيرة والصغيرة في عنوان YNX.", clipboard: "الحافظة غير متاحة. يمكنك تحديد العنوان ونسخه." },
  },
  id: {
    eyebrow: "Alat alamat", title: "Satu akun. Dua format alamat.",
    lead: "YNX menggunakan ynx1 sebagai format alamat native. Alamat EVM yang setara mewakili 20 byte akun yang sama. Konversi format tidak mengubah aset, kunci, atau status akun.",
    boundary: "0x adalah format kompatibel EVM yang digunakan oleh alat seperti MetaMask, Solidity, dan EVM JSON-RPC.",
    inputLabel: "Alamat akun", placeholder: "Alamat ynx1… atau 0x…", convert: "Konversi",
    nativeLabel: "YNX native (default)", compatibilityLabel: "Kompatibel EVM / MetaMask", explorer: "Lihat data akun di Explorer",
    copy: "Salin alamat", copied: "Alamat disalin",
    errors: { invalid: "Masukkan alamat ynx1 yang valid atau alamat 0x dengan 40 karakter heksadesimal.", checksum: "Checksum alamat YNX tidak valid. Periksa alamat dan coba lagi.", mixedCase: "Alamat YNX tidak boleh mencampur huruf besar dan kecil.", clipboard: "Papan klip tidak tersedia. Anda dapat memilih dan menyalin alamat." },
  },
};

export function getAddressConverterCopy(locale) {
  return Object.hasOwn(ADDRESS_CONVERTER_COPY, locale)
    ? ADDRESS_CONVERTER_COPY[locale]
    : ADDRESS_CONVERTER_COPY.en;
}
