import { PRODUCT_STATUS } from "../lib/ecosystemCatalog.js";

const locales = ["en", "zh-CN", "zh-TW", "ja", "ko", "es", "fr", "de", "pt", "ru", "ar", "id"];

const actionLabels = { en: ["Open / download", "Risks"], "zh-CN": ["打开 / 下载", "风险"], "zh-TW": ["開啟 / 下載", "風險"], ja: ["開く / ダウンロード", "リスク"], ko: ["열기 / 다운로드", "위험"], es: ["Abrir / descargar", "Riesgos"], fr: ["Ouvrir / télécharger", "Risques"], de: ["Öffnen / herunterladen", "Risiken"], pt: ["Abrir / baixar", "Riscos"], ru: ["Открыть / скачать", "Риски"], ar: ["فتح / تنزيل", "المخاطر"], id: ["Buka / unduh", "Risiko"] };

const language = {
  en: ["Software products under one /dapp route", "This directory separates implemented capabilities from blocked work. Every label is an evidence-backed status.", "Public web, candidate code, local builds, hosted downloads, production signing and store release are separate states.", "Try it now", "Claim 100 Testnet YNXT, then verify the transaction in Explorer.", "Find a product, workflow, or capability", "All categories", "All evidence states", "Public web", "Candidate", "Candidate incomplete", "Not ready", "Available surfaces", "No public package", "View product", "Release evidence", "No matching DApps", "Clear a filter or search by product, workflow, evidence or capability.", "Product status follows evidence.", "Code or a readiness package is not a finished application without a user workflow, security boundary, deployment and public verification."],
  "zh-CN": ["全部软件产品统一归入 /dapp 路由", "该目录区分已实现能力与受阻工作，每个状态都以证据为依据。", "公开网页、候选代码、本地构建、托管下载、生产签名与商店发布是独立状态。", "现在就试", "领取 100 测试网 YNXT，然后在 Explorer 核对交易。", "搜索产品、工作流或能力", "全部分类", "全部证据状态", "公开网页", "候选版本", "候选版本未完整", "尚未就绪", "可用平台", "暂无公开软件包", "查看产品", "发布证据", "没有匹配的 DApp", "清除筛选，或按产品、工作流、证据或能力搜索。", "产品状态服从证据。", "没有用户工作流、安全边界、部署与公网验证，代码或就绪包就不是完成的应用。"],
  "zh-TW": ["所有軟體產品統一位於 /dapp", "此目錄區分已實作能力與受阻工作，每個狀態都有證據。", "公開網頁、候選碼、本機構建、託管下載、正式簽署與商店發布是獨立狀態。", "立即試用", "領取 100 測試網 YNXT，再於 Explorer 核對交易。", "搜尋產品、流程或能力", "所有分類", "所有證據狀態", "公開網頁", "候選版本", "候選版本未完整", "尚未就緒", "可用平台", "暫無公開套件", "查看產品", "發布證據", "沒有相符的 DApp", "清除篩選，或依產品、流程、證據或能力搜尋。", "產品狀態依循證據。", "沒有使用者流程、安全邊界、部署與公開驗證，程式碼或就緒包就不是完成的應用。"],
  ja: ["すべてのソフトウェアを /dapp に整理", "実装済みと未完了を分け、各状態を証拠に基づいて表示します。", "公開Web、候補コード、ローカルビルド、ホスト済み配布、正式署名、ストア公開は別の状態です。", "今すぐ試す", "Testnet YNXTを100取得し、Explorerで取引を確認します。", "製品・ワークフロー・機能を検索", "すべてのカテゴリ", "すべての証拠状態", "公開Web", "候補", "候補は未完成", "未準備", "利用可能な面", "公開パッケージなし", "製品を見る", "リリース証拠", "一致するDAppなし", "絞り込みを解除するか、製品や機能を検索してください。", "製品状態は証拠に従います。", "利用フロー、安全境界、配備、公開検証がなければ完成したアプリではありません。"],
  ko: ["모든 소프트웨어를 /dapp에 구성", "구현된 기능과 차단된 작업을 분리하고 모든 상태를 증거로 표시합니다.", "공개 웹, 후보 코드, 로컬 빌드, 호스팅 다운로드, 운영 서명, 스토어 출시는 별도 상태입니다.", "지금 사용", "Testnet YNXT 100개를 받고 Explorer에서 거래를 확인합니다.", "제품·워크플로·기능 검색", "모든 카테고리", "모든 증거 상태", "공개 웹", "후보", "미완성 후보", "준비 안 됨", "사용 가능한 화면", "공개 패키지 없음", "제품 보기", "릴리스 증거", "일치하는 DApp 없음", "필터를 지우거나 제품과 기능을 검색하세요.", "제품 상태는 증거를 따릅니다.", "사용자 흐름, 보안 경계, 배포와 공개 검증 없이는 완성된 앱이 아닙니다."],
  es: ["Todo el software bajo /dapp", "El directorio separa capacidades implementadas de trabajo bloqueado y respalda cada estado con evidencia.", "Web pública, código candidato, compilación local, descarga alojada, firma de producción y tienda son estados separados.", "Probar ahora", "Obtén 100 YNXT de Testnet y verifica la transacción en Explorer.", "Buscar producto, flujo o capacidad", "Todas las categorías", "Todos los estados", "Web pública", "Candidato", "Candidato incompleto", "No preparado", "Superficies disponibles", "Sin paquete público", "Ver producto", "Evidencia de versión", "No hay DApps coincidentes", "Quita filtros o busca por producto, flujo, evidencia o capacidad.", "El estado sigue la evidencia.", "Sin flujo de usuario, límite de seguridad, despliegue y verificación pública no es una aplicación terminada."],
  fr: ["Tous les logiciels sous /dapp", "Le répertoire sépare les fonctions réalisées du travail bloqué et fonde chaque état sur des preuves.", "Web public, code candidat, build local, téléchargement hébergé, signature de production et store sont des états distincts.", "Essayer", "Obtenez 100 YNXT Testnet puis vérifiez la transaction dans Explorer.", "Rechercher produit, parcours ou fonction", "Toutes les catégories", "Tous les états", "Web public", "Candidat", "Candidat incomplet", "Non prêt", "Surfaces disponibles", "Aucun paquet public", "Voir le produit", "Preuve de version", "Aucune DApp correspondante", "Effacez un filtre ou recherchez par produit, parcours, preuve ou fonction.", "L'état du produit suit les preuves.", "Sans parcours utilisateur, limite de sécurité, déploiement et vérification publique, l'application n'est pas terminée."],
  de: ["Alle Softwareprodukte unter /dapp", "Das Verzeichnis trennt Umgesetztes von Blockiertem und belegt jeden Status.", "Öffentliche Web-App, Kandidatencode, lokaler Build, gehosteter Download, Produktionssignatur und Store sind getrennte Zustände.", "Jetzt testen", "100 Testnet-YNXT abrufen und die Transaktion im Explorer prüfen.", "Produkt, Ablauf oder Funktion suchen", "Alle Kategorien", "Alle Nachweisstatus", "Öffentliche Web-App", "Kandidat", "Kandidat unvollständig", "Nicht bereit", "Verfügbare Oberflächen", "Kein öffentliches Paket", "Produkt ansehen", "Release-Nachweis", "Keine passenden DApps", "Filter löschen oder nach Produkt, Ablauf, Nachweis oder Funktion suchen.", "Produktstatus folgt Nachweisen.", "Ohne Nutzerablauf, Sicherheitsgrenze, Bereitstellung und öffentliche Prüfung ist die App nicht fertig."],
  pt: ["Todos os produtos em /dapp", "O diretório separa recursos implementados de trabalho bloqueado e fundamenta cada status.", "Web pública, código candidato, build local, download hospedado, assinatura de produção e loja são estados separados.", "Testar agora", "Receba 100 YNXT da Testnet e verifique a transação no Explorer.", "Buscar produto, fluxo ou recurso", "Todas as categorias", "Todos os estados", "Web pública", "Candidato", "Candidato incompleto", "Não pronto", "Superfícies disponíveis", "Sem pacote público", "Ver produto", "Evidência de release", "Nenhum DApp encontrado", "Limpe os filtros ou busque por produto, fluxo, evidência ou recurso.", "O status segue a evidência.", "Sem fluxo de usuário, limite de segurança, implantação e verificação pública, o app não está concluído."],
  ru: ["Все продукты в маршруте /dapp", "Каталог отделяет реализованное от заблокированного и подтверждает каждый статус.", "Публичный Web, кандидатный код, локальная сборка, размещённая загрузка, производственная подпись и магазин — разные состояния.", "Попробовать", "Получите 100 тестовых YNXT и проверьте транзакцию в Explorer.", "Поиск продукта, сценария или функции", "Все категории", "Все состояния", "Публичный Web", "Кандидат", "Кандидат неполон", "Не готово", "Доступные поверхности", "Нет публичного пакета", "Открыть продукт", "Доказательство выпуска", "Подходящих DApp нет", "Сбросьте фильтры или ищите по продукту, сценарию, доказательству или функции.", "Статус продукта следует доказательствам.", "Без пользовательского сценария, границы безопасности, развёртывания и публичной проверки приложение не завершено."],
  ar: ["جميع البرامج ضمن /dapp", "يفصل الدليل القدرات المنفذة عن العمل المتعثر ويربط كل حالة بالدليل.", "الويب العام والكود المرشح والبناء المحلي والتنزيل المستضاف وتوقيع الإنتاج والمتجر حالات مستقلة.", "جرّبه الآن", "احصل على 100 YNXT اختبارية ثم تحقق من المعاملة في Explorer.", "ابحث عن منتج أو مسار أو قدرة", "كل الفئات", "كل حالات الدليل", "ويب عام", "مرشح", "مرشح غير مكتمل", "غير جاهز", "الواجهات المتاحة", "لا حزمة عامة", "عرض المنتج", "دليل الإصدار", "لا توجد DApps مطابقة", "أزل المرشح أو ابحث حسب المنتج أو المسار أو الدليل أو القدرة.", "حالة المنتج تتبع الدليل.", "من دون مسار مستخدم وحدود أمان ونشر وتحقق عام لا يكون التطبيق مكتملًا."],
  id: ["Semua produk di bawah /dapp", "Direktori memisahkan kemampuan yang sudah dibuat dari pekerjaan terhambat dan mendasari setiap status dengan bukti.", "Web publik, kode kandidat, build lokal, unduhan hosted, signing produksi, dan store adalah status terpisah.", "Coba sekarang", "Klaim 100 YNXT Testnet lalu verifikasi transaksi di Explorer.", "Cari produk, alur, atau kemampuan", "Semua kategori", "Semua status bukti", "Web publik", "Kandidat", "Kandidat belum lengkap", "Belum siap", "Permukaan tersedia", "Tidak ada paket publik", "Lihat produk", "Bukti rilis", "Tidak ada DApp yang cocok", "Hapus filter atau cari berdasarkan produk, alur, bukti, atau kemampuan.", "Status produk mengikuti bukti.", "Tanpa alur pengguna, batas keamanan, deployment, dan verifikasi publik, aplikasi belum selesai."],
};

const categories = {
  en: [["Money & commerce", "Payments, markets, merchants, finance and exchange."], ["Identity & community", "Custody, communication, collaboration and calendars."], ["Build & operate", "Developer, observability, chain data and discovery tools."], ["AI, media & data", "AI workflows, content, storage and creator tools."], ["Trust & infrastructure", "Evidence, governance, appeals and settlement boundaries."]],
  "zh-CN": [["货币与商业", "支付、市场、商户、金融与交易。"], ["身份与社区", "保管、通信、协作与日程。"], ["构建与运维", "开发、可观测性、链数据与发现工具。"], ["AI、媒体与数据", "AI 工作流、内容、存储与创作工具。"], ["信任与基础设施", "证据、治理、申诉与结算边界。"]],
  "zh-TW": [["貨幣與商業", "支付、市場、商戶、金融與交易。"], ["身分與社群", "保管、通信、協作與日程。"], ["建置與運維", "開發、可觀測性、鏈資料與發現工具。"], ["AI、媒體與資料", "AI 流程、內容、儲存與創作工具。"], ["信任與基礎設施", "證據、治理、申訴與結算邊界。"]],
};

for (const locale of locales.slice(3)) categories[locale] = [["Commerce", "Payments and markets."], ["Identity", "Custody and community."], ["Build", "Developer and operations tools."], ["AI & media", "Content and data tools."], ["Trust", "Evidence and infrastructure."]];

const safety = {
  en: ["Download center", "Public products and installable releases, separated.", "Only immutable hosted artifacts or verified public web surfaces are links. Local builds remain visible as evidence, not downloads.", "Available now", "Verified official downloads", "Only supported, hash-registered Testnet Preview artifacts appear here. Shop Android is retired; Shop Web/PWA remains available.", "Other products", "Web entries and release status", "Products without installers clearly show web, candidate or not-ready state.", "No fake release states.", "Test signatures and local build folders are not production releases. Downloads require URL, hash, size, signing class and install evidence. Testnet Previews may reset; never import real assets or production private keys.", "Machine-readable release registry"],
  "zh-CN": ["下载中心", "公开产品与可安装发布明确分开。", "只有不可变托管工件或已验证公开网页才提供链接。本地构建只是证据，不是下载。", "现在可下载", "已验证的官网下载", "这里只显示受支持且已登记哈希的 Testnet Preview。Shop Android 已退役；Shop Web/PWA 仍可用。", "其他产品", "网页入口与发布状态", "没有安装包的产品明确显示网页、候选或未就绪状态。", "不伪造发布状态。", "测试签名和本地构建不是生产发布。下载必须具备 URL、哈希、大小、签名类别与安装证据。Testnet Preview 可能重置；绝不导入真实资产或生产私钥。", "机器可读发布登记表"],
  "zh-TW": ["下載中心", "公開產品與可安裝發布明確分開。", "只有不可變託管工件或已驗證公開網頁才提供連結。本機構建只是證據，不是下載。", "現在可下載", "已驗證的官方下載", "僅顯示受支援且已登記雜湊的 Testnet Preview。Shop Android 已退役；Shop Web/PWA 仍可用。", "其他產品", "網頁入口與發布狀態", "沒有安裝包的產品明確顯示網頁、候選或未就緒。", "不偽造發布狀態。", "測試簽署和本機構建不是正式發布。下載必須具備 URL、雜湊、大小、簽署類別與安裝證據。Testnet Preview 可能重置；絕不匯入真實資產或正式私鑰。", "機器可讀發布登記表"],
};

const translatedSafety = {
  ja: ["ダウンロードセンター", "公開製品とインストール可能版を分離。", "不変ホスト済み成果物または検証済み公開Webだけをリンクします。ローカルビルドは証拠でありダウンロードではありません。", "現在利用可能", "検証済み公式ダウンロード", "対応中でハッシュ登録済みのTestnet Previewのみ表示します。Shop Androidは廃止、Web/PWAは利用可能です。", "その他の製品", "Web入口とリリース状態", "インストーラーなしの製品は状態を明示します。", "偽のリリース状態は表示しません。", "テスト署名やローカルビルドは正式版ではありません。URL、ハッシュ、サイズ、署名種別、導入証拠が必要です。Testnetはリセットされ得るため実資産や本番秘密鍵を入れないでください。", "機械可読リリース台帳"],
  ko: ["다운로드 센터", "공개 제품과 설치 가능한 릴리스를 분리합니다.", "불변 호스팅 아티팩트나 검증된 공개 웹만 링크합니다. 로컬 빌드는 증거이지 다운로드가 아닙니다.", "지금 사용 가능", "검증된 공식 다운로드", "지원 중이며 해시 등록된 Testnet Preview만 표시합니다. Shop Android는 폐기되었고 Web/PWA는 사용 가능합니다.", "기타 제품", "웹 진입점과 릴리스 상태", "설치 파일이 없는 제품은 상태를 명확히 표시합니다.", "가짜 릴리스 상태 없음.", "테스트 서명과 로컬 빌드는 운영 릴리스가 아닙니다. URL, 해시, 크기, 서명 종류, 설치 증거가 필요합니다. Testnet은 재설정될 수 있으니 실제 자산이나 운영 개인 키를 가져오지 마십시오.", "기계 판독 릴리스 레지스트리"],
  es: ["Centro de descargas", "Productos públicos y versiones instalables, separados.", "Solo enlazamos artefactos inmutables alojados o webs públicas verificadas. Los builds locales son evidencia, no descargas.", "Disponible ahora", "Descargas oficiales verificadas", "Solo aparecen Testnet Preview soportadas y con hash registrado. Shop Android está retirado; Web/PWA sigue disponible.", "Otros productos", "Entradas web y estado", "Los productos sin instalador muestran su estado claramente.", "Sin estados de versión falsos.", "Firmas de prueba y builds locales no son producción. Se requieren URL, hash, tamaño, clase de firma y prueba de instalación. Testnet puede reiniciarse; nunca importes activos reales ni claves privadas de producción.", "Registro de versiones legible por máquina"],
  fr: ["Centre de téléchargement", "Produits publics et versions installables séparés.", "Seuls les artefacts immuables hébergés ou les sites publics vérifiés sont liés. Les builds locaux sont des preuves, pas des téléchargements.", "Disponible maintenant", "Téléchargements officiels vérifiés", "Seuls les Testnet Preview supportés avec hash enregistré apparaissent. Shop Android est retiré ; Web/PWA reste disponible.", "Autres produits", "Entrées Web et état", "Les produits sans installateur affichent clairement leur état.", "Aucun faux état de version.", "Les signatures de test et builds locaux ne sont pas des versions de production. URL, hash, taille, classe de signature et preuve d'installation sont requis. Le Testnet peut être réinitialisé ; n'importez jamais d'actifs réels ni de clés privées de production.", "Registre de versions lisible par machine"],
  de: ["Download-Center", "Öffentliche Produkte und installierbare Releases getrennt.", "Nur unveränderlich gehostete Artefakte oder geprüfte öffentliche Web-Flächen werden verlinkt. Lokale Builds sind Nachweise, keine Downloads.", "Jetzt verfügbar", "Geprüfte offizielle Downloads", "Nur unterstützte, hash-registrierte Testnet Previews erscheinen. Shop Android ist eingestellt; Web/PWA bleibt verfügbar.", "Weitere Produkte", "Web-Einstiege und Release-Status", "Produkte ohne Installer zeigen ihren Status klar.", "Keine erfundenen Release-Status.", "Testsignaturen und lokale Builds sind keine Produktionsreleases. URL, Hash, Größe, Signaturklasse und Installationsnachweis sind erforderlich. Testnet kann zurückgesetzt werden; niemals echte Werte oder Produktionsschlüssel importieren.", "Maschinenlesbares Release-Register"],
  pt: ["Central de downloads", "Produtos públicos e releases instaláveis separados.", "Só vinculamos artefatos imutáveis hospedados ou webs públicas verificadas. Builds locais são evidência, não downloads.", "Disponível agora", "Downloads oficiais verificados", "Só aparecem Testnet Previews suportados e com hash registrado. Shop Android foi descontinuado; Web/PWA continua disponível.", "Outros produtos", "Entradas web e status", "Produtos sem instalador mostram o status claramente.", "Sem estados falsos de release.", "Assinaturas de teste e builds locais não são produção. URL, hash, tamanho, classe de assinatura e prova de instalação são obrigatórios. A Testnet pode reiniciar; nunca importe ativos reais nem chaves privadas de produção.", "Registro de release legível por máquina"],
  ru: ["Центр загрузок", "Публичные продукты и устанавливаемые выпуски разделены.", "Ссылки ведут только на неизменяемые размещённые артефакты или проверенные публичные сайты. Локальные сборки — доказательство, не загрузка.", "Доступно сейчас", "Проверенные официальные загрузки", "Показаны только поддерживаемые Testnet Preview с зарегистрированным хешем. Shop Android снят; Web/PWA доступен.", "Другие продукты", "Web-входы и статус выпуска", "Продукты без установщика ясно показывают статус.", "Без ложных статусов выпуска.", "Тестовые подписи и локальные сборки не являются production. Нужны URL, хеш, размер, класс подписи и доказательство установки. Testnet может сброситься; не импортируйте реальные активы или production-ключи.", "Машиночитаемый реестр выпусков"],
  ar: ["مركز التنزيل", "فصل المنتجات العامة عن الإصدارات القابلة للتثبيت.", "نربط فقط بملفات مستضافة غير قابلة للتغيير أو مواقع عامة متحقق منها. البناء المحلي دليل وليس تنزيلًا.", "متاح الآن", "تنزيلات رسمية متحقق منها", "تظهر فقط معاينات Testnet المدعومة والمسجلة بالهاش. أوقف Shop Android وتظل Web/PWA متاحة.", "منتجات أخرى", "مداخل الويب وحالة الإصدار", "تعرض المنتجات بلا مثبّت حالتها بوضوح.", "لا حالات إصدار زائفة.", "توقيعات الاختبار والبناء المحلي ليست إنتاجًا. يلزم URL وهاش وحجم وفئة توقيع ودليل تثبيت. قد يعاد ضبط Testnet؛ لا تستورد أصولًا حقيقية أو مفاتيح إنتاج خاصة.", "سجل إصدارات قابل للقراءة آليًا"],
  id: ["Pusat unduhan", "Produk publik dan rilis yang dapat dipasang dipisahkan.", "Hanya artefak immutable yang di-host atau web publik terverifikasi yang ditautkan. Build lokal adalah bukti, bukan unduhan.", "Tersedia sekarang", "Unduhan resmi terverifikasi", "Hanya Testnet Preview yang didukung dan terdaftar hash-nya. Shop Android dihentikan; Web/PWA tetap tersedia.", "Produk lain", "Entri web dan status rilis", "Produk tanpa installer menampilkan status dengan jelas.", "Tanpa status rilis palsu.", "Tanda tangan uji dan build lokal bukan rilis produksi. URL, hash, ukuran, kelas signing, dan bukti instalasi wajib ada. Testnet dapat direset; jangan impor aset nyata atau kunci privat produksi.", "Registri rilis terbaca mesin"],
};
Object.assign(safety, translatedSafety);

const faucet = {
  en: ["Claim test coins. Verify the real transaction.", "Enter a YNX or compatible 0x address. The Faucet sends 100 Testnet YNXT and returns a hash for Explorer verification.", "Claim YNXT Testnet coins", "Claim amount", "Receiving address", "Valid address", "Will be sent on-chain to", "I understand this Testnet asset has no represented monetary value, and I will never enter a seed phrase or private key.", "Submitting real transaction…", "Claim", "Nothing was sent", "Try again", "Testnet transfer submitted", "View RPC record", "Done", "Claim rules", "Four clear steps", "Copy an address", "Use only an address controlled by your Wallet.", "Validate and claim", "One claim per IP/address per hour, fixed at 100 YNXT.", "Wait for finality", "A timeout stays unknown; it never becomes fake success.", "Verify the transfer", "Compare From, To, amount, fee and block in Explorer.", "Security boundary", "The Faucet needs only a public address. It never asks for a seed phrase, private key, payment or Wallet approval.", "View runtime and verified transaction evidence", "Faucet status", "Verified · RPC backed", "one claim per IP/address per hour", "Temporarily unavailable", "Retry connection", "Connecting…", "This IP or address has already claimed during the one-hour window.", "Faucet connection unavailable. Retry after the public service is reachable."],
  "zh-CN": ["领取测试币，然后验证真实交易。", "输入 YNX 或兼容 0x 地址。Faucet 发送 100 测试网 YNXT，并返回可在 Explorer 核验的哈希。", "领取 YNXT 测试币", "本次领取", "收款地址", "有效地址", "链上将使用", "我理解这是没有货币价值的测试网资产，并且绝不会输入助记词或私钥。", "正在提交真实交易…", "领取", "未发送", "返回重试", "测试币交易已提交", "查看 RPC 记录", "完成", "领取规则", "四步完成", "复制地址", "只使用你控制的钱包地址。", "验证并领取", "每个 IP/地址每小时一次，固定 100 YNXT。", "等待最终确认", "超时属于未知状态，不会显示虚假成功。", "核对交易", "在 Explorer 对比 From、To、金额、手续费和区块。", "安全边界", "Faucet 只需要公开地址，绝不会要求助记词、私钥、付款或钱包授权。", "查看运行版本与真实交易验证记录", "Faucet 状态", "已验证 · RPC 支持", "每个 IP/地址每小时一次", "暂时不可用", "重试连接", "正在连接…", "该 IP 或地址一小时内已经领取过，请稍后再试。", "Faucet 连接不可用，请在公开服务恢复后重试。"],
};

const faucetCompact = {
  "zh-TW": ["領取測試幣並驗證真實交易。", "輸入 YNX 或相容 0x 位址。Faucet 傳送 100 測試網 YNXT 並回傳可驗證雜湊。", "我了解此測試網資產沒有貨幣價值，絕不輸入助記詞或私鑰。", "逾時保持未知，不會顯示虛假成功。", "Faucet 只需要公開位址，絕不要求助記詞、私鑰、付款或錢包授權。"],
  ja: ["テストコインを取得し、実際の取引を検証。", "YNX または互換 0x アドレスを入力すると、100 Testnet YNXT と検証用ハッシュが返ります。", "このTestnet資産に金銭価値がなく、シードフレーズや秘密鍵を入力しないことを理解しました。", "タイムアウトは不明のままで、偽の成功にはなりません。", "Faucet は公開アドレスだけを必要とし、シード、秘密鍵、支払い、Wallet承認を要求しません。"],
  ko: ["테스트 코인을 받고 실제 거래를 검증하세요.", "YNX 또는 호환 0x 주소를 입력하면 100 Testnet YNXT와 검증용 해시를 반환합니다.", "이 Testnet 자산에는 금전 가치가 없으며 시드 문구나 개인 키를 입력하지 않겠습니다.", "시간 초과는 알 수 없음으로 유지되며 가짜 성공이 되지 않습니다.", "Faucet은 공개 주소만 필요하며 시드, 개인 키, 결제 또는 Wallet 승인을 요구하지 않습니다."],
  es: ["Obtén monedas de prueba y verifica la transacción real.", "Introduce una dirección YNX o 0x compatible; recibirás 100 YNXT Testnet y un hash verificable.", "Entiendo que este activo Testnet no tiene valor monetario representado y nunca introduciré semilla ni clave privada.", "Un timeout permanece desconocido; nunca se convierte en éxito falso.", "Faucet solo necesita una dirección pública; nunca pide semilla, clave privada, pago ni aprobación del monedero."],
  fr: ["Obtenez des jetons de test et vérifiez la transaction réelle.", "Saisissez une adresse YNX ou 0x compatible ; 100 YNXT Testnet et un hash vérifiable seront renvoyés.", "Je comprends que cet actif Testnet n'a pas de valeur monétaire représentée et je ne saisirai jamais de phrase de récupération ni de clé privée.", "Un délai dépassé reste inconnu et ne devient jamais un faux succès.", "Le Faucet ne demande qu'une adresse publique, jamais une phrase, clé privée, paiement ou approbation Wallet."],
  de: ["Testmünzen abrufen und echte Transaktion prüfen.", "YNX- oder kompatible 0x-Adresse eingeben; 100 Testnet-YNXT und ein prüfbarer Hash werden zurückgegeben.", "Ich verstehe, dass dieses Testnet-Asset keinen dargestellten Geldwert hat, und gebe niemals Seed-Phrase oder privaten Schlüssel ein.", "Ein Timeout bleibt unbekannt und wird nie als Erfolg dargestellt.", "Der Faucet benötigt nur eine öffentliche Adresse und fragt nie nach Seed, privatem Schlüssel, Zahlung oder Wallet-Freigabe."],
  pt: ["Receba moedas de teste e verifique a transação real.", "Informe um endereço YNX ou 0x compatível; serão enviados 100 YNXT Testnet e um hash verificável.", "Entendo que este ativo Testnet não tem valor monetário representado e nunca informarei seed ou chave privada.", "Timeout permanece desconhecido e nunca vira sucesso falso.", "O Faucet precisa apenas de endereço público; nunca pede seed, chave privada, pagamento ou aprovação da carteira."],
  ru: ["Получите тестовые монеты и проверьте реальную транзакцию.", "Введите YNX или совместимый 0x-адрес; Faucet отправит 100 Testnet YNXT и вернёт проверяемый хеш.", "Я понимаю, что этот актив Testnet не имеет заявленной денежной стоимости, и никогда не введу seed-фразу или закрытый ключ.", "Тайм-аут остаётся неизвестным состоянием и не становится ложным успехом.", "Faucet нужен только публичный адрес; он не просит seed, закрытый ключ, оплату или одобрение Wallet."],
  ar: ["احصل على عملات اختبار وتحقق من المعاملة الحقيقية.", "أدخل عنوان YNX أو 0x متوافقًا؛ يرسل Faucet مقدار 100 YNXT اختبارية ويعيد هاشًا قابلاً للتحقق.", "أفهم أن أصل Testnet هذا بلا قيمة نقدية ممثلة ولن أدخل عبارة استرداد أو مفتاحًا خاصًا.", "تبقى المهلة حالة مجهولة ولا تتحول إلى نجاح زائف.", "يحتاج Faucet إلى عنوان عام فقط ولا يطلب عبارة استرداد أو مفتاحًا خاصًا أو دفعًا أو موافقة Wallet."],
  id: ["Klaim koin uji dan verifikasi transaksi nyata.", "Masukkan alamat YNX atau 0x kompatibel; Faucet mengirim 100 YNXT Testnet dan mengembalikan hash yang dapat diverifikasi.", "Saya memahami aset Testnet ini tidak memiliki nilai uang yang dinyatakan dan tidak akan memasukkan seed phrase atau kunci privat.", "Timeout tetap tidak diketahui dan tidak pernah menjadi sukses palsu.", "Faucet hanya memerlukan alamat publik; tidak pernah meminta seed, kunci privat, pembayaran, atau persetujuan Wallet."],
};

for (const [locale, v] of Object.entries(faucetCompact)) faucet[locale] = [v[0], v[1], "Claim YNXT Testnet", "Claim amount", "Receiving address", "Valid address", "On-chain destination", v[2], "Submitting transaction…", "Claim", "Nothing sent", "Try again", "Testnet transfer submitted", "View RPC record", "Done", "Claim rules", "Four steps", "Copy address", "Use an address you control.", "Validate and claim", "One claim per IP/address per hour, fixed 100 YNXT.", "Wait for finality", v[3], "Verify transfer", "Compare From, To, amount, fee and block in Explorer.", "Security boundary", v[4], "View runtime evidence", "Faucet status", "Verified · RPC", "one claim per IP/address per hour", "Temporarily unavailable", "Retry", "Connecting…", "Claim limit reached for this hour.", "Faucet connection unavailable; retry when public service returns."];

export function getAppsCopy(locale) {
  const v = language[locale];
  if (!v || !categories[locale]) return null;
  return { openDownload: actionLabels[locale][0], risks: actionLabels[locale][1], title: v[0], lead: v[1], statusLead: v[2], tryEyebrow: v[3], tryLead: v[4], search: v[5], allCategories: v[6], statusFilters: [["all", v[7]], [PRODUCT_STATUS.LIVE, v[8]], [PRODUCT_STATUS.LOCAL, v[9]], [PRODUCT_STATUS.PLANNED, v[10]]], statusLabels: { [PRODUCT_STATUS.LIVE]: v[8], [PRODUCT_STATUS.LOCAL]: v[9], [PRODUCT_STATUS.PLANNED]: v[10], [PRODUCT_STATUS.NOT_READY]: v[11] }, available: v[12], noPackage: v[13], view: v[14], release: v[15], noneTitle: v[16], noneLead: v[17], boundaryTitle: v[18], boundary: v[19], categories: categories[locale] };
}

export function getDownloadCopy(locale) {
  const v = safety[locale];
  const common = language[locale];
  if (!v || !common) return null;
  return { hero: v.slice(0, 3), available: v.slice(3, 6), other: v.slice(6, 9), boundary: v.slice(9, 12), statusLabels: { [PRODUCT_STATUS.LIVE]: common[8], [PRODUCT_STATUS.LOCAL]: common[9], [PRODUCT_STATUS.PLANNED]: common[10], [PRODUCT_STATUS.NOT_READY]: common[11] }, download: locale === "zh-CN" ? "从官网下载" : locale === "zh-TW" ? "從官方下載" : "Official download", unavailable: common[11], evidence: locale === "zh-CN" ? ["版本", "大小", "签名", "来源提交", "安装验证", "发布证据"] : locale === "zh-TW" ? ["版本", "大小", "簽署", "來源提交", "安裝驗證", "發布證據"] : ["Version", "Size", "Signing", "Source commit", "Install proof", "Release evidence"], view: locale === "en" ? "View release status" : common[14] };
}

export function getFaucetCopy(locale) {
  const v = faucet[locale];
  if (!v) return null;
  return { hero: v.slice(0, 2), aria: v[2], amount: v[3], receiving: v[4], valid: v[5], canonical: v[6], consent: v[7], submitting: v[8], claim: v[9], errorTitle: v[10], retry: v[11], successTitle: v[12], rpc: v[13], done: v[14], rulesEyebrow: v[15], rulesTitle: v[16], steps: [[v[17], v[18]], [v[19], v[20]], [v[21], v[22]], [v[23], v[24]]], securityTitle: v[25], security: v[26], evidence: v[27], service: { label: v[28], ready: v[29], limit: v[30], unavailable: v[31], retry: v[32], connecting: v[33] }, rateLimit: v[34], connectionError: v[35] };
}

export { locales as BUSINESS_LOCALES };
