// Public Card copy describes the deployed Testnet simulation, never issuance.
// Source IDs, chain IDs, URLs and file hashes stay language-independent.
const cardCopy = {
  en: ["Public Testnet Card simulation for review; private Wallet approval, provider-issued cards, funding and real payments are not verified.", "The public Card Testnet simulation UI and v1/v2 routes run from e95fcf443. Unauthenticated private requests are rejected. Wallet approval, funding, provider Sandbox issuance and real payments remain unverified.", "Public Testnet simulation UI. No real card issuance or production payment.", "Surface", "Risk", "Boundary", "Public Testnet simulation UI and v1/v2 API routes", "Wallet approval and issuer evidence are absent", "No real card or production payment"],
  "zh-CN": ["公开测试网 Card 模拟页面可供体验；私有 Wallet 授权、服务商发卡、入金和真实支付均未验证。", "公开 Card 测试网模拟页面及 v1/v2 路由来自 e95fcf443。未授权的私有请求会被拒绝；Wallet 授权、入金、服务商 Sandbox 发卡和真实支付仍未验证。", "公开测试网模拟页面；没有真实发卡或生产支付。", "界面", "风险", "边界", "公开测试网模拟页面与 v1/v2 API 路由", "尚无 Wallet 授权及发卡方证据", "没有真实卡或生产支付"],
  "zh-TW": ["公開測試網 Card 模擬頁面可供體驗；私人 Wallet 授權、服務商發卡、入金及真實支付均未驗證。", "公開 Card 測試網模擬頁面及 v1/v2 路由來自 e95fcf443。未授權的私人請求會被拒絕；Wallet 授權、入金、服務商 Sandbox 發卡及真實支付仍未驗證。", "公開測試網模擬頁面；沒有真實發卡或正式支付。", "介面", "風險", "界限", "公開測試網模擬頁面與 v1/v2 API 路由", "尚無 Wallet 授權及發卡方證據", "沒有真實卡或正式支付"],
  ja: ["公開テストネットの Card シミュレーション画面です。非公開の Wallet 承認、プロバイダーによる発行、入金、実決済は未検証です。", "公開 Card テストネット画面と v1/v2 ルートは e95fcf443 から配信されています。未認証の非公開リクエストは拒否されます。Wallet 承認、入金、プロバイダー Sandbox の発行、実決済は未検証です。", "公開テストネットのシミュレーション画面。実カードの発行や本番決済はありません。", "公開範囲", "リスク", "境界", "公開テストネット画面と v1/v2 API ルート", "Wallet 承認と発行元の証拠は未確認", "実カード・本番決済なし"],
  ko: ["공개 테스트넷 Card 시뮬레이션 화면입니다. 비공개 Wallet 승인, 제공업체 카드 발급, 자금 입금 및 실제 결제는 검증되지 않았습니다.", "공개 Card 테스트넷 화면과 v1/v2 경로는 e95fcf443에서 제공됩니다. 인증되지 않은 비공개 요청은 거부됩니다. Wallet 승인, 입금, 제공업체 Sandbox 발급 및 실제 결제는 아직 검증되지 않았습니다.", "공개 테스트넷 시뮬레이션 화면이며 실제 카드 발급이나 운영 결제는 없습니다.", "공개 범위", "위험", "경계", "공개 테스트넷 화면 및 v1/v2 API 경로", "Wallet 승인 및 발급사 증거 없음", "실제 카드 또는 운영 결제 없음"],
  es: ["Vista pública de simulación Card en Testnet. No se han verificado la aprobación privada de Wallet, la emisión por proveedor, la financiación ni los pagos reales.", "La interfaz pública Card de Testnet y las rutas v1/v2 proceden de e95fcf443. Se rechazan las solicitudes privadas sin autenticar. La aprobación de Wallet, la financiación, la emisión en Sandbox y los pagos reales siguen sin verificarse.", "Interfaz pública de simulación Testnet; no emite tarjetas reales ni procesa pagos de producción.", "Superficie", "Riesgo", "Límite", "Interfaz pública Testnet y rutas API v1/v2", "Sin pruebas de aprobación de Wallet ni del emisor", "Sin tarjeta real ni pago de producción"],
  fr: ["Interface publique de simulation Card sur Testnet. L'approbation privée Wallet, l'émission par un fournisseur, le financement et les paiements réels ne sont pas vérifiés.", "L'interface Card publique et les routes v1/v2 de Testnet proviennent de e95fcf443. Les requêtes privées non authentifiées sont refusées. L'approbation Wallet, le financement, l'émission Sandbox et les paiements réels restent non vérifiés.", "Interface publique de simulation Testnet ; aucune carte réelle ni paiement de production.", "Surface", "Risque", "Limite", "Interface Testnet publique et routes API v1/v2", "Aucune preuve d'approbation Wallet ou d'émetteur", "Aucune carte réelle ni paiement de production"],
  de: ["Öffentliche Card-Simulation im Testnet. Private Wallet-Freigabe, Kartenausgabe durch Anbieter, Einzahlung und echte Zahlungen sind nicht verifiziert.", "Die öffentliche Card-Testnet-Oberfläche und die v1/v2-Routen stammen aus e95fcf443. Nicht authentifizierte private Anfragen werden abgewiesen. Wallet-Freigabe, Einzahlung, Sandbox-Kartenausgabe und echte Zahlungen sind nicht verifiziert.", "Öffentliche Testnet-Simulation; keine echte Kartenausgabe oder Produktivzahlung.", "Oberfläche", "Risiko", "Grenze", "Öffentliche Testnet-Oberfläche und v1/v2-API-Routen", "Keine Nachweise für Wallet-Freigabe oder Herausgeber", "Keine echte Karte oder Produktivzahlung"],
  pt: ["Interface pública de simulação Card na Testnet. A aprovação privada da Wallet, a emissão por fornecedor, o financiamento e os pagamentos reais não foram verificados.", "A interface pública Card e as rotas v1/v2 da Testnet vêm de e95fcf443. Pedidos privados sem autenticação são rejeitados. Aprovação Wallet, financiamento, emissão Sandbox e pagamentos reais continuam sem verificação.", "Interface pública de simulação Testnet; sem emissão de cartão real nem pagamento em produção.", "Superfície", "Risco", "Limite", "Interface pública Testnet e rotas API v1/v2", "Sem prova de aprovação Wallet ou do emissor", "Sem cartão real nem pagamento em produção"],
  ru: ["Публичный интерфейс симуляции Card в тестовой сети. Закрытое одобрение Wallet, выпуск карт провайдером, пополнение и реальные платежи не подтверждены.", "Публичный интерфейс Card и маршруты v1/v2 тестовой сети выпущены из e95fcf443. Неаутентифицированные закрытые запросы отклоняются. Одобрение Wallet, пополнение, выпуск в Sandbox и реальные платежи не подтверждены.", "Публичная симуляция в тестовой сети; без выпуска настоящих карт и рабочих платежей.", "Доступно", "Риск", "Граница", "Публичный интерфейс Testnet и маршруты API v1/v2", "Нет подтверждения Wallet и эмитента", "Нет настоящей карты или рабочего платежа"],
  ar: ["واجهة محاكاة Card عامة على الشبكة التجريبية. لم يُتحقق من موافقة Wallet الخاصة أو إصدار البطاقات من المزود أو التمويل أو المدفوعات الحقيقية.", "واجهة Card العامة ومسارات v1/v2 للشبكة التجريبية منشورة من e95fcf443. تُرفض الطلبات الخاصة غير الموثقة. ما زالت موافقة Wallet والتمويل وإصدار Sandbox والمدفوعات الحقيقية غير متحقق منها.", "واجهة محاكاة عامة للشبكة التجريبية؛ لا إصدار لبطاقات حقيقية ولا مدفوعات إنتاجية.", "الواجهة", "المخاطر", "الحدود", "واجهة الشبكة التجريبية العامة ومسارات API v1/v2", "لا دليل على موافقة Wallet أو الجهة المصدرة", "لا بطاقة حقيقية ولا دفع إنتاجي"],
  id: ["Antarmuka simulasi Card Testnet publik. Persetujuan Wallet privat, penerbitan kartu oleh penyedia, pendanaan, dan pembayaran nyata belum terverifikasi.", "Antarmuka Card Testnet publik dan rute v1/v2 berasal dari e95fcf443. Permintaan privat tanpa autentikasi ditolak. Persetujuan Wallet, pendanaan, penerbitan Sandbox, dan pembayaran nyata belum terverifikasi.", "Antarmuka simulasi Testnet publik; tidak ada penerbitan kartu nyata atau pembayaran produksi.", "Antarmuka", "Risiko", "Batas", "Antarmuka Testnet publik dan rute API v1/v2", "Belum ada bukti persetujuan Wallet atau penerbit", "Tidak ada kartu nyata atau pembayaran produksi"],
};

export function localizeCardProduct(product, locale) {
  if (product?.key !== "card") return product;
  const v = cardCopy[locale] || cardCopy.en;
  return {
    ...product,
    detail: v[0],
    release: { ...product.release, statusNote: v[1] },
    downloads: { ...product.downloads, web: { ...product.downloads.web, note: v[2] } },
    metrics: [[v[3], v[6]], [v[4], v[7]], [v[5], v[8]]],
  };
}

export const CARD_PUBLIC_LOCALES = Object.keys(cardCopy);
