export const FOUNDER_EMAIL = "Founder@ynxweb4.com";
const copy = {
  en: ["Contact us", "Let’s talk about what’s next.", "Have an idea, a question or something to share? Meet the YNX community or write directly to the founder.", "Talk to the founder", "For project questions, feedback and collaboration, send us an email.", "Write an email", "Your email app will open with the recipient filled in.", "Get started", "API reference", "Documentation", "Whitepapers"],
  "zh-CN": ["联系我们", "聊聊你的下一个想法。", "有想法、问题，或想分享正在做的事情？加入 YNX 社区，也可以直接给创始人写邮件。", "和创始人聊一聊", "项目咨询、使用反馈与合作交流，欢迎通过邮件联系我们。", "给创始人写邮件", "将打开你的邮件客户端，并自动填写收件人。", "开始手册", "API 手册", "文档中心", "白皮书"],
  "zh-TW": ["聯絡我們", "聊聊你的下一個想法。", "有想法、問題，或想分享正在做的事？加入 YNX 社群，也可以直接寫信給創辦人。", "和創辦人聊一聊", "專案諮詢、使用回饋與合作交流，歡迎透過電子郵件聯絡我們。", "寫信給創辦人", "將開啟你的郵件程式，並自動填入收件人。", "入門手冊", "API 手冊", "文件中心", "白皮書"],
  ja: ["お問い合わせ", "次のアイデアを話しましょう。", "アイデアや質問、共有したいことはありますか。YNX コミュニティに参加するか、創業者へ直接メールを送れます。", "創業者と話す", "プロジェクトへの質問、フィードバック、協業のご相談をメールでお寄せください。", "メールを書く", "メールアプリが開き、宛先が自動入力されます。", "入門ガイド", "API リファレンス", "ドキュメント", "ホワイトペーパー"],
  ko: ["문의하기", "다음 아이디어를 나눠요.", "아이디어, 질문 또는 공유할 소식이 있나요? YNX 커뮤니티에 참여하거나 창립자에게 직접 이메일을 보내세요.", "창립자와 이야기하기", "프로젝트 문의, 사용 의견, 협업 제안을 이메일로 보내주세요.", "이메일 쓰기", "받는 사람이 입력된 이메일 앱이 열립니다.", "시작 안내서", "API 안내서", "문서 센터", "백서"],
  es: ["Contacto", "Hablemos de tu próxima idea.", "¿Tienes una idea, una pregunta o algo que compartir? Únete a la comunidad YNX o escribe directamente al fundador.", "Habla con el fundador", "Envíanos un correo para consultas, comentarios o propuestas de colaboración.", "Escribir un correo", "Se abrirá tu aplicación de correo con el destinatario indicado.", "Guía de inicio", "Referencia API", "Documentación", "Libros blancos"],
  fr: ["Nous contacter", "Parlons de votre prochaine idée.", "Une idée, une question ou quelque chose à partager ? Rejoignez la communauté YNX ou écrivez directement au fondateur.", "Parler au fondateur", "Envoyez-nous vos questions, retours et propositions de collaboration par e-mail.", "Écrire un e-mail", "Votre application de messagerie s’ouvrira avec le destinataire renseigné.", "Guide de démarrage", "Référence API", "Documentation", "Livres blancs"],
  de: ["Kontakt", "Sprechen wir über deine nächste Idee.", "Eine Idee, eine Frage oder etwas zu teilen? Triff die YNX-Community oder schreibe direkt an den Gründer.", "Mit dem Gründer sprechen", "Schicke uns Fragen, Feedback oder Vorschläge zur Zusammenarbeit per E-Mail.", "E-Mail schreiben", "Dein E-Mail-Programm öffnet sich mit eingetragenem Empfänger.", "Erste Schritte", "API-Referenz", "Dokumentation", "Whitepaper"],
  pt: ["Fale conosco", "Vamos falar da sua próxima ideia.", "Tem uma ideia, pergunta ou algo para compartilhar? Entre na comunidade YNX ou escreva diretamente ao fundador.", "Converse com o fundador", "Envie dúvidas, sugestões e propostas de colaboração por e-mail.", "Escrever e-mail", "Seu aplicativo de e-mail será aberto com o destinatário preenchido.", "Primeiros passos", "Referência da API", "Documentação", "Whitepapers"],
  ru: ["Связаться с нами", "Обсудим вашу следующую идею.", "Есть идея, вопрос или новость? Присоединяйтесь к сообществу YNX или напишите основателю напрямую.", "Поговорить с основателем", "Напишите нам по вопросам проекта, для обратной связи и предложений о сотрудничестве.", "Написать письмо", "Откроется почтовое приложение с заполненным адресом получателя.", "Руководство для начала", "Справочник API", "Документация", "Технические документы"],
  ar: ["تواصل معنا", "لنتحدث عن فكرتك القادمة.", "هل لديك فكرة أو سؤال أو شيء ترغب في مشاركته؟ انضم إلى مجتمع YNX أو راسل المؤسس مباشرة.", "تحدث مع المؤسس", "راسلنا بأسئلتك وملاحظاتك ومقترحات التعاون عبر البريد الإلكتروني.", "اكتب رسالة بريد", "سيفتح تطبيق البريد الإلكتروني مع إدراج عنوان المستلم.", "دليل البداية", "مرجع API", "الوثائق", "الأوراق البيضاء"],
  id: ["Hubungi kami", "Mari bahas ide Anda berikutnya.", "Punya ide, pertanyaan, atau hal untuk dibagikan? Bergabunglah dengan komunitas YNX atau kirim email langsung kepada pendiri.", "Bicara dengan pendiri", "Kirim pertanyaan proyek, masukan, dan usulan kolaborasi melalui email.", "Tulis email", "Aplikasi email Anda akan terbuka dengan penerima yang sudah diisi.", "Panduan memulai", "Referensi API", "Dokumentasi", "Whitepaper"],
};
export function getContactCopy(locale) {
  const keys = ["nav", "title", "lead", "founder", "emailLead", "emailAction", "emailHint", "manual", "api", "docs", "whitepaper"];
  return Object.fromEntries(keys.map((key, i) => [key, (copy[locale] || copy.en)[i]]));
}
