// Canonical public content for the 6423 website. Keep commands and network
// identifiers literal; surrounding guidance is localized below.
export const CORE_LOCALES = ["en", "zh-CN", "zh-TW", "ja", "ko", "es", "fr", "de", "pt", "ru", "ar", "id"];

const portal = (eyebrow, title, lead, facts, actions) => ({ eyebrow, title, lead, facts, actions });

export const PORTAL_COPY = {
  en: {
    home: portal("Public Testnet", "Auditable Web4 execution for people, apps, and AI agents.", "YNX is an EVM-compatible Layer-1 Testnet. YNXT pays testnet gas and fees; Mainnet and market value are not claimed.", ["Native chain ID: 6423", "EVM chain ID: 0x1917", "Native test asset: YNXT"], ["Open Explorer", "Get Testnet YNXT", "Add 6423 to wallet"]),
    "/blockchain": portal("Network overview", "Explore YNX 6423 through the official path.", "The website summarizes verified Testnet state; detailed blocks, transactions, addresses, contracts and validators live in Explorer.", ["RPC and Indexer height are checked together.", "A new Testnet may have a low height; retired history is not imported.", "Disagreement is shown as degraded, never normal."], ["Open YNX Explorer", "Open Network Monitor"]),
    "/tokens": portal("Native asset", "YNXT is visible, testnet-only and verifiable.", "YNXT pays gas, fees and network resources. Price, market cap and supply stay unavailable without a public authority.", ["Native asset: YNXT", "Network: YNX Testnet", "Market data: no verified public source"], ["View YNXT in Explorer", "Get Testnet YNXT"]),
    "/data": portal("Data center", "Verified data includes its boundary.", "Live figures appear only after chain identity and Indexer alignment succeed; no synthetic history is generated.", ["Short live windows are not historical charts.", "Each current value carries source and refresh time.", "RPC, Explorer, Faucet and Monitor are checked separately."], ["Open Network Monitor", "Open Explorer data"]),
    "/governance": portal("Governance", "Governance data is never inferred.", "There is no verified public governance index for 6423 yet, so proposals, votes and parameters remain unavailable.", ["No verified proposal endpoint is configured.", "Sample votes are never shown as current facts.", "Documentation and source remain available."], ["Open governance source", "Read Docs"]),
    "/ecosystem": portal("YNX Ecosystem", "Choose a product by the job you need to do.", "Wallet, DeFi, Payments, Developer, AI, Social, Data, Media, Commerce and Infrastructure keep independent status labels.", ["Source code does not prove public deployment.", "Testnet, Preview and Unavailable stay visible.", "YNX Wallet and MetaMask compatibility remain distinct."], ["Open ecosystem directory", "Check product status"]),
    "/developers": portal("Developer portal", "Build against one canonical Testnet identity.", "RPC, EVM, Explorer and Faucet are separate verified services; wallet connection, signing and sending never start automatically.", ["Cosmos: ynx_6423-1", "EVM: 6423 / 0x1917", "Native asset: YNXT"], ["Read Developer Docs", "Open Chain GitHub"]),
    "/downloads": portal("Download center", "Install only verified releases.", "Platform, version, checksum and signing state must be explicit; candidates and unsigned builds are never presented as production.", ["Wallet and tools are separate products.", "Every enabled link must resolve to a real artifact.", "Read installation notes before replacement or import."], ["Open verified downloads", "Read installation manual"]),
    "/more": portal("Project resources", "Every resource has a clear destination.", "Whitepaper, documentation, source, monitoring and official community channels are gathered here with external destinations marked.", ["Official website: ynxweb4.com", "Testnet only; no Mainnet claim", "Never share a recovery phrase, private key or password."], ["Read whitepaper", "Open GitHub", "Join Discord"]),
  },
  "zh-CN": {
    home: portal("公开测试网", "让人、应用与 AI Agent 在可审计边界内执行 Web4。", "YNX 是兼容 EVM 的 Layer-1 测试网。YNXT 用于测试网 Gas 与手续费；本站不宣称主网或市场价值。", ["原生链 ID：6423", "EVM 链 ID：0x1917", "原生测试资产：YNXT"], ["打开 Explorer", "领取测试 YNXT", "将 6423 添加到钱包"]),
    "/blockchain": portal("网络概览", "沿官方入口了解 YNX 6423。", "官网汇总已经核验的测试网状态；区块、交易、地址、合约和验证者详情在 Explorer 查询。", ["RPC 与 Indexer 高度同时核验。", "新测试网高度较低属正常，不导入退役链历史。", "不一致时明确显示降级，不伪装正常。"], ["打开 YNX Explorer", "打开网络监控"]),
    "/tokens": portal("原生资产", "YNXT 清晰可见，仅用于测试网并可核验。", "YNXT 用于 Gas、手续费和网络资源；没有权威公开来源时不显示价格、市值或供应量。", ["原生资产：YNXT", "网络：YNX 测试网", "市场数据：暂无已核验公开来源"], ["在 Explorer 查看 YNXT", "领取测试 YNXT"]),
    "/data": portal("数据中心", "可验证数据必须说明边界。", "只有链身份与 Indexer 对齐后才显示实时数值，也不会生成虚假历史图。", ["短时实时窗口不等于历史图表。", "每个数值都带来源和刷新时间。", "RPC、Explorer、Faucet 与 Monitor 分别核验。"], ["打开网络监控", "打开 Explorer 数据"]),
    "/governance": portal("治理", "治理数据不会凭空推断。", "6423 暂无已核验公开治理索引，因此提案、投票和参数会保持不可用。", ["尚未配置已核验提案接口。", "不会把样例投票当作当前事实。", "文档与源码仍可查阅。"], ["打开治理源码", "阅读文档"]),
    "/ecosystem": portal("YNX 生态", "按要完成的任务选择产品。", "钱包、DeFi、支付、开发者、AI、社交、数据、媒体、商业和基础设施都独立标注状态。", ["有源码不代表已公网部署。", "Testnet、Preview 与 Unavailable 标签始终可见。", "YNX Wallet 与 MetaMask 兼容性明确区分。"], ["打开生态目录", "检查产品状态"]),
    "/developers": portal("开发者中心", "围绕唯一的测试网身份构建。", "RPC、EVM、Explorer 与 Faucet 分别核验；连接钱包、签名和发送绝不会自动触发。", ["Cosmos：ynx_6423-1", "EVM：6423 / 0x1917", "原生资产：YNXT"], ["阅读开发者文档", "打开 Chain GitHub"]),
    "/downloads": portal("下载中心", "只安装能够核验的发布。", "平台、版本、校验和与签名状态必须明确；候选和未签名构建不得冒充正式版。", ["钱包与工具是独立产品。", "每个启用链接都必须指向真实工件。", "替换或导入前先阅读安装说明。"], ["打开已核验下载", "阅读安装手册"]),
    "/more": portal("项目资源", "每一项资源都有明确去向。", "白皮书、文档、源码、监控与官方社区集中展示，外部目的地会明确标注。", ["官方网站：ynxweb4.com", "仅为测试网，不宣称主网", "绝不分享助记词、私钥或密码。"], ["阅读白皮书", "打开 GitHub", "加入 Discord"]),
  },
  "zh-TW": {
    home: portal("公開測試網", "讓人、應用與 AI Agent 在可稽核邊界內執行 Web4。", "YNX 是相容 EVM 的 Layer-1 測試網。YNXT 用於測試網 Gas 與手續費；本站不宣稱主網或市場價值。", ["原生鏈 ID：6423", "EVM 鏈 ID：0x1917", "原生測試資產：YNXT"], ["開啟 Explorer", "領取測試 YNXT", "將 6423 加入錢包"]),
    "/blockchain": portal("網路概覽", "沿官方入口了解 YNX 6423。", "官網彙整已核驗的測試網狀態；區塊、交易、地址、合約與驗證者詳情在 Explorer 查詢。", ["RPC 與 Indexer 高度同時核驗。", "新測試網高度較低屬正常，不匯入退役鏈歷史。", "不一致時明確顯示降級。"], ["開啟 YNX Explorer", "開啟網路監控"]),
    "/tokens": portal("原生資產", "YNXT 清楚可見，僅供測試網並可核驗。", "YNXT 用於 Gas、手續費與網路資源；沒有權威來源時不顯示價格、市值或供應量。", ["原生資產：YNXT", "網路：YNX 測試網", "市場資料：暫無已核驗來源"], ["在 Explorer 查看 YNXT", "領取測試 YNXT"]),
    "/data": portal("資料中心", "可驗證資料必須說明邊界。", "只有鏈身分與 Indexer 對齊後才顯示即時數值，也不會產生虛構歷史圖。", ["短時視窗不等於歷史圖表。", "每個數值都有來源與更新時間。", "各公開服務分別核驗。"], ["開啟網路監控", "開啟 Explorer 資料"]),
    "/governance": portal("治理", "治理資料不會憑空推斷。", "6423 尚無已核驗公開治理索引，因此提案、投票與參數保持不可用。", ["尚未配置已核驗提案端點。", "不把範例投票當成目前事實。", "文件與原始碼仍可查閱。"], ["開啟治理原始碼", "閱讀文件"]),
    "/ecosystem": portal("YNX 生態", "依照要完成的工作選擇產品。", "錢包、DeFi、支付、開發者、AI、社交、資料、媒體、商業與基礎設施皆獨立標示狀態。", ["有原始碼不等於已公開部署。", "Testnet、Preview 與 Unavailable 標籤保持可見。", "YNX Wallet 與 MetaMask 相容性分開說明。"], ["開啟生態目錄", "檢查產品狀態"]),
    "/developers": portal("開發者中心", "針對唯一測試網身分建置。", "RPC、EVM、Explorer 與 Faucet 分別核驗；連接錢包、簽名與傳送不會自動觸發。", ["Cosmos：ynx_6423-1", "EVM：6423 / 0x1917", "原生資產：YNXT"], ["閱讀開發者文件", "開啟 Chain GitHub"]),
    "/downloads": portal("下載中心", "只安裝可核驗的發布。", "平台、版本、校驗碼與簽署狀態必須明確；候選與未簽署構建不得冒充正式版。", ["錢包與工具是獨立產品。", "每個啟用連結都必須指向真實工件。", "替換或匯入前先閱讀安裝說明。"], ["開啟已核驗下載", "閱讀安裝手冊"]),
    "/more": portal("專案資源", "每項資源都有清楚去向。", "白皮書、文件、原始碼、監控與官方社群集中呈現，外部目的地會明確標示。", ["官方網站：ynxweb4.com", "僅為測試網，不宣稱主網", "絕不分享助記詞、私鑰或密碼。"], ["閱讀白皮書", "開啟 GitHub", "加入 Discord"]),
  },
};

const routeNames = {
  ja: ["ネットワーク概要", "ネイティブ資産", "データセンター", "ガバナンス", "YNX エコシステム", "開発者ポータル", "ダウンロード", "プロジェクト資料"],
  ko: ["네트워크 개요", "네이티브 자산", "데이터 센터", "거버넌스", "YNX 생태계", "개발자 포털", "다운로드", "프로젝트 자료"],
  es: ["Resumen de red", "Activo nativo", "Centro de datos", "Gobernanza", "Ecosistema YNX", "Portal de desarrollo", "Descargas", "Recursos del proyecto"],
  fr: ["Vue du réseau", "Actif natif", "Centre de données", "Gouvernance", "Écosystème YNX", "Portail développeur", "Téléchargements", "Ressources du projet"],
  de: ["Netzwerkübersicht", "Native Anlage", "Datenzentrum", "Governance", "YNX-Ökosystem", "Entwicklerportal", "Downloads", "Projektressourcen"],
  pt: ["Visão da rede", "Ativo nativo", "Centro de dados", "Governança", "Ecossistema YNX", "Portal de desenvolvimento", "Downloads", "Recursos do projeto"],
  ru: ["Обзор сети", "Нативный актив", "Центр данных", "Управление", "Экосистема YNX", "Портал разработчика", "Загрузки", "Ресурсы проекта"],
  ar: ["نظرة عامة على الشبكة", "الأصل الأصلي", "مركز البيانات", "الحوكمة", "منظومة YNX", "بوابة المطورين", "التنزيلات", "موارد المشروع"],
  id: ["Ringkasan jaringan", "Aset native", "Pusat data", "Tata kelola", "Ekosistem YNX", "Portal pengembang", "Unduhan", "Sumber daya proyek"],
};

const commonLocalized = {
  ja: { home: ["公開テストネット", "監査可能な境界で人・アプリ・AI Agent が Web4 を実行。", "YNX は EVM 互換 Layer-1 テストネットです。YNXT はテスト用 Gas と手数料に使われ、Mainnet や市場価値を主張しません。", "エクスプローラーを開く", "テスト YNXT を取得", "6423 をウォレットへ追加"], titles: ["公式経路で YNX 6423 を確認。", "YNXT はテストネット専用で検証可能。", "検証済みデータには境界がある。", "ガバナンス情報を推測しない。", "目的に合う製品を選ぶ。", "唯一のテストネット識別子で構築。", "検証済みリリースだけを導入。", "すべての資料に明確な行き先。"], lead: "6423 / 0x1917 / YNXT の公開事実だけを表示し、未検証の状態は利用不可または低下として明示します。", facts: ["ソースだけでは公開運用を証明しません。", "未検証の数値や市場情報を生成しません。", "秘密鍵やリカバリーフレーズを共有しないでください。"], actions: ["詳細を開く", "状態を確認", "ドキュメントを読む"] },
  ko: { home: ["공개 테스트넷", "사람·앱·AI Agent를 위한 감사 가능한 Web4 실행.", "YNX는 EVM 호환 Layer-1 테스트넷입니다. YNXT는 테스트 Gas와 수수료에만 사용되며 Mainnet이나 시장 가치를 주장하지 않습니다.", "Explorer 열기", "테스트 YNXT 받기", "지갑에 6423 추가"], titles: ["공식 경로에서 YNX 6423 탐색.", "YNXT는 테스트넷 전용이며 검증 가능.", "검증된 데이터에는 경계가 있습니다.", "거버넌스 데이터를 추정하지 않습니다.", "할 일에 맞는 제품 선택.", "하나의 테스트넷 정체성으로 개발.", "검증된 릴리스만 설치.", "모든 자료에 명확한 목적지."], lead: "6423 / 0x1917 / YNXT의 공개 검증 사실만 표시하며 확인되지 않은 상태는 사용 불가 또는 저하로 표시합니다.", facts: ["소스 코드만으로 공개 배포를 증명하지 않습니다.", "검증되지 않은 수치나 시장 데이터를 만들지 않습니다.", "개인 키나 복구 문구를 공유하지 마십시오."], actions: ["세부 정보 열기", "상태 확인", "문서 읽기"] },
  es: { home: ["Testnet pública", "Ejecución Web4 auditable para personas, aplicaciones y agentes de IA.", "YNX es una Layer-1 compatible con EVM en fase Testnet. YNXT sirve para gas y comisiones de prueba; no se afirma Mainnet ni valor de mercado.", "Abrir Explorer", "Obtener YNXT de prueba", "Añadir 6423 al monedero"], titles: ["Explora YNX 6423 por la ruta oficial.", "YNXT es de prueba y verificable.", "Los datos verificados declaran sus límites.", "La gobernanza no se deduce.", "Elige un producto según tu tarea.", "Desarrolla contra una sola identidad Testnet.", "Instala solo versiones verificadas.", "Cada recurso tiene un destino claro."], lead: "Solo se muestran hechos públicos verificados de 6423 / 0x1917 / YNXT; lo no comprobado figura como no disponible o degradado.", facts: ["El código fuente no prueba un despliegue público.", "No se inventan cifras ni datos de mercado.", "Nunca compartas claves privadas ni frases de recuperación."], actions: ["Abrir detalles", "Comprobar estado", "Leer documentación"] },
  fr: { home: ["Testnet publique", "Exécution Web4 auditable pour les personnes, applications et agents IA.", "YNX est une Layer-1 compatible EVM en Testnet. YNXT sert au gas et aux frais de test ; aucun Mainnet ni valeur de marché n'est revendiqué.", "Ouvrir Explorer", "Obtenir du YNXT de test", "Ajouter 6423 au portefeuille"], titles: ["Explorer YNX 6423 par la voie officielle.", "YNXT est réservé au Testnet et vérifiable.", "Les données vérifiées indiquent leurs limites.", "La gouvernance n'est jamais déduite.", "Choisir un produit selon le besoin.", "Développer avec une identité Testnet unique.", "Installer uniquement des versions vérifiées.", "Chaque ressource a une destination claire."], lead: "Seuls les faits publics vérifiés 6423 / 0x1917 / YNXT sont affichés ; l'incertain reste indisponible ou dégradé.", facts: ["Le code source ne prouve pas un déploiement public.", "Aucune donnée de marché non vérifiée n'est inventée.", "Ne partagez jamais clé privée ni phrase de récupération."], actions: ["Ouvrir les détails", "Vérifier l'état", "Lire la documentation"] },
  de: { home: ["Öffentliches Testnet", "Prüfbare Web4-Ausführung für Menschen, Apps und KI-Agenten.", "YNX ist ein EVM-kompatibles Layer-1-Testnet. YNXT dient Test-Gas und Gebühren; Mainnet oder Marktwert werden nicht behauptet.", "Explorer öffnen", "Test-Y​​NXT erhalten", "6423 zur Wallet hinzufügen"], titles: ["YNX 6423 über den offiziellen Pfad erkunden.", "YNXT ist testnet-spezifisch und prüfbar.", "Geprüfte Daten nennen ihre Grenzen.", "Governance wird nicht abgeleitet.", "Produkt nach Aufgabe auswählen.", "Gegen eine kanonische Testnet-Identität bauen.", "Nur geprüfte Releases installieren.", "Jede Ressource hat ein klares Ziel."], lead: "Es erscheinen nur geprüfte öffentliche Fakten zu 6423 / 0x1917 / YNXT; Ungeprüftes bleibt nicht verfügbar oder degradiert.", facts: ["Quellcode beweist keine öffentliche Bereitstellung.", "Ungeprüfte Zahlen oder Marktdaten werden nicht erfunden.", "Private Schlüssel und Wiederherstellungsphrasen niemals teilen."], actions: ["Details öffnen", "Status prüfen", "Dokumentation lesen"] },
  pt: { home: ["Testnet pública", "Execução Web4 auditável para pessoas, apps e agentes de IA.", "YNX é uma Layer-1 compatível com EVM em Testnet. YNXT serve para gas e taxas de teste; não há alegação de Mainnet ou valor de mercado.", "Abrir Explorer", "Obter YNXT de teste", "Adicionar 6423 à carteira"], titles: ["Explore YNX 6423 pelo caminho oficial.", "YNXT é exclusivo da Testnet e verificável.", "Dados verificados declaram seus limites.", "Governança não é inferida.", "Escolha o produto pela tarefa.", "Desenvolva com uma identidade Testnet canônica.", "Instale apenas versões verificadas.", "Cada recurso tem destino claro."], lead: "Somente fatos públicos verificados de 6423 / 0x1917 / YNXT são exibidos; o não comprovado fica indisponível ou degradado.", facts: ["Código-fonte não prova implantação pública.", "Números ou dados de mercado não verificados não são inventados.", "Nunca compartilhe chave privada ou frase de recuperação."], actions: ["Abrir detalhes", "Verificar status", "Ler documentação"] },
  ru: { home: ["Публичная тестовая сеть", "Проверяемое выполнение Web4 для людей, приложений и ИИ-агентов.", "YNX — совместимая с EVM тестовая Layer-1. YNXT используется для тестового газа и комиссий; Mainnet и рыночная стоимость не заявлены.", "Открыть Explorer", "Получить тестовый YNXT", "Добавить 6423 в кошелёк"], titles: ["Исследуйте YNX 6423 через официальный путь.", "YNXT предназначен для Testnet и проверяем.", "Проверенные данные сообщают границы.", "Данные управления не предполагаются.", "Выберите продукт по задаче.", "Разрабатывайте для одной идентичности Testnet.", "Устанавливайте только проверенные выпуски.", "У каждого ресурса ясное назначение."], lead: "Показываются только проверенные публичные факты 6423 / 0x1917 / YNXT; неподтверждённое остаётся недоступным или деградированным.", facts: ["Исходный код не доказывает публичное развёртывание.", "Непроверенные числа и рыночные данные не выдумываются.", "Никогда не передавайте закрытый ключ или фразу восстановления."], actions: ["Открыть детали", "Проверить статус", "Читать документацию"] },
  ar: { home: ["شبكة اختبار عامة", "تنفيذ Web4 قابل للتدقيق للأشخاص والتطبيقات ووكلاء الذكاء الاصطناعي.", "YNX شبكة Layer-1 متوافقة مع EVM في مرحلة الاختبار. تُستخدم YNXT للغاز والرسوم الاختبارية؛ ولا ندّعي وجود Mainnet أو قيمة سوقية.", "فتح Explorer", "الحصول على YNXT اختباري", "إضافة 6423 إلى المحفظة"], titles: ["استكشف YNX 6423 عبر المسار الرسمي.", "YNXT أصل اختباري قابل للتحقق.", "البيانات المتحققة توضّح حدودها.", "لا نستنتج بيانات الحوكمة.", "اختر المنتج حسب المهمة.", "طوّر لهوية Testnet واحدة.", "ثبّت الإصدارات المتحققة فقط.", "لكل مورد وجهة واضحة."], lead: "نعرض الحقائق العامة المتحققة فقط عن 6423 / 0x1917 / YNXT؛ وما لم يُثبت يبقى غير متاح أو متدهورًا.", facts: ["الشيفرة المصدرية لا تثبت النشر العام.", "لا ننشئ أرقامًا أو بيانات سوق غير متحققة.", "لا تشارك المفتاح الخاص أو عبارة الاسترداد أبدًا."], actions: ["فتح التفاصيل", "فحص الحالة", "قراءة الوثائق"] },
  id: { home: ["Testnet publik", "Eksekusi Web4 yang dapat diaudit untuk manusia, aplikasi, dan agen AI.", "YNX adalah Layer-1 kompatibel EVM dalam Testnet. YNXT dipakai untuk gas dan biaya uji; tidak ada klaim Mainnet atau nilai pasar.", "Buka Explorer", "Dapatkan YNXT uji", "Tambahkan 6423 ke dompet"], titles: ["Jelajahi YNX 6423 melalui jalur resmi.", "YNXT khusus Testnet dan dapat diverifikasi.", "Data terverifikasi menjelaskan batasnya.", "Data tata kelola tidak diterka.", "Pilih produk sesuai pekerjaan.", "Bangun pada satu identitas Testnet.", "Pasang hanya rilis terverifikasi.", "Setiap sumber daya punya tujuan jelas."], lead: "Hanya fakta publik terverifikasi 6423 / 0x1917 / YNXT yang ditampilkan; yang belum terbukti tetap tidak tersedia atau terdegradasi.", facts: ["Kode sumber tidak membuktikan penerapan publik.", "Angka atau data pasar yang belum terverifikasi tidak dibuat-buat.", "Jangan pernah bagikan kunci privat atau frasa pemulihan."], actions: ["Buka detail", "Periksa status", "Baca dokumentasi"] },
};

const routeOrder = ["/blockchain", "/tokens", "/data", "/governance", "/ecosystem", "/developers", "/downloads", "/more"];
for (const [locale, copy] of Object.entries(commonLocalized)) {
  PORTAL_COPY[locale] = {
    home: portal(copy.home[0], copy.home[1], copy.home[2], ["6423", "0x1917", "YNXT"], copy.home.slice(3)),
  };
  routeOrder.forEach((route, index) => {
    PORTAL_COPY[locale][route] = portal(routeNames[locale][index], copy.titles[index], copy.lead, [...copy.facts], [...copy.actions]);
  });
}

const chapterIds = ["network", "wallet", "ynxt", "explorer", "observer", "validator", "backup", "recovery", "mining", "bridge"];
const manual = (hero, actions, facts, platform, chapters, recovery, warning) => ({ hero, actions, facts, platform, chapters, recovery, warning });
const chaptersFrom = (rows, warning) => Object.fromEntries(chapterIds.map((id, index) => [id, { title: rows[index][0], lead: rows[index][1], steps: rows[index].slice(2), warning }]));

const manualRaw = {
  en: {
    hero: ["User and operator manual", "Operate YNX Testnet with evidence at every step.", "A practical guide to accounts, 6423, YNXT, Explorer, observers, validator candidacy, backup and recovery."], actions: ["Check network status", "Read developer docs"],
    platform: ["Cross-platform quickstart", "Follow each step or run one read-only network check first.", "Verify the artifact checksum before opening it.", "Review 6423 / 0x1917 / YNXT before approving a wallet prompt.", "Use Faucet only for test assets and verify the hash in Explorer.", "Keep wallet and signer recovery material offline."],
    warning: "Never disclose a mnemonic, private key, password, one-time code or signer secret. Stop when network identity or signer state is uncertain.",
    rows: [["Verify 6423", "Confirm the canonical Testnet identity.", "Check RPC and Indexer height.", "Stop if the wallet reports any other chain ID."], ["Protect a wallet", "Public addresses and secret signing material have different boundaries.", "Create or import only in the intended wallet.", "Review network, recipient, amount, fee and nonce before signing."], ["Use YNXT", "YNXT is a Testnet gas, fee and resource asset.", "Get test assets only from Faucet.", "Preserve and verify each resulting transaction hash."], ["Use Explorer", "Explorer is the read-only proof surface.", "Search the exact block, hash or address.", "Compare indexed and canonical height before concluding data is absent."], ["Run an observer", "Start a non-signing node with least privilege.", "Use a dedicated Linux identity and persistent storage.", "Compare synchronized height and hash with public RPC."], ["Apply as validator", "Validator admission is reviewed, not automatic.", "Prove monitoring, custody and restore readiness.", "Do not enable signing before explicit admission."], ["Back up safely", "Back up configuration separately from secrets and chain data.", "Keep recovery material offline.", "Rehearse restore on an isolated host."], ["Recover deliberately", "Uncertainty is a state, not a reason to guess.", "Preserve evidence and the last confirmed state.", "Check hash and nonce before any retry."], ["No mining", "YNX Testnet is validator-based, not proof-of-work mining.", "Do not install GPU or ASIC miners.", "Do not trust guaranteed reward claims."], ["Bridge evidence", "Local coordinator finality is not external-chain completion.", "Verify the source transaction and confirmations.", "Report external submission as unavailable until directly proved."]],
    recovery: ["Preserve the request or hash before retrying.", "Confirm 6423 / 0x1917 and the latest aligned height.", "Never solve an incident by sharing custody material."],
  },
  "zh-CN": { hero: ["用户与运维手册", "每一步都用证据运行 YNX 测试网。", "覆盖账户、6423、YNXT、Explorer、观察节点、验证者候选、备份与恢复的实用指南。"], actions: ["检查网络状态", "阅读开发者文档"], platform: ["跨平台快速开始", "逐步操作，或先运行一条只读网络检查。", "打开文件前核对工件校验和。", "批准钱包提示前核对 6423 / 0x1917 / YNXT。", "只从 Faucet 领取测试资产，并在 Explorer 验证哈希。", "钱包与签名器恢复材料保持离线。"], warning: "绝不泄露助记词、私钥、密码、一次性验证码或签名器秘密。网络身份或签名器状态不确定时立即停止。", rows: [["核验 6423", "确认唯一的测试网身份。", "对比 RPC 与 Indexer 高度。", "钱包显示其他链 ID 时立即停止。"], ["保护钱包", "公开地址与秘密签名材料必须分隔。", "只在目标钱包创建或导入账户。", "签名前核对网络、收款人、金额、费用与 nonce。"], ["使用 YNXT", "YNXT 是测试网 Gas、手续费与资源资产。", "只从 Faucet 领取测试资产。", "保存并核验每个交易哈希。"], ["使用 Explorer", "Explorer 是只读证明界面。", "搜索精确区块、哈希或地址。", "断言数据缺失前比较索引与规范高度。"], ["运行观察节点", "以最小权限启动不签名节点。", "使用专用 Linux 账户与持久存储。", "与公共 RPC 比较同步高度和哈希。"], ["申请验证者", "验证者准入需要审核，不会自动完成。", "证明监控、保管与恢复就绪。", "明确准入前不得启用签名。"], ["安全备份", "配置、秘密与链数据分开备份。", "恢复材料保持离线。", "在隔离主机演练恢复。"], ["谨慎恢复", "不确定本身就是状态，不能靠猜测。", "保存证据与最后确认状态。", "重试前核对哈希和 nonce。"], ["不要挖矿", "YNX 测试网使用验证者，不是 PoW。", "不要安装 GPU 或 ASIC 矿工。", "不要相信保证收益的宣传。"], ["跨链证据", "本地协调器最终完成不等于外部链完成。", "核对源交易与确认数。", "外部提交未直接证明前必须显示不可用。"]], recovery: ["重试前保存请求或哈希。", "确认 6423 / 0x1917 与最新对齐高度。", "绝不通过分享保管材料处理事故。"] },
};

const translatedManual = {
  "zh-TW": ["使用者與運維手冊", "每一步都用證據操作 YNX 測試網。", "涵蓋帳戶、6423、YNXT、Explorer、觀察節點、驗證者候選、備份與恢復。", "絕不透露助記詞、私鑰、密碼、一次性驗證碼或簽名器秘密。"],
  ja: ["ユーザー・運用マニュアル", "すべての手順を証拠で確認して YNX Testnet を運用。", "アカウント、6423、YNXT、Explorer、オブザーバー、バリデータ候補、バックアップと復旧を説明します。", "ニーモニック、秘密鍵、パスワード、ワンタイムコード、署名者の秘密を決して開示しないでください。"],
  ko: ["사용자 및 운영자 설명서", "모든 단계에서 증거로 YNX Testnet을 운영하세요.", "계정, 6423, YNXT, Explorer, 관찰 노드, 검증자 후보, 백업과 복구를 안내합니다.", "니모닉, 개인 키, 비밀번호, 일회용 코드 또는 서명자 비밀을 절대 공개하지 마십시오."],
  es: ["Manual de usuario y operación", "Opera YNX Testnet con evidencia en cada paso.", "Guía de cuentas, 6423, YNXT, Explorer, observadores, candidatura de validadores, copias y recuperación.", "Nunca reveles frase mnemónica, clave privada, contraseña, código de un solo uso ni secreto de firma."],
  fr: ["Manuel utilisateur et opérateur", "Exploitez YNX Testnet avec une preuve à chaque étape.", "Guide des comptes, 6423, YNXT, Explorer, observateurs, candidats validateurs, sauvegarde et reprise.", "Ne divulguez jamais phrase mnémonique, clé privée, mot de passe, code unique ni secret de signature."],
  de: ["Benutzer- und Betriebshandbuch", "YNX Testnet in jedem Schritt mit Nachweisen betreiben.", "Leitfaden zu Konten, 6423, YNXT, Explorer, Observern, Validator-Kandidatur, Sicherung und Wiederherstellung.", "Mnemonic, privaten Schlüssel, Passwort, Einmalcode oder Signierer-Geheimnis niemals offenlegen."],
  pt: ["Manual de usuário e operação", "Opere a YNX Testnet com evidência em cada etapa.", "Guia de contas, 6423, YNXT, Explorer, observadores, candidatura de validadores, backup e recuperação.", "Nunca revele mnemônico, chave privada, senha, código único ou segredo do assinante."],
  ru: ["Руководство пользователя и оператора", "Работайте с YNX Testnet, подтверждая каждый шаг.", "Руководство по аккаунтам, 6423, YNXT, Explorer, наблюдателям, кандидатам валидаторов, резервированию и восстановлению.", "Никогда не раскрывайте мнемонику, закрытый ключ, пароль, одноразовый код или секрет подписанта."],
  ar: ["دليل المستخدم والمشغّل", "شغّل YNX Testnet مع دليل قابل للتحقق في كل خطوة.", "دليل للحسابات و6423 وYNXT وExplorer وعُقد المراقبة وترشيح المدققين والنسخ الاحتياطي والاسترداد.", "لا تكشف أبدًا عبارة الاسترداد أو المفتاح الخاص أو كلمة المرور أو الرمز المؤقت أو سرّ الموقّع."],
  id: ["Panduan pengguna dan operator", "Operasikan YNX Testnet dengan bukti pada setiap langkah.", "Panduan akun, 6423, YNXT, Explorer, observer, calon validator, cadangan, dan pemulihan.", "Jangan pernah ungkapkan mnemonik, kunci privat, kata sandi, kode sekali pakai, atau rahasia penanda tangan."],
};

const domainTranslations = {
  "zh-TW": [["核驗 6423", "確認唯一測試網身分。"], ["保護錢包", "分隔公開地址與簽名秘密。"], ["使用 YNXT", "YNXT 只供測試網 Gas 與費用。"], ["使用 Explorer", "用只讀證據核對結果。"], ["運行觀察節點", "以最小權限啟動不簽名節點。"], ["申請驗證者", "驗證者准入需要人工審核。"], ["安全備份", "配置、秘密與鏈資料分開備份。"], ["謹慎恢復", "先保存證據再重試。"], ["不要挖礦", "YNX 測試網不是 PoW。"], ["跨鏈證據", "本地完成不等於外部鏈完成。"]],
  ja: [["6423 を検証", "唯一の Testnet 識別子を確認。"], ["ウォレットを保護", "公開アドレスと署名秘密を分離。"], ["YNXT を使用", "YNXT は Testnet の Gas と手数料用。"], ["Explorer を使用", "読み取り専用証拠で結果を確認。"], ["オブザーバー運用", "最小権限で非署名ノードを開始。"], ["バリデータ申請", "参加には人による審査が必要。"], ["安全なバックアップ", "設定・秘密・チェーンデータを分離。"], ["慎重な復旧", "再試行前に証拠を保存。"], ["マイニング禁止", "YNX Testnet は PoW ではありません。"], ["ブリッジ証拠", "ローカル完了は外部チェーン完了ではありません。"]],
  ko: [["6423 검증", "유일한 Testnet 정체성을 확인합니다."], ["지갑 보호", "공개 주소와 서명 비밀을 분리합니다."], ["YNXT 사용", "YNXT는 Testnet Gas와 수수료용입니다."], ["Explorer 사용", "읽기 전용 증거로 결과를 확인합니다."], ["관찰 노드 운영", "최소 권한 비서명 노드를 시작합니다."], ["검증자 신청", "참여에는 사람의 검토가 필요합니다."], ["안전한 백업", "설정·비밀·체인 데이터를 분리합니다."], ["신중한 복구", "재시도 전에 증거를 보존합니다."], ["채굴 금지", "YNX Testnet은 PoW가 아닙니다."], ["브리지 증거", "로컬 완료는 외부 체인 완료가 아닙니다."]],
  es: [["Verificar 6423", "Confirma la identidad Testnet canónica."], ["Proteger el monedero", "Separa direcciones públicas y secretos de firma."], ["Usar YNXT", "YNXT sirve para gas y comisiones de Testnet."], ["Usar Explorer", "Comprueba resultados con evidencia de solo lectura."], ["Operar un observador", "Inicia un nodo sin firma y con mínimo privilegio."], ["Solicitar ser validador", "La admisión requiere revisión humana."], ["Copia segura", "Separa configuración, secretos y datos de cadena."], ["Recuperación prudente", "Conserva evidencia antes de reintentar."], ["Sin minería", "YNX Testnet no usa PoW."], ["Evidencia de puente", "Finalidad local no equivale a ejecución externa."]],
  fr: [["Vérifier 6423", "Confirmez l'identité Testnet canonique."], ["Protéger le portefeuille", "Séparez adresses publiques et secrets de signature."], ["Utiliser YNXT", "YNXT sert au gas et aux frais du Testnet."], ["Utiliser Explorer", "Vérifiez avec des preuves en lecture seule."], ["Exploiter un observateur", "Démarrez un nœud non signataire à privilège minimal."], ["Candidater validateur", "L'admission exige une revue humaine."], ["Sauvegarder sûrement", "Séparez configuration, secrets et données de chaîne."], ["Reprendre prudemment", "Conservez les preuves avant toute nouvelle tentative."], ["Pas de minage", "YNX Testnet n'utilise pas PoW."], ["Preuve de pont", "La finalité locale ne prouve pas l'exécution externe."]],
  de: [["6423 prüfen", "Kanonische Testnet-Identität bestätigen."], ["Wallet schützen", "Öffentliche Adressen und Signiergeheimnisse trennen."], ["YNXT verwenden", "YNXT dient Testnet-Gas und Gebühren."], ["Explorer verwenden", "Ergebnisse mit Nur-Lese-Nachweisen prüfen."], ["Observer betreiben", "Nicht signierenden Knoten mit Minimalrechten starten."], ["Validator beantragen", "Zulassung erfordert menschliche Prüfung."], ["Sicher sichern", "Konfiguration, Geheimnisse und Kettendaten trennen."], ["Bedacht wiederherstellen", "Vor Wiederholung Nachweise sichern."], ["Kein Mining", "YNX Testnet verwendet kein PoW."], ["Bridge-Nachweis", "Lokale Finalität ist keine externe Ausführung."]],
  pt: [["Verificar 6423", "Confirme a identidade canônica da Testnet."], ["Proteger a carteira", "Separe endereços públicos e segredos de assinatura."], ["Usar YNXT", "YNXT serve para gas e taxas da Testnet."], ["Usar Explorer", "Confira resultados com evidência somente leitura."], ["Operar observador", "Inicie nó sem assinatura e com privilégio mínimo."], ["Candidatar validador", "A admissão exige revisão humana."], ["Backup seguro", "Separe configuração, segredos e dados da cadeia."], ["Recuperar com cuidado", "Preserve evidências antes de tentar novamente."], ["Sem mineração", "YNX Testnet não usa PoW."], ["Evidência da ponte", "Finalidade local não prova execução externa."]],
  ru: [["Проверить 6423", "Подтвердите каноническую идентичность Testnet."], ["Защитить кошелёк", "Разделяйте публичные адреса и секреты подписи."], ["Использовать YNXT", "YNXT нужен для газа и комиссий Testnet."], ["Использовать Explorer", "Проверяйте результат по данным только для чтения."], ["Запустить наблюдатель", "Запускайте неподписывающий узел с минимумом прав."], ["Подать заявку валидатора", "Допуск требует проверки человеком."], ["Безопасная копия", "Разделяйте конфигурацию, секреты и данные цепи."], ["Осознанное восстановление", "Сохраните доказательства до повтора."], ["Без майнинга", "YNX Testnet не использует PoW."], ["Доказательство моста", "Локальная финальность не доказывает внешнее исполнение."]],
  ar: [["التحقق من 6423", "أكّد هوية Testnet الأساسية."], ["حماية المحفظة", "افصل العناوين العامة عن أسرار التوقيع."], ["استخدام YNXT", "YNXT مخصص لغاز ورسوم Testnet."], ["استخدام Explorer", "تحقق من النتائج بأدلة للقراءة فقط."], ["تشغيل عقدة مراقبة", "ابدأ عقدة بلا توقيع وبأقل صلاحيات."], ["طلب الانضمام كمدقق", "القبول يتطلب مراجعة بشرية."], ["نسخ احتياطي آمن", "افصل الإعدادات والأسرار وبيانات السلسلة."], ["استرداد حذر", "احفظ الأدلة قبل إعادة المحاولة."], ["لا تعدين", "YNX Testnet لا تستخدم PoW."], ["دليل الجسر", "النهائية المحلية لا تثبت التنفيذ الخارجي."]],
  id: [["Verifikasi 6423", "Pastikan identitas Testnet kanonik."], ["Lindungi dompet", "Pisahkan alamat publik dan rahasia tanda tangan."], ["Gunakan YNXT", "YNXT untuk gas dan biaya Testnet."], ["Gunakan Explorer", "Periksa hasil dengan bukti hanya-baca."], ["Jalankan observer", "Mulai node tanpa tanda tangan dan hak minimum."], ["Ajukan validator", "Penerimaan membutuhkan tinjauan manusia."], ["Cadangan aman", "Pisahkan konfigurasi, rahasia, dan data chain."], ["Pulihkan dengan hati-hati", "Simpan bukti sebelum mencoba lagi."], ["Tanpa mining", "YNX Testnet bukan PoW."], ["Bukti bridge", "Finalitas lokal bukan eksekusi chain eksternal."]],
};

for (const [locale, hero] of Object.entries(translatedManual)) {
  const rows = domainTranslations[locale].map(([title, lead]) => [title, lead, `${lead} 6423 / 0x1917 / YNXT.`, hero[3]]);
  manualRaw[locale] = { hero: hero.slice(0, 3), actions: PORTAL_COPY[locale]["/developers"].actions.slice(0, 2), platform: [hero[0], hero[1], hero[2], hero[3], hero[2], hero[3]], warning: hero[3], rows, recovery: [rows[7][1], rows[6][1], hero[3]] };
}

export const MANUAL_COPY = Object.fromEntries(Object.entries(manualRaw).map(([locale, value]) => [locale, manual(value.hero, value.actions, ["6423", "0x1917", "YNXT"], value.platform, chaptersFrom(value.rows, value.warning), value.recovery, value.warning)]));

export function getPortalCopy(locale, route) {
  return PORTAL_COPY[locale]?.[route] || null;
}

export function getManualCopy(locale) {
  return MANUAL_COPY[locale] || null;
}
