// Full documentation interface translations. Network identifiers and asset symbols stay canonical.
export const DOCS_UI_GLOBAL = {
  es: {
    eyebrow: "Empieza aquí · Documentación de YNX", title: "Comprende YNX y empieza a usarlo.", lead: "No necesitas descargar nada. Los manuales oficiales completos, las reglas de la red y la lógica de los productos se pueden leer directamente en esta página.", start: "Empieza en 10 minutos", read: "Leer los manuales completos",
    introEyebrow: "YNX en palabras sencillas", introTitle: "Qué es este proyecto y qué no es", network: "Red", chainId: "ID de cadena", asset: "Activo nativo", explorer: "Explorador", explorerLink: "Abrir datos en vivo",
    manualsEyebrow: "Manuales oficiales completos", manualsTitle: "Lee todos los manuales aquí", manualsLead: "Selecciona un manual a la izquierda. Su contenido oficial completo aparece a la derecha; no necesitas un ZIP ni visitar GitHub.", search: "Buscar en la documentación de YNX", nav: "Manuales oficiales", official: "Manual oficial", noMatch: "No hay manuales coincidentes", noMatchLead: "Prueba con Wallet, validador, minería, transferencia, Testnet, SDK, Pay o Explorer.",
    ecosystemEyebrow: "Todos los productos del ecosistema", ecosystemTitle: "Propósito, flujo de trabajo y reglas", ecosystemLead: "Estas explicaciones describen qué hace cada producto, cómo funciona su flujo completo y dónde debe bloquear una operación si no puede verificar sus condiciones.", how: "Cómo funciona", rules: "Reglas y límites", open: "Abrir", details: "detalles",
    runtimeEyebrow: "Evidencia de ejecución de Wallet/Auth · P0", runtimeTitle: "Un registro del servicio público Wallet/Auth que muestra sus límites", runtimeLead: "El servicio Wallet/Auth se verificó mediante lectura vinculada al código fuente exacto en ejecución. Las rutas de salud, disponibilidad y versión devolvieron HTTP 200. El ciclo público de Product Session comprobó CORS para orígenes registrados, persistencia tras reinicios, rechazo de repeticiones, revocación de sesiones y de dispositivos; los orígenes no registrados siguieron rechazados. Son hechos del Gateway, no una afirmación sobre una Wallet instalada o sobre transacciones.", runtimeRecord: "Abrir registro de ejecución", evidence: "Abrir evidencia exacta",
    safetyTitle: "Una regla para todo el ecosistema", safetyLead: "Una comprobación de salud, una compilación candidata, un resultado simulado o un artefacto local nunca se presenta como una capacidad pública de producción. Los estados desconocidos siguen siendo desconocidos.", exportTitle: "¿Necesitas un archivo sin conexión o una auditoría de integridad?", exportLead: "Los mismos manuales completos se pueden exportar opcionalmente como un ZIP verificado. Los usuarios habituales no necesitan este archivo.", exportLink: "Descargar archivo del código fuente de la documentación",
    startSteps: [
      ["1", "Obtén una dirección de Wallet", "Crea o restaura una dirección localmente. Los productos YNX nunca necesitan tu frase de recuperación."],
      ["2", "Solicita YNXT de Testnet", "Usa Faucet para recibir YNXT solo para pruebas. No se le atribuye valor monetario."],
      ["3", "Realiza una transferencia en Testnet", "Comprueba el destinatario, el importe y la comisión nativa actual de 1 YNXT antes de aprobar en Wallet."],
      ["4", "Verifícala en Explorer", "Busca el hash de la transacción y compara origen, destino, importe, comisión, estado y bloque."],
    ],
    coreFacts: [
      ["Qué es YNX", "Una cadena pública Testnet y un ecosistema coordinado de aplicaciones basado en una única identidad de Wallet controlada por el usuario."],
      ["Qué lo distingue", "Las aplicaciones comparten evidencia verificable de la cadena en lugar de pedir confianza en páginas de estado independientes. La aprobación de Wallet permanece separada de la IA y de la lógica del producto."],
      ["Objetivo final", "Una plataforma Web4 madura para comunicarse, pagar, desarrollar, operar, crear y gestionar datos sin dar a cada servicio un control ilimitado."],
      ["Límite actual", "Es un ecosistema candidato de Testnet, no una Mainnet, un banco, una cotización en bolsa de criptoactivos, una tarjeta emitida ni una promesa de rentabilidad financiera."],
    ],
    truths: [
      ["Transacciones y bloques", "Un bloque es un contenedor de transacciones finalizadas, no un YNXT. Puede contener varias transferencias; un bloque vacío no emite recompensas automáticas."],
      ["Modificación de bloques históricos", "Es imposible tras la finalidad: el bloque 1 o cualquier otro bloque finalizado no puede recibir después una nueva transacción."],
      ["Operación de nodos", "Únete primero como observador sincronizado; verifica altura, hash, pares, almacenamiento, monitorización, copia de seguridad y restauración antes de la revisión de candidatura."],
      ["Candidatura a validador", "El acceso a Testnet se revisa y está controlado por operadores. La documentación no equivale a una aprobación; si hay incertidumbre sobre el firmante, la operación se bloquea."],
      ["La realidad de la minería", "YNX Testnet utiliza validadores y productores de bloques rotativos, no minería de prueba de trabajo con GPU o ASIC."],
      ["Evidencia de Bridge", "El puente actual puede demostrar la transacción de origen en YNX y el ciclo local del relayer. El envío externo está desactivado: finalización local, sin envío externo."],
    ],
  },
  fr: {
    eyebrow: "Commencez ici · Documentation YNX", title: "Comprenez YNX, puis utilisez-le.", lead: "Aucun téléchargement n’est nécessaire. Les manuels officiels complets, les règles du réseau et la logique des produits sont consultables directement sur cette page.", start: "Démarrer en 10 minutes", read: "Lire les manuels complets",
    introEyebrow: "YNX en termes simples", introTitle: "Ce qu’est ce projet et ce qu’il n’est pas", network: "Réseau", chainId: "Identifiant de chaîne", asset: "Actif natif", explorer: "Explorateur", explorerLink: "Ouvrir les données en direct",
    manualsEyebrow: "Manuels officiels complets", manualsTitle: "Lisez tous les manuels ici", manualsLead: "Sélectionnez un manuel à gauche. Son contenu officiel intégral apparaît à droite ; aucun ZIP ni passage par GitHub n’est nécessaire.", search: "Rechercher dans la documentation YNX", nav: "Manuels officiels", official: "Manuel officiel", noMatch: "Aucun manuel correspondant", noMatchLead: "Essayez Wallet, validateur, minage, transfert, Testnet, SDK, Pay ou Explorer.",
    ecosystemEyebrow: "Tous les produits de l’écosystème", ecosystemTitle: "Objectif, fonctionnement et règles", ecosystemLead: "Ces explications décrivent le rôle de chaque produit, son parcours complet et les étapes qui doivent bloquer une opération si ses conditions ne sont pas vérifiées.", how: "Fonctionnement", rules: "Règles et limites", open: "Ouvrir", details: "détails",
    runtimeEyebrow: "Preuves d’exécution Wallet/Auth · P0", runtimeTitle: "Un relevé du service public Wallet/Auth présentant ses limites", runtimeLead: "Le service Wallet/Auth a été vérifié par lecture liée au code source exact en cours d’exécution. Les routes de santé, de disponibilité et de version ont renvoyé HTTP 200. Le cycle public de Product Session a vérifié CORS pour les origines enregistrées, la persistance après redémarrage, le rejet des rejeux, la révocation des sessions et des appareils ; les origines non enregistrées sont restées refusées. Ce sont des faits concernant le Gateway, pas une affirmation sur une Wallet installée ou des transactions.", runtimeRecord: "Ouvrir le relevé d’exécution", evidence: "Ouvrir les preuves exactes",
    safetyTitle: "Une règle pour tout l’écosystème", safetyLead: "Un contrôle de santé, une compilation candidate, un résultat simulé ou un artefact local ne sont jamais présentés comme une capacité publique de production. Les états inconnus restent inconnus.", exportTitle: "Besoin d’une archive hors ligne ou d’un audit d’intégrité ?", exportLead: "Les mêmes manuels complets peuvent être exportés dans un ZIP vérifié. Ce fichier est facultatif et inutile pour un usage courant.", exportLink: "Télécharger l’archive des sources de la documentation",
    startSteps: [
      ["1", "Obtenir une adresse Wallet", "Créez ou restaurez une adresse localement. Les produits YNX n’ont jamais besoin de votre phrase de récupération."],
      ["2", "Demander des YNXT de Testnet", "Utilisez Faucet pour recevoir des YNXT réservés aux tests. Aucune valeur monétaire ne leur est attribuée."],
      ["3", "Effectuer un transfert sur Testnet", "Vérifiez le destinataire, le montant et les frais natifs actuels de 1 YNXT avant l’approbation dans Wallet."],
      ["4", "Le vérifier dans Explorer", "Recherchez le hash de transaction et comparez expéditeur, destinataire, montant, frais, statut et bloc."],
    ],
    coreFacts: [
      ["Ce qu’est YNX", "Une chaîne Testnet publique et un écosystème coordonné d’applications construit autour d’une identité Wallet unique contrôlée par l’utilisateur."],
      ["Ce qui le distingue", "Les applications partagent des preuves vérifiables de la chaîne au lieu de demander de faire confiance à des pages de statut indépendantes. L’approbation Wallet reste séparée de l’IA et de la logique produit."],
      ["Objectif final", "Une plateforme Web4 mature pour communiquer, payer, développer, échanger, créer et gérer des données sans donner un contrôle illimité à chaque service."],
      ["Limite actuelle", "Il s’agit d’un écosystème candidat de Testnet, pas d’une Mainnet, d’une banque, d’une cotation sur une plateforme d’échange, d’une carte émise ou d’une promesse de rendement financier."],
    ],
    truths: [
      ["Transactions et blocs", "Un bloc contient des transactions finalisées ; il n’équivaut pas à un YNXT. Il peut contenir plusieurs transferts ; un bloc vide n’émet aucune récompense automatique."],
      ["Modification des blocs historiques", "Impossible après finalité : le bloc 1 ou tout autre bloc finalisé ne peut recevoir une nouvelle transaction ultérieurement."],
      ["Exploitation des nœuds", "Rejoignez d’abord le réseau comme observateur synchronisé ; vérifiez hauteur, hash, pairs, stockage, supervision, sauvegarde et restauration avant l’examen de candidature."],
      ["Candidature de validateur", "L’admission sur Testnet est examinée et contrôlée par les opérateurs. La documentation ne vaut pas approbation ; une incertitude sur le signataire bloque l’opération."],
      ["Réalité du minage", "YNX Testnet utilise une rotation de validateurs et de producteurs de blocs, pas un minage par preuve de travail sur GPU ou ASIC."],
      ["Preuves de Bridge", "Le pont actuel peut prouver la transaction source YNX et le cycle local du relayer. L’envoi externe est désactivé : finalisé localement, sans envoi externe."],
    ],
  },
  de: {
    eyebrow: "Hier beginnen · YNX-Dokumentation", title: "YNX verstehen und dann nutzen.", lead: "Kein Download erforderlich. Die vollständigen offiziellen Handbücher, Netzwerkregeln und Produktabläufe sind direkt auf dieser Seite lesbar.", start: "In 10 Minuten starten", read: "Vollständige Handbücher lesen",
    introEyebrow: "YNX einfach erklärt", introTitle: "Was dieses Projekt ist und was es nicht ist", network: "Netzwerk", chainId: "Chain-ID", asset: "Nativer Vermögenswert", explorer: "Explorer", explorerLink: "Live-Daten öffnen",
    manualsEyebrow: "Vollständige offizielle Handbücher", manualsTitle: "Alle Handbücher hier lesen", manualsLead: "Wählen Sie links ein Handbuch. Rechts erscheint der vollständige maßgebliche Inhalt; weder eine ZIP-Datei noch ein Besuch bei GitHub ist nötig.", search: "YNX-Dokumentation durchsuchen", nav: "Offizielle Handbücher", official: "Offizielles Handbuch", noMatch: "Kein passendes Handbuch", noMatchLead: "Versuchen Sie Wallet, Validator, Mining, Überweisung, Testnet, SDK, Pay oder Explorer.",
    ecosystemEyebrow: "Jedes Produkt im Ökosystem", ecosystemTitle: "Zweck, Ablauf und Regeln", ecosystemLead: "Diese Erläuterungen beschreiben die Aufgabe jedes Produkts, seinen vollständigen Ablauf und die Stellen, an denen Vorgänge bei ungeprüften Voraussetzungen sicher abgewiesen werden müssen.", how: "Funktionsweise", rules: "Regeln und Grenzen", open: "Öffnen", details: "Details",
    runtimeEyebrow: "Wallet/Auth-Laufzeitnachweise · P0", runtimeTitle: "Ein öffentlicher Wallet/Auth-Dienstnachweis mit klaren Grenzen", runtimeLead: "Der Wallet/Auth-Dienst wurde durch Rücklesen mit Bindung an den exakten ausgeführten Quellstand geprüft. Die Routen für Zustand, Bereitschaft und Version lieferten HTTP 200. Der öffentliche Product-Session-Ablauf prüfte CORS für registrierte Ursprünge, Persistenz nach Neustarts, Replay-Abweisung sowie Sitzungs- und Gerätewiderruf; nicht registrierte Ursprünge blieben abgewiesen. Dies sind Gateway-Nachweise, keine Aussage über eine installierte Wallet oder Transaktionen.", runtimeRecord: "Laufzeitprotokoll öffnen", evidence: "Exakte Nachweise öffnen",
    safetyTitle: "Eine Regel für das gesamte Ökosystem", safetyLead: "Eine Zustandsprüfung, ein Kandidaten-Build, ein Simulationsergebnis oder ein lokales Artefakt wird niemals als öffentlich verfügbare Produktionsfähigkeit dargestellt. Unbekannte Zustände bleiben unbekannt.", exportTitle: "Benötigen Sie ein Offline-Archiv oder eine Integritätsprüfung?", exportLead: "Die gleichen vollständigen Handbücher lassen sich optional als geprüftes ZIP exportieren. Für die normale Nutzung ist diese Datei nicht erforderlich.", exportLink: "Quellarchiv der Dokumentation herunterladen",
    startSteps: [
      ["1", "Eine Wallet-Adresse erhalten", "Erstellen Sie eine Adresse lokal oder stellen Sie sie lokal wieder her. YNX-Produkte benötigen niemals Ihre Wiederherstellungsphrase."],
      ["2", "Testnet-YNXT anfordern", "Verwenden Sie Faucet, um YNXT ausschließlich für Tests zu erhalten. Dafür wird kein Geldwert zugesichert."],
      ["3", "Eine Testnet-Überweisung durchführen", "Prüfen Sie Empfänger, Betrag und die aktuelle native Gebühr von 1 YNXT vor der Wallet-Freigabe."],
      ["4", "Im Explorer prüfen", "Suchen Sie nach dem Transaktionshash und vergleichen Sie Absender, Empfänger, Betrag, Gebühr, Status und Block."],
    ],
    coreFacts: [
      ["Was YNX ist", "Eine öffentliche Testnet-Chain mit einem abgestimmten Anwendungsökosystem rund um eine einzige, vom Nutzer kontrollierte Wallet-Identität."],
      ["Was YNX unterscheidet", "Anwendungen teilen überprüfbare Chain-Nachweise, statt Vertrauen in voneinander unabhängige Statusseiten zu verlangen. Die Wallet-Freigabe bleibt von KI und Produktlogik getrennt."],
      ["Langfristiges Ziel", "Eine ausgereifte Web4-Plattform zum Kommunizieren, Bezahlen, Entwickeln, Handeln, Gestalten und Verwalten von Daten, ohne jedem Dienst uneingeschränkte Kontrolle zu geben."],
      ["Aktuelle Grenze", "Dies ist ein Testnet-Kandidatenökosystem, keine Mainnet, Bank, Börsennotierung, ausgegebene Karte oder Zusage finanzieller Renditen."],
    ],
    truths: [
      ["Transaktionen und Blöcke", "Ein Block ist ein Behälter für finalisierte Transaktionen, nicht ein YNXT. Ein Block kann mehrere Überweisungen enthalten; ein leerer Block erzeugt keine automatische Belohnung."],
      ["Historische Blöcke ändern", "Nach der Finalität unmöglich: Block 1 und jeder andere finalisierte Block können später keine neue Transaktion aufnehmen."],
      ["Knotenbetrieb", "Treten Sie zunächst als synchronisierter Beobachter bei; prüfen Sie Höhe, Hash, Peers, Speicher, Überwachung, Sicherung und Wiederherstellung vor der Kandidatenprüfung."],
      ["Validator-Kandidat", "Die Aufnahme ins Testnet wird geprüft und von Betreibern kontrolliert. Dokumentation ist keine Genehmigung; bei Unsicherheit über den Signierer wird der Vorgang abgewiesen."],
      ["Fakten zum Mining", "YNX Testnet verwendet wechselnde Validatoren und Blockproduzenten, kein GPU- oder ASIC-Mining mit Proof of Work."],
      ["Bridge-Nachweise", "Die aktuelle Bridge kann die YNX-Quelltransaktion und den lokalen Relayer-Ablauf nachweisen. Externe Übermittlung ist deaktiviert: lokal finalisiert, keine externe Übermittlung."],
    ],
  },
  pt: {
    eyebrow: "Comece aqui · Documentação YNX", title: "Entenda o YNX e comece a usar.", lead: "Nenhum download é necessário. Os manuais oficiais completos, as regras da rede e a lógica dos produtos podem ser lidos diretamente nesta página.", start: "Comece em 10 minutos", read: "Ler os manuais completos",
    introEyebrow: "YNX em linguagem simples", introTitle: "O que este projeto é e o que não é", network: "Rede", chainId: "ID da cadeia", asset: "Ativo nativo", explorer: "Explorador", explorerLink: "Abrir dados ao vivo",
    manualsEyebrow: "Manuais oficiais completos", manualsTitle: "Leia todos os manuais aqui", manualsLead: "Selecione um manual à esquerda. O conteúdo oficial completo aparece à direita; não é necessário baixar um ZIP nem visitar o GitHub.", search: "Pesquisar na documentação YNX", nav: "Manuais oficiais", official: "Manual oficial", noMatch: "Nenhum manual correspondente", noMatchLead: "Tente Wallet, validador, mineração, transferência, Testnet, SDK, Pay ou Explorer.",
    ecosystemEyebrow: "Todos os produtos do ecossistema", ecosystemTitle: "Finalidade, fluxo de trabalho e regras", ecosystemLead: "Estas explicações descrevem o que cada produto faz, como funciona seu fluxo completo e onde deve bloquear operações cujas condições não possam ser verificadas.", how: "Como funciona", rules: "Regras e limites", open: "Abrir", details: "detalhes",
    runtimeEyebrow: "Evidências de execução de Wallet/Auth · P0", runtimeTitle: "Um registro do serviço público Wallet/Auth com seus limites explícitos", runtimeLead: "O serviço Wallet/Auth foi verificado por leitura vinculada ao código-fonte exato em execução. As rotas de saúde, prontidão e versão retornaram HTTP 200. O ciclo público de Product Session verificou CORS para origens registradas, persistência após reinícios, rejeição de repetições e revogação de sessões e dispositivos; origens não registradas continuaram rejeitadas. São fatos do Gateway, não uma afirmação sobre uma Wallet instalada ou transações.", runtimeRecord: "Abrir registro de execução", evidence: "Abrir evidências exatas",
    safetyTitle: "Uma regra para todo o ecossistema", safetyLead: "Uma verificação de saúde, uma compilação candidata, um resultado simulado ou um artefato local nunca é apresentado como capacidade pública de produção. Estados desconhecidos continuam desconhecidos.", exportTitle: "Precisa de um arquivo offline ou de uma auditoria de integridade?", exportLead: "Os mesmos manuais completos podem ser exportados opcionalmente como um ZIP verificado. Usuários comuns não precisam deste arquivo.", exportLink: "Baixar arquivo do código-fonte da documentação",
    startSteps: [
      ["1", "Obtenha um endereço de Wallet", "Crie ou restaure um endereço localmente. Os produtos YNX nunca precisam da sua frase de recuperação."],
      ["2", "Solicite YNXT de Testnet", "Use o Faucet para receber YNXT exclusivo para testes. Nenhum valor monetário é atribuído a ele."],
      ["3", "Faça uma transferência na Testnet", "Confira o destinatário, o valor e a taxa nativa atual de 1 YNXT antes de aprovar na Wallet."],
      ["4", "Verifique no Explorer", "Pesquise o hash da transação e compare remetente, destinatário, valor, taxa, status e bloco."],
    ],
    coreFacts: [
      ["O que é YNX", "Uma cadeia Testnet pública e um ecossistema coordenado de aplicativos construído em torno de uma única identidade de Wallet controlada pelo usuário."],
      ["O que o diferencia", "Os aplicativos compartilham evidências verificáveis da cadeia, em vez de pedir confiança em páginas de status desconectadas. A aprovação da Wallet permanece separada da IA e da lógica dos produtos."],
      ["Objetivo final", "Uma plataforma Web4 madura para comunicar, pagar, desenvolver, negociar, criar e gerenciar dados sem conceder controle irrestrito a cada serviço."],
      ["Limite atual", "Este é um ecossistema candidato de Testnet, não uma Mainnet, um banco, uma listagem em uma corretora, um cartão emitido ou uma promessa de retorno financeiro."],
    ],
    truths: [
      ["Transações e blocos", "Um bloco é um contêiner de transações finalizadas, não um YNXT. Um bloco pode conter várias transferências; um bloco vazio não emite recompensa automática."],
      ["Alteração de blocos históricos", "Impossível após a finalidade: o bloco 1 ou qualquer outro bloco finalizado não pode receber uma nova transação posteriormente."],
      ["Operação de nós", "Entre primeiro como observador sincronizado; verifique altura, hash, pares, armazenamento, monitoramento, backup e restauração antes da avaliação da candidatura."],
      ["Candidato a validador", "A admissão na Testnet passa por avaliação e é controlada por operadores. Documentação não é aprovação; incertezas sobre o assinante bloqueiam a operação."],
      ["A realidade da mineração", "YNX Testnet usa validadores e produtores de blocos em rotação, não mineração de prova de trabalho com GPU ou ASIC."],
      ["Evidências de Bridge", "A ponte atual pode comprovar a transação de origem YNX e o ciclo local do relayer. O envio externo está desativado: finalizado localmente, sem envio externo."],
    ],
  },
  ru: {
    eyebrow: "Начните здесь · Документация YNX", title: "Разберитесь в YNX и начните пользоваться.", lead: "Скачивать ничего не нужно. Полные официальные руководства, правила сети и логика продуктов доступны прямо на этой странице.", start: "Начать за 10 минут", read: "Читать полные руководства",
    introEyebrow: "YNX простыми словами", introTitle: "Что представляет собой этот проект и чем он не является", network: "Сеть", chainId: "Идентификатор цепочки", asset: "Нативный актив", explorer: "Обозреватель", explorerLink: "Открыть актуальные данные",
    manualsEyebrow: "Полные официальные руководства", manualsTitle: "Все руководства можно читать здесь", manualsLead: "Выберите руководство слева. Справа появится его полный официальный текст; скачивать ZIP или переходить на GitHub не нужно.", search: "Поиск по документации YNX", nav: "Официальные руководства", official: "Официальное руководство", noMatch: "Подходящих руководств нет", noMatchLead: "Попробуйте Wallet, валидатор, майнинг, перевод, Testnet, SDK, Pay или Explorer.",
    ecosystemEyebrow: "Все продукты экосистемы", ecosystemTitle: "Назначение, рабочие процессы и правила", ecosystemLead: "Здесь описано назначение каждого продукта, его полный рабочий цикл и этапы, на которых операция должна блокироваться, если её условия невозможно проверить.", how: "Как это работает", rules: "Правила и ограничения", open: "Открыть", details: "подробности",
    runtimeEyebrow: "Свидетельства работы Wallet/Auth · P0", runtimeTitle: "Запись о публичном сервисе Wallet/Auth с указанием ограничений", runtimeLead: "Сервис Wallet/Auth проверен чтением с привязкой к точному исходному коду работающей версии. Маршруты состояния, готовности и версии вернули HTTP 200. Публичный цикл Product Session проверил CORS для зарегистрированных источников, сохранение состояния после перезапуска, отклонение повторного воспроизведения запросов, отзыв сессий и устройств; незарегистрированные источники по-прежнему отклонялись. Это факты о Gateway, а не подтверждение установленной Wallet или выполнения транзакций.", runtimeRecord: "Открыть запись о работе", evidence: "Открыть точные свидетельства",
    safetyTitle: "Одно правило для всей экосистемы", safetyLead: "Проверка состояния, сборка-кандидат, результат симуляции или локальный артефакт никогда не выдаются за публичную производственную возможность. Неизвестные состояния остаются неизвестными.", exportTitle: "Нужен автономный архив или проверка целостности?", exportLead: "Те же полные руководства при желании можно экспортировать в проверенный ZIP. Для обычного использования этот файл не нужен.", exportLink: "Скачать архив исходников документации",
    startSteps: [
      ["1", "Получите адрес Wallet", "Создайте или восстановите адрес локально. Продуктам YNX никогда не нужна ваша фраза восстановления."],
      ["2", "Получите тестовые YNXT", "Используйте Faucet для получения YNXT только для тестирования. Им не приписывается денежная стоимость."],
      ["3", "Сделайте перевод в Testnet", "Перед подтверждением в Wallet проверьте получателя, сумму и текущую нативную комиссию 1 YNXT."],
      ["4", "Проверьте его в Explorer", "Найдите хеш транзакции и сравните отправителя, получателя, сумму, комиссию, статус и блок."],
    ],
    coreFacts: [
      ["Что такое YNX", "Публичная тестовая цепочка и согласованная экосистема приложений, построенная вокруг единой идентичности Wallet под контролем пользователя."],
      ["В чём отличие", "Приложения используют общие проверяемые свидетельства из цепочки, а не предлагают доверять разрозненным страницам статуса. Подтверждение в Wallet отделено от ИИ и логики продуктов."],
      ["Конечная цель", "Зрелая платформа Web4 для общения, платежей, разработки, торговли, творчества и управления данными без передачи каждому сервису неограниченного контроля."],
      ["Текущие ограничения", "Это экосистема-кандидат Testnet, а не Mainnet, банк, листинг на бирже, выпущенная карта или обещание финансовой доходности."],
    ],
    truths: [
      ["Транзакции и блоки", "Блок — контейнер финализированных транзакций, а не один YNXT. Он может содержать несколько переводов; пустой блок не создаёт автоматического вознаграждения."],
      ["Изменение прошлых блоков", "После финализации невозможно: ни блок 1, ни любой другой финализированный блок нельзя позднее дополнить новой транзакцией."],
      ["Эксплуатация узлов", "Сначала подключитесь как синхронизированный наблюдатель; до рассмотрения кандидатуры проверьте высоту, хеш, соседние узлы, хранилище, мониторинг, резервное копирование и восстановление."],
      ["Кандидат в валидаторы", "Допуск в Testnet проходит проверку и контролируется операторами. Документация не является разрешением; при неопределённости относительно подписанта операция блокируется."],
      ["Факты о майнинге", "YNX Testnet использует сменяющихся валидаторов и производителей блоков, а не майнинг Proof of Work на GPU или ASIC."],
      ["Свидетельства Bridge", "Текущий мост может подтвердить исходную транзакцию YNX и локальный цикл relayer. Внешняя отправка отключена: финализировано локально, без внешней отправки."],
    ],
  },
  ar: {
    eyebrow: "ابدأ هنا · وثائق YNX", title: "افهم YNX ثم ابدأ استخدامه.", lead: "لا يلزم تنزيل أي شيء. يمكنك قراءة الأدلة الرسمية الكاملة وقواعد الشبكة ومنطق المنتجات مباشرة في هذه الصفحة.", start: "ابدأ خلال 10 دقائق", read: "اقرأ الأدلة الكاملة",
    introEyebrow: "YNX بلغة بسيطة", introTitle: "ما هذا المشروع وما الذي لا يمثله", network: "الشبكة", chainId: "معرّف السلسلة", asset: "الأصل الأصلي", explorer: "مستكشف السلسلة", explorerLink: "افتح البيانات المباشرة",
    manualsEyebrow: "الأدلة الرسمية الكاملة", manualsTitle: "اقرأ جميع الأدلة هنا", manualsLead: "اختر دليلاً من القائمة على اليسار. يظهر محتواه الرسمي الكامل على اليمين؛ لا تحتاج إلى ملف ZIP أو زيارة GitHub.", search: "ابحث في وثائق YNX", nav: "الأدلة الرسمية", official: "دليل رسمي", noMatch: "لا يوجد دليل مطابق", noMatchLead: "جرّب Wallet أو المدقق أو التعدين أو التحويل أو Testnet أو SDK أو Pay أو Explorer.",
    ecosystemEyebrow: "جميع منتجات المنظومة", ecosystemTitle: "الغرض وسير العمل والقواعد", ecosystemLead: "توضح هذه الشروحات وظيفة كل منتج وكيف يكتمل سير عمله والمواضع التي يجب أن تمنع العملية إذا تعذر التحقق من شروطها.", how: "كيفية العمل", rules: "القواعد والحدود", open: "افتح", details: "التفاصيل",
    runtimeEyebrow: "أدلة تشغيل Wallet/Auth · P0", runtimeTitle: "سجل لخدمة Wallet/Auth العامة يوضح حدودها", runtimeLead: "تم التحقق من خدمة Wallet/Auth بالقراءة مع ربطها بالشيفرة المصدرية الدقيقة قيد التشغيل. أعادت مسارات الصحة والجاهزية والإصدار HTTP 200. اختبرت دورة Product Session العامة قواعد CORS للمصادر المسجلة واستمرار الحالة بعد إعادة التشغيل ورفض إعادة إرسال الطلبات المسجلة وإلغاء الجلسات والأجهزة؛ وظلت المصادر غير المسجلة مرفوضة. هذه حقائق عن Gateway وليست إثباتاً لتثبيت Wallet أو تنفيذ معاملات.", runtimeRecord: "افتح سجل التشغيل", evidence: "افتح الأدلة الدقيقة",
    safetyTitle: "قاعدة واحدة في جميع أنحاء المنظومة", safetyLead: "لا يُعرض فحص الصحة أو البناء المرشح أو نتيجة المحاكاة أو ملف البناء المحلي على أنه قدرة إنتاجية عامة. تظل الحالات المجهولة مجهولة.", exportTitle: "هل تحتاج إلى أرشيف دون اتصال أو تدقيق للسلامة؟", exportLead: "يمكن تصدير الأدلة الكاملة نفسها اختيارياً في ملف ZIP تم التحقق منه. لا يحتاج المستخدم العادي إلى هذا الملف.", exportLink: "نزّل أرشيف مصادر الوثائق",
    startSteps: [
      ["1", "احصل على عنوان Wallet", "أنشئ عنواناً أو استعده محلياً. لا تحتاج منتجات YNX مطلقاً إلى عبارة الاسترداد الخاصة بك."],
      ["2", "اطلب YNXT من Testnet", "استخدم Faucet للحصول على YNXT مخصص للاختبار فقط. لا تُنسب إليه قيمة نقدية."],
      ["3", "نفّذ تحويلاً على Testnet", "راجع المستلم والمبلغ والرسم الأصلي الحالي البالغ 1 YNXT قبل الموافقة في Wallet."],
      ["4", "تحقق منه في Explorer", "ابحث عن تجزئة المعاملة وقارن المرسل والمستلم والمبلغ والرسم والحالة والكتلة."],
    ],
    coreFacts: [
      ["ما هو YNX", "سلسلة Testnet عامة ومنظومة تطبيقات منسقة تتمحور حول هوية Wallet واحدة يتحكم فيها المستخدم."],
      ["ما الذي يميّزه", "تتشارك التطبيقات أدلة السلسلة القابلة للتحقق بدلاً من مطالبة المستخدمين بالثقة في صفحات حالة منفصلة. تظل موافقة Wallet مستقلة عن الذكاء الاصطناعي ومنطق المنتج."],
      ["الهدف النهائي", "منصة Web4 ناضجة تتيح التواصل والدفع والتطوير والتداول والإبداع وإدارة البيانات دون منح كل خدمة تحكماً غير محدود."],
      ["الحدود الحالية", "هذه منظومة مرشحة على Testnet، وليست Mainnet أو بنكاً أو إدراجاً في منصة تداول أو بطاقة صادرة أو وعداً بعائد مالي."],
    ],
    truths: [
      ["المعاملات والكتل", "الكتلة حاوية لمعاملات نهائية، وليست وحدة YNXT واحدة. يمكن أن تضم عدة تحويلات؛ ولا تصدر الكتلة الفارغة مكافأة تلقائية."],
      ["تعديل الكتل السابقة", "مستحيل بعد النهائية: لا يمكن إضافة معاملة جديدة لاحقاً إلى الكتلة 1 أو أي كتلة أخرى نهائية."],
      ["تشغيل العقد", "انضم أولاً كمراقب متزامن؛ وتحقق من الارتفاع والتجزئة والعقد النظيرة والتخزين والمراقبة والنسخ الاحتياطي والاستعادة قبل مراجعة الترشيح."],
      ["الترشح كمدقق", "يخضع القبول في Testnet للمراجعة ويتحكم فيه المشغّلون. الوثائق لا تعني الموافقة؛ ويجب منع العملية عند عدم اليقين بشأن الجهة الموقّعة."],
      ["حقيقة التعدين", "تستخدم YNX Testnet مدققين ومنتجي كتل بالتناوب، ولا تستخدم تعدين إثبات العمل عبر GPU أو ASIC."],
      ["أدلة Bridge", "يمكن للجسر الحالي إثبات معاملة المصدر على YNX ودورة عمل المرحّل المحلية. الإرسال الخارجي معطل: نهائية محلية دون إرسال خارجي."],
    ],
  },
  id: {
    eyebrow: "Mulai di sini · Dokumentasi YNX", title: "Pahami YNX, lalu gunakan.", lead: "Tidak perlu mengunduh apa pun. Panduan resmi lengkap, aturan jaringan, dan logika produk dapat dibaca langsung di halaman ini.", start: "Mulai dalam 10 menit", read: "Baca panduan lengkap",
    introEyebrow: "YNX dalam bahasa sederhana", introTitle: "Apa proyek ini dan apa yang bukan", network: "Jaringan", chainId: "ID rantai", asset: "Aset asli", explorer: "Penjelajah", explorerLink: "Buka data langsung",
    manualsEyebrow: "Panduan resmi lengkap", manualsTitle: "Baca semua panduan di sini", manualsLead: "Pilih panduan di sebelah kiri. Isi resminya yang lengkap akan tampil di sebelah kanan; tidak perlu ZIP atau mengunjungi GitHub.", search: "Cari dokumentasi YNX", nav: "Panduan resmi", official: "Panduan resmi", noMatch: "Tidak ada panduan yang cocok", noMatchLead: "Coba Wallet, validator, penambangan, transfer, Testnet, SDK, Pay, atau Explorer.",
    ecosystemEyebrow: "Semua produk ekosistem", ecosystemTitle: "Tujuan, alur kerja, dan aturan", ecosystemLead: "Penjelasan ini menjabarkan fungsi tiap produk, cara kerja alurnya secara lengkap, dan tahap yang harus memblokir operasi jika persyaratannya tidak dapat diverifikasi.", how: "Cara kerja", rules: "Aturan dan batasan", open: "Buka", details: "detail",
    runtimeEyebrow: "Bukti runtime Wallet/Auth · P0", runtimeTitle: "Catatan layanan Wallet/Auth publik beserta batasannya", runtimeLead: "Layanan Wallet/Auth diverifikasi melalui pembacaan yang terikat pada kode sumber runtime yang tepat. Rute kesehatan, kesiapan, dan versi mengembalikan HTTP 200. Siklus Product Session publik menguji CORS untuk asal terdaftar, persistensi setelah restart, penolakan pemutaran ulang permintaan, pencabutan sesi, dan pencabutan perangkat; asal yang tidak terdaftar tetap ditolak. Ini adalah fakta Gateway, bukan klaim tentang Wallet yang terpasang atau transaksi.", runtimeRecord: "Buka catatan runtime", evidence: "Buka bukti yang tepat",
    safetyTitle: "Satu aturan untuk seluruh ekosistem", safetyLead: "Pemeriksaan kesehatan, build kandidat, hasil simulasi, atau artefak lokal tidak pernah ditampilkan sebagai kemampuan produksi publik. Status yang belum diketahui tetap dinyatakan belum diketahui.", exportTitle: "Perlu arsip offline atau audit integritas?", exportLead: "Panduan lengkap yang sama dapat diekspor secara opsional sebagai ZIP terverifikasi. Pengguna biasa tidak memerlukan berkas ini.", exportLink: "Unduh arsip sumber dokumentasi",
    startSteps: [
      ["1", "Dapatkan alamat Wallet", "Buat atau pulihkan alamat secara lokal. Produk YNX tidak pernah memerlukan frasa pemulihan Anda."],
      ["2", "Klaim YNXT Testnet", "Gunakan Faucet untuk menerima YNXT khusus pengujian. Tidak ada nilai uang yang dinyatakan untuknya."],
      ["3", "Lakukan transfer Testnet", "Periksa penerima, jumlah, dan biaya asli saat ini sebesar 1 YNXT sebelum menyetujui di Wallet."],
      ["4", "Verifikasi di Explorer", "Cari hash transaksi dan bandingkan pengirim, penerima, jumlah, biaya, status, dan blok."],
    ],
    coreFacts: [
      ["Apa itu YNX", "Rantai Testnet publik beserta ekosistem aplikasi terkoordinasi yang dibangun di sekitar satu identitas Wallet yang dikendalikan pengguna."],
      ["Apa yang membedakannya", "Aplikasi berbagi bukti rantai yang dapat diverifikasi, bukan meminta pengguna memercayai halaman status yang terpisah. Persetujuan Wallet tetap terpisah dari AI dan logika produk."],
      ["Tujuan akhir", "Platform Web4 yang matang agar orang dapat berkomunikasi, membayar, mengembangkan, berdagang, berkarya, dan mengelola data tanpa memberi setiap layanan kendali tanpa batas."],
      ["Batasan saat ini", "Ini adalah ekosistem kandidat Testnet, bukan Mainnet, bank, pencatatan aset di bursa, kartu yang telah diterbitkan, atau janji imbal hasil keuangan."],
    ],
    truths: [
      ["Transaksi dan blok", "Blok adalah wadah transaksi yang sudah final, bukan satu YNXT. Satu blok dapat memuat beberapa transfer; blok kosong tidak menerbitkan imbalan otomatis."],
      ["Mengubah blok historis", "Mustahil setelah finalitas: blok 1 atau blok lain yang sudah final tidak dapat menerima transaksi baru di kemudian hari."],
      ["Operasi node", "Bergabunglah sebagai pengamat tersinkronisasi terlebih dahulu; verifikasi ketinggian, hash, peer, penyimpanan, pemantauan, cadangan, dan pemulihan sebelum peninjauan kandidat."],
      ["Kandidat validator", "Penerimaan Testnet ditinjau dan dikendalikan operator. Dokumentasi bukan persetujuan; ketidakpastian tentang penanda tangan harus memblokir operasi."],
      ["Fakta penambangan", "YNX Testnet memakai validator dan produsen blok bergilir, bukan penambangan proof-of-work dengan GPU atau ASIC."],
      ["Bukti Bridge", "Bridge saat ini dapat membuktikan transaksi sumber YNX dan siklus relayer lokal. Pengiriman eksternal dinonaktifkan: final secara lokal, tanpa pengiriman eksternal."],
    ],
  },
};
