const keys = ['translated', 'translationNotice', 'bodyLanguage', 'originalLanguage', 'translationChecksum', 'operatorNotice', 'currentGuide'];
const values = {
  en: ['Translated draft', 'This translation preserves the source version and its dated claims. It is not a new specification or evidence of a current release.', 'Displayed language', 'Original language', 'Translation SHA-256', 'These archived commands describe an earlier local or operator workflow. They do not enroll a public validator, enable public contract deployment or grant signing authority. Use the current guide for supported steps.', 'Read the current guide'],
  'zh-CN': ['翻译草稿', '译文保留来源版本及其当时的声明，不构成新规范或当前发布证据。', '显示语言', '原文语言', '译文 SHA-256', '这些归档命令描述较早的本地或运营者工作流，不会加入公开验证者集合、启用公开合约部署或授予签名权限。当前支持的步骤请阅读新版指南。', '阅读当前指南'],
  'zh-TW': ['翻譯草稿', '譯文保留來源版本及其當時的聲明，不構成新規範或目前發布的證據。', '顯示語言', '原文語言', '譯文 SHA-256', '這些封存命令描述較早的本機或營運者工作流程，不會加入公開驗證者集合、啟用公開合約部署或授予簽章權限。目前支援的步驟請閱讀新版指南。', '閱讀目前指南'],
  ja: ['翻訳草案', '翻訳は出典のバージョンと当時の記述を保持します。新しい仕様や現在のリリースを示す証拠ではありません。', '表示言語', '原文の言語', '翻訳の SHA-256', 'このアーカイブのコマンドは、以前のローカルまたは運用者向け手順です。公開バリデータへの参加、公開コントラクトのデプロイ、署名権限の付与は行いません。現在対応する手順は最新ガイドをご覧ください。', '現在のガイドを読む'],
  ko: ['번역 초안', '번역은 출처 버전과 당시의 설명을 유지합니다. 새로운 명세나 현재 릴리스의 증거가 아닙니다.', '표시 언어', '원문 언어', '번역 SHA-256', '보관된 명령은 이전 로컬 또는 운영자 작업 흐름을 설명합니다. 공개 검증자로 등록하거나 공개 컨트랙트 배포를 활성화하거나 서명 권한을 부여하지 않습니다. 현재 지원되는 절차는 최신 가이드를 확인하세요.', '현재 가이드 읽기'],
  es: ['Borrador traducido', 'La traducción conserva la versión y las afirmaciones fechadas de la fuente. No es una nueva especificación ni prueba de una versión actual.', 'Idioma mostrado', 'Idioma original', 'SHA-256 de la traducción', 'Estos comandos archivados describen un flujo local o de operador anterior. No incorporan validadores públicos, habilitan contratos públicos ni conceden autoridad de firma. Consulta la guía actual para los pasos admitidos.', 'Leer la guía actual'],
  fr: ['Traduction provisoire', 'Cette traduction conserve la version source et ses affirmations datées. Elle ne constitue ni une nouvelle spécification ni une preuve de publication actuelle.', 'Langue affichée', 'Langue originale', 'SHA-256 de la traduction', 'Ces commandes archivées décrivent un ancien parcours local ou opérateur. Elles ne permettent ni de rejoindre les validateurs publics, ni de déployer des contrats publics, ni de recevoir un droit de signature. Consultez le guide actuel pour les étapes prises en charge.', 'Lire le guide actuel'],
  de: ['Übersetzter Entwurf', 'Diese Übersetzung bewahrt die Quellversion und ihre damaligen Aussagen. Sie ist weder eine neue Spezifikation noch ein Beleg für eine aktuelle Veröffentlichung.', 'Angezeigte Sprache', 'Originalsprache', 'SHA-256 der Übersetzung', 'Diese archivierten Befehle beschreiben einen früheren lokalen oder Betreiberablauf. Sie nehmen keine öffentlichen Validatoren auf, ermöglichen keine öffentlichen Vertragsdeployments und erteilen keine Signaturrechte. Unterstützte Schritte stehen im aktuellen Leitfaden.', 'Aktuellen Leitfaden lesen'],
  pt: ['Rascunho traduzido', 'Esta tradução preserva a versão da fonte e suas afirmações datadas. Não é uma nova especificação nem prova de uma versão atual.', 'Idioma exibido', 'Idioma original', 'SHA-256 da tradução', 'Estes comandos arquivados descrevem um fluxo local ou de operador anterior. Não incluem validadores públicos, habilitam contratos públicos nem concedem autoridade de assinatura. Consulte o guia atual para os passos suportados.', 'Ler o guia atual'],
  ru: ['Черновой перевод', 'Перевод сохраняет версию источника и утверждения на указанную дату. Он не является новой спецификацией или доказательством текущего выпуска.', 'Язык отображения', 'Язык оригинала', 'SHA-256 перевода', 'Архивные команды описывают прежний локальный процесс или работу оператора. Они не подключают публичных валидаторов, не включают развёртывание публичных контрактов и не дают права подписи. Поддерживаемые шаги приведены в текущем руководстве.', 'Открыть текущее руководство'],
  ar: ['مسودة مترجمة', 'تحافظ هذه الترجمة على إصدار المصدر وادعاءاته المؤرخة. وهي ليست مواصفة جديدة أو دليلاً على إصدار حالي.', 'لغة العرض', 'لغة الأصل', 'SHA-256 للترجمة', 'تصف هذه الأوامر المؤرشفة سير عمل محلياً أو خاصاً بالمشغّل في إصدار سابق. لا تضم مدققين عامين ولا تفعّل نشر عقود عامة ولا تمنح صلاحية التوقيع. راجع الدليل الحالي للخطوات المدعومة.', 'قراءة الدليل الحالي'],
  id: ['Draf terjemahan', 'Terjemahan ini mempertahankan versi sumber dan klaim pada tanggalnya. Ini bukan spesifikasi baru atau bukti rilis saat ini.', 'Bahasa tampilan', 'Bahasa asli', 'SHA-256 terjemahan', 'Perintah arsip ini menjelaskan alur lokal atau operator versi lama. Perintah tersebut tidak mendaftarkan validator publik, mengaktifkan kontrak publik, atau memberikan wewenang tanda tangan. Lihat panduan terkini untuk langkah yang didukung.', 'Baca panduan terkini'],
};
export function getDocumentTranslationCopy(locale = 'en') {
  return Object.fromEntries(keys.map((key, index) => [key, (values[locale] || values.en)[index]]));
}
