const copy = {
  en: ["Ecosystem downloads", "Explore 26 YNX products. Find a public web entry or a verified Testnet package.", "Search products, for example Wallet, DEX, AI…", "All", "Choose a way to open or install", "Open web", "Versions & downloads", "No verified public web entry or package yet.", "Available packages", "No verified installer for this platform. Use an available option or view the release status.", "Release details and safety notes", "All ways", "Web", "Packages", "Unavailable", "All platforms", "Desktop", "Mobile", "Browser", "Clear filters", "products", "No matching products", "Select a product to inspect its verified public options.", "View release status", "Public Testnet preview; check the release evidence before installing."],
  "zh-CN": ["生态与下载", "探索 YNX 生态的 26 个产品。查找已核验的网页入口或测试网安装包。", "搜索产品（例如 Wallet、DEX、AI…）", "全部", "选择平台下载或打开", "打开网页版", "查看版本与下载", "尚无已核验的公开网页或安装包。", "可用安装包", "该平台暂无已核验安装包；请选择可用方式或查看发布状态。", "发布详情与安全提示", "全部方式", "网页", "安装包", "暂不可用", "全部平台", "桌面", "移动", "浏览器", "清除筛选", "个产品", "没有匹配的产品", "选择产品查看已核验的公开入口。", "查看发布状态", "公开测试网预览；安装前请核对发布证据。"],
  "zh-TW": ["生態與下載", "探索 YNX 生態的 26 個產品。尋找已驗證的網頁入口或測試網安裝套件。", "搜尋產品（例如 Wallet、DEX、AI…）", "全部", "選擇平台下載或開啟", "開啟網頁版", "查看版本與下載", "目前沒有已驗證的公開網頁或安裝套件。", "可用安裝套件", "此平台尚無已驗證安裝套件；請選擇可用方式或查看發佈狀態。", "發佈詳情與安全提示", "所有方式", "網頁", "安裝套件", "暫不可用", "所有平台", "桌面", "行動", "瀏覽器", "清除篩選", "個產品", "沒有符合的產品", "選擇產品查看已驗證的公開入口。", "查看發佈狀態", "公開測試網預覽；安裝前請核對發佈證據。"],
  ja: ["エコシステムとダウンロード", "YNX の26製品から、確認済みの公開Web入口とTestnetパッケージを探せます。", "製品を検索（Wallet、DEX、AIなど）", "すべて", "開く方法またはインストール先を選択", "Webを開く", "バージョンとダウンロード", "確認済みの公開Web入口やパッケージはまだありません。", "利用可能なパッケージ", "このプラットフォームには確認済みのパッケージがありません。別の方法かリリース状況をご覧ください。", "リリース詳細と安全上の注意", "すべての方法", "Web", "パッケージ", "利用不可", "すべてのプラットフォーム", "デスクトップ", "モバイル", "ブラウザー", "絞り込みを解除", "製品", "一致する製品がありません", "製品を選ぶと確認済みの公開方法を表示します。", "リリース状況を見る", "公開Testnetプレビューです。インストール前にリリース証拠を確認してください。"],
  ko: ["생태계와 다운로드", "YNX 제품 26개에서 검증된 공개 웹 진입점과 테스트넷 패키지를 찾으세요.", "제품 검색 (Wallet, DEX, AI 등)", "전체", "열기 또는 설치 방법 선택", "웹 열기", "버전 및 다운로드", "검증된 공개 웹이나 패키지가 아직 없습니다.", "제공 중인 패키지", "이 플랫폼에는 검증된 패키지가 없습니다. 다른 방법이나 릴리스 상태를 확인하세요.", "릴리스 세부 정보 및 안전 안내", "모든 방식", "웹", "패키지", "사용 불가", "모든 플랫폼", "데스크톱", "모바일", "브라우저", "필터 지우기", "개 제품", "일치하는 제품 없음", "제품을 선택하면 검증된 공개 옵션을 볼 수 있습니다.", "릴리스 상태 보기", "공개 테스트넷 미리보기입니다. 설치 전 릴리스 증거를 확인하세요."],
  es: ["Ecosistema y descargas", "Explora 26 productos YNX y encuentra entradas web públicas o paquetes Testnet verificados.", "Buscar productos (Wallet, DEX, AI…)", "Todos", "Elige cómo abrir o instalar", "Abrir web", "Versiones y descargas", "Aún no hay web pública ni paquete verificado.", "Paquetes disponibles", "No hay paquete verificado para esta plataforma. Usa otra opción o consulta el estado de la versión.", "Detalles y avisos de seguridad", "Todos los métodos", "Web", "Paquetes", "No disponible", "Todas las plataformas", "Escritorio", "Móvil", "Navegador", "Borrar filtros", "productos", "No hay productos coincidentes", "Selecciona un producto para ver sus opciones públicas verificadas.", "Ver estado de versión", "Vista previa Testnet pública; verifica la evidencia antes de instalar."],
  fr: ["Écosystème et téléchargements", "Explorez 26 produits YNX et trouvez les accès Web publics ou paquets Testnet vérifiés.", "Rechercher (Wallet, DEX, AI…)", "Tous", "Choisissez comment ouvrir ou installer", "Ouvrir le Web", "Versions et téléchargements", "Aucun accès Web public ni paquet vérifié pour le moment.", "Paquets disponibles", "Aucun paquet vérifié pour cette plateforme. Choisissez une autre option ou consultez la version.", "Détails et consignes de sécurité", "Tous les modes", "Web", "Paquets", "Indisponible", "Toutes les plateformes", "Ordinateur", "Mobile", "Navigateur", "Effacer les filtres", "produits", "Aucun produit correspondant", "Sélectionnez un produit pour voir ses options publiques vérifiées.", "Voir le statut de version", "Aperçu Testnet public ; vérifiez les preuves avant installation."],
  de: ["Ökosystem und Downloads", "Entdecke 26 YNX-Produkte und finde geprüfte öffentliche Web-Zugänge oder Testnet-Pakete.", "Produkte suchen (Wallet, DEX, AI…)", "Alle", "Öffnen oder installieren", "Web öffnen", "Versionen und Downloads", "Noch kein geprüfter öffentlicher Web-Zugang oder Paket.", "Verfügbare Pakete", "Für diese Plattform gibt es kein geprüftes Paket. Nutze eine andere Option oder prüfe den Release-Status.", "Release-Details und Sicherheitshinweise", "Alle Wege", "Web", "Pakete", "Nicht verfügbar", "Alle Plattformen", "Desktop", "Mobil", "Browser", "Filter löschen", "Produkte", "Keine passenden Produkte", "Wähle ein Produkt für geprüfte öffentliche Optionen.", "Release-Status ansehen", "Öffentliche Testnet-Vorschau; prüfe die Nachweise vor der Installation."],
  pt: ["Ecossistema e downloads", "Explore 26 produtos YNX e encontre entradas Web públicas ou pacotes Testnet verificados.", "Buscar produtos (Wallet, DEX, AI…)", "Todos", "Escolha como abrir ou instalar", "Abrir Web", "Versões e downloads", "Ainda não há entrada Web pública nem pacote verificado.", "Pacotes disponíveis", "Não há pacote verificado para esta plataforma. Use outra opção ou veja o estado da versão.", "Detalhes e avisos de segurança", "Todos os métodos", "Web", "Pacotes", "Indisponível", "Todas as plataformas", "Desktop", "Celular", "Navegador", "Limpar filtros", "produtos", "Nenhum produto correspondente", "Selecione um produto para ver as opções públicas verificadas.", "Ver estado da versão", "Prévia pública Testnet; confira as evidências antes de instalar."],
  ru: ["Экосистема и загрузки", "Изучите 26 продуктов YNX и найдите проверенный публичный веб-вход или пакеты Testnet.", "Поиск продуктов (Wallet, DEX, AI…)", "Все", "Выберите способ открытия или установки", "Открыть веб", "Версии и загрузки", "Проверенного публичного веб-входа или пакета пока нет.", "Доступные пакеты", "Для этой платформы нет проверенного пакета. Выберите другой вариант или проверьте выпуск.", "Сведения о выпуске и безопасности", "Все способы", "Веб", "Пакеты", "Недоступно", "Все платформы", "Компьютер", "Мобильные", "Браузер", "Сбросить фильтры", "продуктов", "Совпадений нет", "Выберите продукт для просмотра проверенных публичных вариантов.", "Статус выпуска", "Публичная версия Testnet; перед установкой проверьте доказательства выпуска."],
  ar: ["النظام والتنزيلات", "استكشف 26 منتجًا من YNX وابحث عن مدخل ويب عام أو حزمة Testnet موثّقة.", "ابحث عن منتج (Wallet أو DEX أو AI…)", "الكل", "اختر طريقة الفتح أو التثبيت", "افتح الويب", "الإصدارات والتنزيلات", "لا يوجد مدخل ويب عام أو حزمة موثّقة بعد.", "الحزم المتاحة", "لا توجد حزمة موثّقة لهذه المنصة. اختر خيارًا آخر أو راجع حالة الإصدار.", "تفاصيل الإصدار وتنبيهات السلامة", "كل الطرق", "الويب", "الحزم", "غير متاح", "كل المنصات", "الحاسوب", "الهاتف", "المتصفح", "امسح المرشحات", "منتج", "لا توجد منتجات مطابقة", "اختر منتجًا لعرض خياراته العامة الموثّقة.", "عرض حالة الإصدار", "معاينة عامة لشبكة الاختبار؛ تحقق من أدلة الإصدار قبل التثبيت."],
  id: ["Ekosistem dan unduhan", "Jelajahi 26 produk YNX dan temukan akses Web publik atau paket Testnet yang terverifikasi.", "Cari produk (Wallet, DEX, AI…)", "Semua", "Pilih cara membuka atau memasang", "Buka Web", "Versi dan unduhan", "Belum ada akses Web publik atau paket terverifikasi.", "Paket tersedia", "Tidak ada paket terverifikasi untuk platform ini. Gunakan opsi lain atau lihat status rilis.", "Detail rilis dan catatan keamanan", "Semua cara", "Web", "Paket", "Tidak tersedia", "Semua platform", "Desktop", "Seluler", "Browser", "Hapus filter", "produk", "Tidak ada produk yang cocok", "Pilih produk untuk melihat opsi publik terverifikasi.", "Lihat status rilis", "Pratinjau Testnet publik; periksa bukti rilis sebelum memasang."],
};

const keys = ["title", "lead", "search", "all", "choose", "openWeb", "versions", "noPublic", "packages", "platformUnavailable", "details", "allMethods", "web", "packagesMethod", "unavailable", "allPlatforms", "desktop", "mobile", "browser", "clear", "productCount", "empty", "selectHint", "viewStatus", "testnetNotice"];

export function getDownloadExperienceCopy(locale) {
  const values = copy[locale];
  if (!values || values.length !== keys.length) throw new Error(`Missing download experience translation: ${locale}`);
  return Object.fromEntries(keys.map((key, index) => [key, values[index]]));
}

export const DOWNLOAD_EXPERIENCE_LOCALES = Object.freeze(Object.keys(copy));

const categoryLabels = {
  en: ["Identity & community", "Money & commerce", "Build & operate", "AI, media & data", "Trust & infrastructure"],
  "zh-CN": ["身份与社区", "货币与商业", "构建与运维", "AI、媒体与数据", "信任与基础设施"],
  "zh-TW": ["身分與社群", "貨幣與商業", "建置與運維", "AI、媒體與資料", "信任與基礎設施"],
  ja: ["アイデンティティとコミュニティ", "決済と商取引", "開発と運用", "AI・メディア・データ", "信頼と基盤"],
  ko: ["신원 및 커뮤니티", "금융 및 상거래", "개발 및 운영", "AI·미디어·데이터", "신뢰 및 인프라"],
  es: ["Identidad y comunidad", "Dinero y comercio", "Desarrollo y operaciones", "IA, medios y datos", "Confianza e infraestructura"],
  fr: ["Identité et communauté", "Finance et commerce", "Développement et opérations", "IA, médias et données", "Confiance et infrastructure"],
  de: ["Identität und Community", "Geld und Handel", "Entwicklung und Betrieb", "KI, Medien und Daten", "Vertrauen und Infrastruktur"],
  pt: ["Identidade e comunidade", "Dinheiro e comércio", "Desenvolvimento e operações", "IA, mídia e dados", "Confiança e infraestrutura"],
  ru: ["Личность и сообщество", "Финансы и торговля", "Разработка и эксплуатация", "ИИ, медиа и данные", "Доверие и инфраструктура"],
  ar: ["الهوية والمجتمع", "المال والتجارة", "البناء والتشغيل", "الذكاء الاصطناعي والإعلام والبيانات", "الثقة والبنية التحتية"],
  id: ["Identitas dan komunitas", "Keuangan dan perdagangan", "Bangun dan operasikan", "AI, media, dan data", "Kepercayaan dan infrastruktur"],
};

export function getDownloadCategoryLabels(locale) {
  const labels = categoryLabels[locale];
  if (!labels || labels.length !== 5) throw new Error(`Missing download category labels: ${locale}`);
  return labels;
}
