export const DOWNLOAD_TILE_KEYS = Object.freeze(["wallet", "social", "mail", "calendar", "pay", "merchantConsole", "card", "exchange", "quant", "shop", "sellerConsole", "finance", "dex", "developer", "explorer", "monitor", "docs", "browser", "search", "ai", "music", "video", "creatorStudio", "cloud", "trust", "resource"]);

// Short directory descriptions are purpose labels, not release or capability claims.
// Public actions and availability always come from the release registry.
const summaries = {
  en: ["Manage assets, connect apps", "Connect with the community", "Private communication", "Plan events and time", "Testnet payment records", "Merchant operations", "Testnet card simulation", "Exchange research", "Strategy research", "Browse demo goods", "Store operations", "Personal finance workspace", "Read-only market preview", "Build on YNX", "Explore chain records", "Network status", "Document workspace", "Web3 browser project", "Discover public records", "AI-assisted workspace", "Rights-aware music", "Discover test videos", "Creator workspace", "File workspace", "Evidence and appeals", "Resource market preview"],
  "zh-CN": ["管理资产，连接应用", "连接社区与世界", "去中心化安全通信", "高效管理日程与活动", "便捷的链上支付体验", "面向商家的支付管理", "测试网卡片模拟", "数字资产交易研究", "量化工具与策略研究", "发现和购买演示商品", "商家店铺与订单管理", "多元化的个人金融服务", "只读市场预览", "构建应用，连接 YNX", "浏览链上数据与交易", "网络与节点监控", "文档协作工作区", "Web3 浏览器项目", "搜索生态公开内容", "AI 辅助工作区", "音乐发现与创作", "发现与分享测试视频", "一站式创作工作区", "去中心化文件工作区", "安全、证据与申诉", "资源报价与市场预览"],
  "zh-TW": ["管理資產，連接應用", "連接社群與世界", "去中心化安全通訊", "有效管理行程與活動", "便捷的鏈上支付體驗", "商家支付管理", "測試網卡片模擬", "數位資產交易研究", "量化工具與策略研究", "探索與購買示範商品", "商家店鋪與訂單管理", "多元個人金融服務", "唯讀市場預覽", "建構應用，連接 YNX", "瀏覽鏈上資料與交易", "網路與節點監控", "文件協作工作區", "Web3 瀏覽器專案", "搜尋生態公開內容", "AI 輔助工作區", "音樂探索與創作", "探索與分享測試影片", "一站式創作工作區", "去中心化檔案工作區", "安全、證據與申訴", "資源報價與市場預覽"],
  ja: ["資産管理とアプリ接続", "コミュニティにつながる", "安全な通信", "予定とイベントの管理", "Testnet決済記録", "加盟店業務", "Testnetカードの模擬", "取引の調査", "戦略の調査", "デモ商品を探す", "店舗と注文の管理", "個人向け金融ワークスペース", "読み取り専用の市場", "YNX上で開発", "チェーン記録を閲覧", "ネットワーク状態", "文書ワークスペース", "Web3ブラウザー計画", "公開記録を探す", "AI支援ワークスペース", "権利を尊重する音楽", "テスト動画を探す", "クリエイター向け", "ファイルワークスペース", "証拠と異議申し立て", "リソース市場のプレビュー"],
  ko: ["자산 관리와 앱 연결", "커뮤니티 연결", "안전한 소통", "일정과 행사 관리", "테스트넷 결제 기록", "판매자 운영", "테스트넷 카드 모의", "거래 연구", "전략 연구", "데모 상품 탐색", "매장과 주문 관리", "개인 금융 공간", "읽기 전용 시장 미리보기", "YNX에서 개발", "체인 기록 탐색", "네트워크 상태", "문서 작업 공간", "Web3 브라우저 프로젝트", "공개 기록 검색", "AI 보조 작업 공간", "권리 중심 음악", "테스트 영상 탐색", "크리에이터 작업 공간", "파일 작업 공간", "증거와 이의 제기", "자원 시장 미리보기"],
  es: ["Gestiona activos y conecta apps", "Conecta con la comunidad", "Comunicación segura", "Agenda y eventos", "Registros de pago Testnet", "Operaciones comerciales", "Simulación de tarjeta Testnet", "Investigación de mercados", "Investigación de estrategias", "Explora productos de prueba", "Tiendas y pedidos", "Finanzas personales", "Mercado de solo lectura", "Desarrolla en YNX", "Explora registros de cadena", "Estado de la red", "Espacio de documentos", "Proyecto de navegador Web3", "Busca registros públicos", "Espacio asistido por IA", "Música con derechos", "Descubre vídeos de prueba", "Espacio para creadores", "Espacio de archivos", "Pruebas y apelaciones", "Vista del mercado de recursos"],
  fr: ["Gérer les actifs et les apps", "Rejoindre la communauté", "Communication sécurisée", "Agenda et événements", "Reçus de paiement Testnet", "Opérations marchandes", "Simulation de carte Testnet", "Recherche sur les échanges", "Recherche de stratégies", "Explorer des produits démo", "Boutique et commandes", "Finances personnelles", "Marché en lecture seule", "Créer sur YNX", "Explorer la chaîne", "État du réseau", "Espace documentaire", "Projet de navigateur Web3", "Chercher les données publiques", "Espace assisté par IA", "Musique et droits", "Découvrir les vidéos test", "Espace créateur", "Espace de fichiers", "Preuves et recours", "Aperçu du marché des ressources"],
  de: ["Vermögen und Apps verbinden", "Community verbinden", "Sichere Kommunikation", "Termine und Ereignisse", "Testnet-Zahlungsbelege", "Händlerbetrieb", "Testnet-Kartensimulation", "Börsenanalyse", "Strategieforschung", "Demo-Waren entdecken", "Shop und Bestellungen", "Persönliche Finanzen", "Markt nur zum Lesen", "Auf YNX entwickeln", "Chain-Daten erkunden", "Netzwerkstatus", "Dokumentenbereich", "Web3-Browserprojekt", "Öffentliche Daten suchen", "KI-gestützter Bereich", "Musik und Rechte", "Testvideos entdecken", "Creator-Bereich", "Dateibereich", "Nachweise und Einsprüche", "Ressourcenmarkt-Vorschau"],
  pt: ["Gerencie ativos e conecte apps", "Conecte a comunidade", "Comunicação segura", "Agenda e eventos", "Registros de pagamento Testnet", "Operações de comerciantes", "Simulação de cartão Testnet", "Pesquisa de câmbio", "Pesquisa de estratégias", "Explore produtos demo", "Loja e pedidos", "Finanças pessoais", "Mercado somente leitura", "Desenvolva na YNX", "Explore dados da cadeia", "Estado da rede", "Espaço de documentos", "Projeto de navegador Web3", "Busque registros públicos", "Espaço com assistência de IA", "Música e direitos", "Descubra vídeos de teste", "Espaço para criadores", "Espaço de arquivos", "Provas e recursos", "Prévia do mercado de recursos"],
  ru: ["Активы и подключение приложений", "Связь с сообществом", "Защищённое общение", "Расписание и события", "Платёжные записи Testnet", "Работа продавца", "Симуляция карты Testnet", "Исследование биржи", "Исследование стратегий", "Демо-товары", "Магазин и заказы", "Личные финансы", "Рынок только для чтения", "Разработка на YNX", "Записи блокчейна", "Состояние сети", "Документы", "Проект браузера Web3", "Поиск открытых записей", "Работа с помощью ИИ", "Музыка с учётом прав", "Тестовые видео", "Инструменты автора", "Работа с файлами", "Доказательства и жалобы", "Обзор рынка ресурсов"],
  ar: ["إدارة الأصول وربط التطبيقات", "تواصل مع المجتمع", "اتصالات آمنة", "تنظيم المواعيد والفعاليات", "سجلات مدفوعات الاختبار", "إدارة أعمال التجار", "محاكاة بطاقة الاختبار", "بحث التداول", "بحث الاستراتيجيات", "استكشاف سلع تجريبية", "إدارة المتجر والطلبات", "مساحة التمويل الشخصي", "معاينة سوق للقراءة فقط", "طوّر على YNX", "استكشف سجلات السلسلة", "حالة الشبكة", "مساحة المستندات", "مشروع متصفح Web3", "بحث السجلات العامة", "مساحة بمساعدة الذكاء الاصطناعي", "موسيقى تراعي الحقوق", "استكشف فيديوهات اختبارية", "مساحة المبدعين", "مساحة الملفات", "الأدلة والاستئنافات", "معاينة سوق الموارد"],
  id: ["Kelola aset dan hubungkan app", "Terhubung dengan komunitas", "Komunikasi aman", "Jadwal dan acara", "Catatan pembayaran Testnet", "Operasi pedagang", "Simulasi kartu Testnet", "Riset bursa", "Riset strategi", "Jelajahi produk demo", "Toko dan pesanan", "Keuangan pribadi", "Pratinjau pasar baca-saja", "Bangun di YNX", "Jelajahi catatan rantai", "Status jaringan", "Ruang dokumen", "Proyek browser Web3", "Cari catatan publik", "Ruang kerja berbantu AI", "Musik yang menghormati hak", "Jelajahi video uji", "Ruang kreator", "Ruang berkas", "Bukti dan banding", "Pratinjau pasar sumber daya"],
};

export function getDownloadTileSummary(locale, key) {
  const index = DOWNLOAD_TILE_KEYS.indexOf(key);
  if (index < 0) return null;
  const values = summaries[locale];
  if (!values || values.length !== DOWNLOAD_TILE_KEYS.length) throw new Error(`Missing download tile summaries: ${locale}`);
  return values[index];
}

export const DOWNLOAD_TILE_LOCALES = Object.freeze(Object.keys(summaries));
