export const COMMUNITY_LINKS = Object.freeze({
  discord: "https://discord.gg/t8KpAF2KE",
  youtube: "https://www.youtube.com/@YNX-Chain",
  x: "https://x.com/YNXChain",
  github: "https://github.com/JiahaoAlbus/YNX-Chain",
});

const entries = {
  en: ["Start here", "Block explorer", "The YNX community", "Build something. Together.", "Meet the community, follow the project and share what you are building.", "Join Discord", "Talk with other users and builders. Share questions, ideas and feedback.", "Watch on YouTube", "Explore the YNX channel for project videos and updates.", "Follow project updates", "Explore the source and contribute", "A Layer 1 connecting people, apps and AI agents. Start exploring the YNX public Testnet.", "Start with a read-only example, then explore network guides, SDKs and the supported development paths."],
  "zh-CN": ["开始手册", "区块浏览器", "YNX 社区", "一起，让想法发生。", "认识社区伙伴，关注项目进展，分享你正在构建的东西。", "加入 Discord", "与用户和开发者交流，分享问题、想法与反馈。", "前往 YouTube", "访问 YNX 官方频道，了解项目视频与更新。", "关注项目动态", "阅读源码，参与贡献", "连接人、应用与 AI 智能体的 Layer 1。从这里开始探索 YNX 公开测试网。", "从一个只读示例开始，再了解网络指南、SDK 与当前支持的开发方式。"],
  "zh-TW": ["入門手冊", "區塊瀏覽器", "YNX 社群", "一起，讓想法實現。", "認識社群夥伴，關注專案進展，分享你正在打造的事物。", "加入 Discord", "與使用者和開發者交流，分享問題、想法與回饋。", "前往 YouTube", "造訪 YNX 官方頻道，了解專案影片與更新。", "關注專案動態", "閱讀原始碼，參與貢獻", "連結人、應用程式與 AI 智慧代理的 Layer 1。從這裡開始探索 YNX 公開測試網。", "從唯讀範例開始，再了解網路指南、SDK 與目前支援的開發方式。"],
  ja: ["入門ガイド", "ブロックエクスプローラー", "YNX コミュニティ", "アイデアを、一緒に形に。", "仲間と出会い、プロジェクトの進捗を追い、制作中のものを共有しましょう。", "Discord に参加", "ユーザーや開発者と質問、アイデア、フィードバックを共有。", "YouTube を見る", "YNX 公式チャンネルで動画や最新情報をご覧ください。", "最新情報をフォロー", "ソースを読んで貢献する", "人、アプリ、AI エージェントをつなぐ Layer 1。YNX 公開テストネットを探索しましょう。", "読み取り専用の例から始め、ネットワークガイド、SDK、対応する開発方法を学びましょう。"],
  ko: ["시작 안내서", "블록 탐색기", "YNX 커뮤니티", "함께 아이디어를 실현하세요.", "커뮤니티를 만나고 프로젝트 소식을 확인하며 만들고 있는 것을 공유하세요.", "Discord 참여", "사용자 및 개발자와 질문, 아이디어, 의견을 나누세요.", "YouTube 보기", "YNX 공식 채널에서 프로젝트 영상과 소식을 확인하세요.", "프로젝트 소식 팔로우", "소스를 살펴보고 기여하기", "사람, 앱, AI 에이전트를 연결하는 Layer 1. YNX 공개 테스트넷을 탐색하세요.", "읽기 전용 예제로 시작하여 네트워크 안내서, SDK, 지원되는 개발 방법을 알아보세요."],
  es: ["Guía de inicio", "Explorador de bloques", "La comunidad YNX", "Creemos algo. Juntos.", "Conoce a la comunidad, sigue el proyecto y comparte lo que estás creando.", "Unirse a Discord", "Comparte preguntas, ideas y comentarios con usuarios y desarrolladores.", "Ver en YouTube", "Visita el canal de YNX para ver vídeos y novedades del proyecto.", "Seguir las novedades", "Explorar el código y contribuir", "Una capa 1 que conecta personas, aplicaciones y agentes de IA. Explora la Testnet pública de YNX.", "Empieza con un ejemplo de solo lectura y descubre las guías de red, los SDK y las opciones de desarrollo disponibles."],
  fr: ["Guide de démarrage", "Explorateur de blocs", "La communauté YNX", "Créons quelque chose. Ensemble.", "Rencontrez la communauté, suivez le projet et partagez vos créations.", "Rejoindre Discord", "Échangez questions, idées et retours avec les utilisateurs et les développeurs.", "Voir sur YouTube", "Retrouvez les vidéos et les actualités du projet sur la chaîne YNX.", "Suivre les actualités", "Explorer le code et contribuer", "Une couche 1 reliant les personnes, les applications et les agents IA. Explorez le Testnet public YNX.", "Commencez par un exemple en lecture seule, puis découvrez les guides réseau, les SDK et les possibilités de développement prises en charge."],
  de: ["Erste Schritte", "Block-Explorer", "Die YNX-Community", "Gemeinsam Ideen verwirklichen.", "Lerne die Community kennen, verfolge das Projekt und teile deine Arbeit.", "Discord beitreten", "Tausche Fragen, Ideen und Feedback mit Nutzern und Entwicklern aus.", "Auf YouTube ansehen", "Entdecke Projektvideos und Neuigkeiten auf dem YNX-Kanal.", "Projektneuigkeiten folgen", "Quellcode entdecken und mitwirken", "Ein Layer 1 für Menschen, Apps und KI-Agenten. Entdecke das öffentliche YNX-Testnet.", "Beginne mit einem Beispiel für Lesezugriffe und entdecke Netzwerkanleitungen, SDKs und unterstützte Entwicklungswege."],
  pt: ["Guia de primeiros passos", "Explorador de blocos", "A comunidade YNX", "Vamos criar. Juntos.", "Conheça a comunidade, acompanhe o projeto e compartilhe o que está criando.", "Entrar no Discord", "Troque perguntas, ideias e opiniões com usuários e desenvolvedores.", "Assistir no YouTube", "Visite o canal YNX para vídeos e novidades do projeto.", "Acompanhar as novidades", "Explorar o código e contribuir", "Uma camada 1 que conecta pessoas, aplicativos e agentes de IA. Explore a Testnet pública YNX.", "Comece com um exemplo somente de leitura e descubra os guias da rede, SDKs e caminhos de desenvolvimento disponíveis."],
  ru: ["Руководство для начала", "Обозреватель блоков", "Сообщество YNX", "Создавайте вместе.", "Знакомьтесь с сообществом, следите за проектом и делитесь своими разработками.", "Присоединиться к Discord", "Обсуждайте вопросы, идеи и отзывы с пользователями и разработчиками.", "Смотреть на YouTube", "Видео и новости проекта на канале YNX.", "Следить за новостями", "Изучать код и вносить вклад", "Layer 1, объединяющий людей, приложения и ИИ-агентов. Исследуйте публичную тестовую сеть YNX.", "Начните с примера чтения данных, затем изучите руководства по сети, SDK и поддерживаемые способы разработки."],
  ar: ["دليل البداية", "مستكشف الكتل", "مجتمع YNX", "لنحوّل الأفكار إلى واقع معًا.", "تعرّف إلى المجتمع وتابع المشروع وشارك ما تبنيه.", "انضم إلى Discord", "تبادل الأسئلة والأفكار والملاحظات مع المستخدمين والمطورين.", "شاهد على YouTube", "تعرّف إلى فيديوهات المشروع وأخباره على قناة YNX.", "تابع أخبار المشروع", "استكشف الشفرة وساهم", "طبقة أولى تربط الأشخاص والتطبيقات ووكلاء الذكاء الاصطناعي. ابدأ باستكشاف شبكة YNX التجريبية العامة.", "ابدأ بمثال للقراءة فقط، ثم استكشف أدلة الشبكة وحزم SDK ومسارات التطوير المدعومة."],
  id: ["Panduan memulai", "Penjelajah blok", "Komunitas YNX", "Wujudkan ide. Bersama.", "Kenali komunitas, ikuti perkembangan proyek, dan bagikan karya yang sedang Anda bangun.", "Gabung Discord", "Bagikan pertanyaan, ide, dan masukan bersama pengguna serta pengembang.", "Tonton di YouTube", "Kunjungi kanal YNX untuk video dan kabar proyek.", "Ikuti kabar proyek", "Jelajahi kode dan berkontribusi", "Layer 1 yang menghubungkan manusia, aplikasi, dan agen AI. Mulai jelajahi Testnet publik YNX.", "Mulai dengan contoh baca saja, lalu pelajari panduan jaringan, SDK, dan alur pengembangan yang didukung."],
};
const keys = ["manual", "explorer", "eyebrow", "title", "lead", "discordAction", "discordDescription", "youtubeAction", "youtubeDescription", "xDescription", "githubDescription", "heroLead", "developerLead"];
export function getHomeEntryCopy(locale) {
  return Object.fromEntries(keys.map((key, i) => [key, (entries[locale] || entries.en)[i]]));
}
