export const HOME_REDESIGN_COPY = {
  en: {
    heroTitle: "One network. New possibilities.",
    heroLead: "An EVM-compatible Layer 1 for people, apps and AI agents. Explore the YNX public Testnet.",
    download: "Download Wallet",
    explore: "Explore the ecosystem",
    testnetNote: "Public Testnet · Test assets have no monetary value.",
    ecosystemEyebrow: "The YNX ecosystem",
    ecosystemTitle: "Your way into YNX.",
    ecosystemLead: "Start with a wallet, explore the network or find an app to try.",
    ecosystemAll: "All applications",
    ecosystemItems: [
      { title: "YNX Wallet", description: "Find wallet downloads and installation guides for your platform.", action: "Download Wallet" },
      { title: "Explorer", description: "Explore blocks, transactions and addresses on the public Testnet.", action: "Open Explorer" },
      { title: "Faucet", description: "Request test YNXT for network fees and app experiments.", action: "Get test YNXT" },
      { title: "Ecosystem apps", description: "Discover YNX apps, their access options and current Testnet status.", action: "Browse apps" },
    ],
    developerEyebrow: "For developers",
    developerTitle: "Build on what you know.",
    developerLead: "Bring your EVM tools to YNX. Start with the network guide, developer docs and SDK.",
    developerAction: "Start building",
    networkDetails: "Network details",
    networkLead: "Live data and network configuration, when available.",
    addressDetails: "Address tools",
    readinessDetails: "Testnet progress and limits",
    readinessScopeTitle: "Public Testnet scope",
    readinessScope: ["Network 6423 and test asset YNXT", "Network and transaction data", "Ecosystem entries and current product status", "Developer docs, SDK and installation guides"],
    resourcesTitle: "Find your next step.",
    menuLabel: "More",
    networkAction: "Network",
    guide: "Installation guide",
    productAction: "View details",
    productReference: "Testnet reference",
    productReachable: "Service reachable",
    endpointCopy: ["Copy","Copied","Copy unavailable"],
    resourceItems: [
      { label: "Explorer", detail: "Blocks, transactions and validators" },
      { label: "Network Monitor", detail: "Network and service status" },
      { label: "Faucet", detail: "Request test YNXT" },
      { label: "Developer docs", detail: "Guides, RPC and SDK integration" },
      { label: "Chain source", detail: "Network runtime and verification code" },
      { label: "Ecosystem apps", detail: "Apps and their current Testnet status" },
    ],
  },
  "zh-CN": {
    heroTitle: "一个网络，连接更多可能。",
    heroLead: "兼容 EVM 的 Layer 1，连接人、应用与 AI 智能体。即刻探索 YNX 公开测试网。",
    download: "下载 Wallet",
    explore: "探索生态",
    testnetNote: "公开测试网 · 测试资产不具有货币价值。",
    ecosystemEyebrow: "YNX 生态",
    ecosystemTitle: "从这里，走进 YNX。",
    ecosystemLead: "从钱包开始，了解网络，或寻找想体验的应用。",
    ecosystemAll: "全部应用",
    ecosystemItems: [
      { title: "YNX Wallet", description: "查找适合你设备的钱包安装包与安装指南。", action: "下载 Wallet" },
      { title: "区块浏览器", description: "查看公开测试网的区块、交易与地址。", action: "打开浏览器" },
      { title: "水龙头", description: "申请测试 YNXT，用于网络手续费与应用体验。", action: "领取测试 YNXT" },
      { title: "生态应用", description: "发现 YNX 应用，了解访问方式与当前测试网进展。", action: "浏览应用" },
    ],
    developerEyebrow: "开发者",
    developerTitle: "用熟悉的工具，构建新可能。",
    developerLead: "将你的 EVM 工具带到 YNX。从网络指南、开发文档与 SDK 开始。",
    developerAction: "开始构建",
    networkDetails: "网络详情",
    networkLead: "查看可用的实时数据与网络配置。",
    addressDetails: "地址工具",
    readinessDetails: "测试网进展与限制",
    readinessScopeTitle: "公开测试网范围",
    readinessScope: ["网络 6423 与测试资产 YNXT", "网络与交易数据", "生态入口与当前产品状态", "开发者文档、SDK 与安装指南"],
    resourcesTitle: "找到你的下一步。",
    menuLabel: "更多",
    networkAction: "网络",
    guide: "安装指南",
    productAction: "查看详情",
    productReference: "测试网资料",
    productReachable: "服务可访问",
    endpointCopy: ["复制","已复制","暂时无法复制"],
    resourceItems: [
      { label: "区块浏览器", detail: "区块、交易与验证者" },
      { label: "网络监控", detail: "网络与服务状态" },
      { label: "水龙头", detail: "申请测试 YNXT" },
      { label: "开发者文档", detail: "开发指南、RPC 与 SDK 集成" },
      { label: "链源码", detail: "网络运行与验证代码" },
      { label: "生态应用", detail: "应用与当前测试网进展" },
    ],
  },
  "zh-TW": {
    heroTitle: "一個網路，連結更多可能。",
    heroLead: "相容 EVM 的 Layer 1，連結人、應用程式與 AI 智慧代理。立即探索 YNX 公開測試網。",
    download: "下載 Wallet",
    explore: "探索生態系",
    testnetNote: "公開測試網 · 測試資產不具有貨幣價值。",
    ecosystemEyebrow: "YNX 生態系",
    ecosystemTitle: "從這裡，走進 YNX。",
    ecosystemLead: "從錢包開始，了解網路，或尋找想體驗的應用程式。",
    ecosystemAll: "所有應用程式",
    ecosystemItems: [
      { title: "YNX Wallet", description: "尋找適合你裝置的錢包安裝檔與安裝指南。", action: "下載 Wallet" },
      { title: "區塊瀏覽器", description: "查看公開測試網的區塊、交易與地址。", action: "開啟瀏覽器" },
      { title: "水龍頭", description: "申請測試 YNXT，用於網路手續費與應用程式體驗。", action: "領取測試 YNXT" },
      { title: "生態系應用程式", description: "探索 YNX 應用程式，了解存取方式與目前測試網進展。", action: "瀏覽應用程式" },
    ],
    developerEyebrow: "開發者",
    developerTitle: "用熟悉的工具，打造新可能。",
    developerLead: "將你的 EVM 工具帶到 YNX。從網路指南、開發文件與 SDK 開始。",
    developerAction: "開始開發",
    networkDetails: "網路詳細資訊",
    networkLead: "查看可用的即時資料與網路設定。",
    addressDetails: "地址工具",
    readinessDetails: "測試網進展與限制",
    readinessScopeTitle: "公開測試網範圍",
    readinessScope: ["網路 6423 與測試資產 YNXT", "網路與交易資料", "生態系入口與目前產品狀態", "開發者文件、SDK 與安裝指南"],
    resourcesTitle: "找到你的下一步。",
    menuLabel: "更多",
    networkAction: "網路",
    guide: "安裝指南",
    productAction: "查看詳細資訊",
    productReference: "測試網資料",
    productReachable: "服務可存取",
    endpointCopy: ["複製","已複製","暫時無法複製"],
    resourceItems: [
      { label: "區塊瀏覽器", detail: "區塊、交易與驗證者" },
      { label: "網路監控", detail: "網路與服務狀態" },
      { label: "水龍頭", detail: "申請測試 YNXT" },
      { label: "開發者文件", detail: "開發指南、RPC 與 SDK 整合" },
      { label: "鏈原始碼", detail: "網路執行與驗證程式碼" },
      { label: "生態系應用程式", detail: "應用程式與目前測試網進展" },
    ],
  },
  ja: {
    heroTitle: "ひとつのネットワークから、新たな可能性へ。",
    heroLead: "人、アプリ、AI エージェントのための EVM 互換 Layer 1。YNX の公開テストネットを探索しましょう。",
    download: "Wallet をダウンロード",
    explore: "エコシステムを見る",
    testnetNote: "公開テストネット · テスト資産に金銭的価値はありません。",
    ecosystemEyebrow: "YNX エコシステム",
    ecosystemTitle: "ここから、YNX をはじめよう。",
    ecosystemLead: "ウォレットの入手、ネットワークの探索、アプリの体験。気になるところから始められます。",
    ecosystemAll: "すべてのアプリ",
    ecosystemItems: [
      { title: "YNX Wallet", description: "お使いの環境に合うウォレットとインストールガイドを探せます。", action: "Wallet をダウンロード" },
      { title: "Explorer", description: "公開テストネットのブロック、トランザクション、アドレスを確認できます。", action: "Explorer を開く" },
      { title: "Faucet", description: "ネットワーク手数料やアプリの試用に使うテスト YNXT を申請できます。", action: "テスト YNXT を取得" },
      { title: "エコシステムのアプリ", description: "YNX のアプリとアクセス方法、現在のテストネット対応状況を確認できます。", action: "アプリを見る" },
    ],
    developerEyebrow: "開発者向け",
    developerTitle: "使い慣れたツールで、新しいものを。",
    developerLead: "EVM ツールを YNX でも。ネットワークガイド、開発ドキュメント、SDK から始めましょう。",
    developerAction: "開発をはじめる",
    networkDetails: "ネットワーク詳細",
    networkLead: "取得可能な最新データとネットワーク設定を確認できます。",
    addressDetails: "アドレスツール",
    readinessDetails: "テストネットの進捗と制限",
    readinessScopeTitle: "公開テストネットの範囲",
    readinessScope: ["ネットワーク 6423 とテスト資産 YNXT", "ネットワークとトランザクションのデータ", "エコシステムの入口と各製品の現在の状況", "開発ドキュメント、SDK、インストールガイド"],
    resourcesTitle: "次の一歩を見つけよう。",
    menuLabel: "その他",
    networkAction: "ネットワーク",
    guide: "インストールガイド",
    productAction: "詳細を見る",
    productReference: "テストネット資料",
    productReachable: "サービスにアクセス可能",
    endpointCopy: ["コピー","コピーしました","コピーできません"],
    resourceItems: [
      { label: "Explorer", detail: "ブロック、トランザクション、バリデータ" },
      { label: "ネットワークモニター", detail: "ネットワークとサービスの状況" },
      { label: "Faucet", detail: "テスト YNXT の申請" },
      { label: "開発ドキュメント", detail: "ガイド、RPC、SDK の導入" },
      { label: "チェーンのソースコード", detail: "ネットワークの実行・検証コード" },
      { label: "エコシステムのアプリ", detail: "アプリと現在のテストネット対応状況" },
    ],
  },
  ko: {
    heroTitle: "하나의 네트워크, 새로운 가능성.",
    heroLead: "사람, 앱, AI 에이전트를 위한 EVM 호환 Layer 1. YNX 공개 테스트넷을 만나보세요.",
    download: "Wallet 다운로드",
    explore: "생태계 둘러보기",
    testnetNote: "공개 테스트넷 · 테스트 자산에는 금전적 가치가 없습니다.",
    ecosystemEyebrow: "YNX 생태계",
    ecosystemTitle: "여기서 YNX를 시작하세요.",
    ecosystemLead: "지갑으로 시작하거나, 네트워크를 살펴보거나, 경험해 보고 싶은 앱을 찾아보세요.",
    ecosystemAll: "모든 앱",
    ecosystemItems: [
      { title: "YNX Wallet", description: "내 기기에 맞는 지갑 다운로드와 설치 가이드를 확인하세요.", action: "Wallet 다운로드" },
      { title: "블록 탐색기", description: "공개 테스트넷의 블록, 트랜잭션, 주소를 살펴보세요.", action: "탐색기 열기" },
      { title: "Faucet", description: "네트워크 수수료와 앱 테스트에 사용할 테스트 YNXT를 신청하세요.", action: "테스트 YNXT 받기" },
      { title: "생태계 앱", description: "YNX 앱의 접속 방법과 현재 테스트넷 지원 현황을 확인하세요.", action: "앱 둘러보기" },
    ],
    developerEyebrow: "개발자를 위해",
    developerTitle: "익숙한 도구로 새로운 것을 만드세요.",
    developerLead: "YNX에서도 EVM 도구를 활용하세요. 네트워크 가이드, 개발 문서, SDK로 시작할 수 있습니다.",
    developerAction: "개발 시작하기",
    networkDetails: "네트워크 상세 정보",
    networkLead: "제공 가능한 실시간 데이터와 네트워크 설정을 확인하세요.",
    addressDetails: "주소 도구",
    readinessDetails: "테스트넷 진행 상황과 제한",
    readinessScopeTitle: "공개 테스트넷 범위",
    readinessScope: ["네트워크 6423과 테스트 자산 YNXT", "네트워크 및 트랜잭션 데이터", "생태계 접속 경로와 현재 제품 상태", "개발 문서, SDK, 설치 가이드"],
    resourcesTitle: "다음 단계를 찾아보세요.",
    menuLabel: "더 보기",
    networkAction: "네트워크",
    guide: "설치 가이드",
    productAction: "자세히 보기",
    productReference: "테스트넷 자료",
    productReachable: "서비스 접속 가능",
    endpointCopy: ["복사","복사됨","복사할 수 없음"],
    resourceItems: [
      { label: "블록 탐색기", detail: "블록, 트랜잭션, 검증자" },
      { label: "네트워크 모니터", detail: "네트워크와 서비스 상태" },
      { label: "Faucet", detail: "테스트 YNXT 신청" },
      { label: "개발 문서", detail: "가이드, RPC, SDK 연동" },
      { label: "체인 소스 코드", detail: "네트워크 실행 및 검증 코드" },
      { label: "생태계 앱", detail: "앱과 현재 테스트넷 지원 현황" },
    ],
  },
  es: {
    heroTitle: "Una red. Nuevas posibilidades.",
    heroLead: "Una Layer 1 compatible con EVM para personas, apps y agentes de IA. Explora la testnet pública de YNX.",
    download: "Descargar Wallet",
    explore: "Explorar el ecosistema",
    testnetNote: "Testnet pública · Los activos de prueba no tienen valor monetario.",
    ecosystemEyebrow: "El ecosistema YNX",
    ecosystemTitle: "Tu punto de partida en YNX.",
    ecosystemLead: "Empieza con un monedero, explora la red o encuentra una app para probar.",
    ecosystemAll: "Todas las aplicaciones",
    ecosystemItems: [
      { title: "YNX Wallet", description: "Encuentra descargas del monedero y guías de instalación para tu plataforma.", action: "Descargar Wallet" },
      { title: "Explorador", description: "Consulta bloques, transacciones y direcciones de la testnet pública.", action: "Abrir el explorador" },
      { title: "Faucet", description: "Solicita YNXT de prueba para las comisiones de red y para probar apps.", action: "Obtener YNXT de prueba" },
      { title: "Apps del ecosistema", description: "Descubre las apps de YNX, cómo acceder y su estado actual en la testnet.", action: "Ver las apps" },
    ],
    developerEyebrow: "Para desarrolladores",
    developerTitle: "Crea con lo que ya conoces.",
    developerLead: "Usa tus herramientas EVM en YNX. Empieza con la guía de red, la documentación y el SDK.",
    developerAction: "Empezar a desarrollar",
    networkDetails: "Detalles de la red",
    networkLead: "Datos en vivo y configuración de red, cuando estén disponibles.",
    addressDetails: "Herramientas de direcciones",
    readinessDetails: "Avances y límites de la testnet",
    readinessScopeTitle: "Alcance de la testnet pública",
    readinessScope: ["Red 6423 y activo de prueba YNXT", "Datos de red y transacciones", "Accesos al ecosistema y estado actual de los productos", "Documentación, SDK y guías de instalación"],
    resourcesTitle: "Encuentra tu próximo paso.",
    menuLabel: "Más",
    networkAction: "Red",
    guide: "Guía de instalación",
    productAction: "Ver detalles",
    productReference: "Referencia de la testnet",
    productReachable: "Servicio accesible",
    endpointCopy: ["Copiar","Copiado","No se puede copiar"],
    resourceItems: [
      { label: "Explorador", detail: "Bloques, transacciones y validadores" },
      { label: "Monitor de red", detail: "Estado de la red y los servicios" },
      { label: "Faucet", detail: "Solicita YNXT de prueba" },
      { label: "Documentación", detail: "Guías e integración de RPC y SDK" },
      { label: "Código de la cadena", detail: "Código de ejecución y verificación de la red" },
      { label: "Apps del ecosistema", detail: "Apps y su estado actual en la testnet" },
    ],
  },
  fr: {
    heroTitle: "Un réseau. De nouvelles possibilités.",
    heroLead: "Une Layer 1 compatible EVM pour les personnes, les apps et les agents IA. Explorez le testnet public YNX.",
    download: "Télécharger Wallet",
    explore: "Explorer l’écosystème",
    testnetNote: "Testnet public · Les actifs de test n’ont aucune valeur monétaire.",
    ecosystemEyebrow: "L’écosystème YNX",
    ecosystemTitle: "Votre point de départ sur YNX.",
    ecosystemLead: "Commencez par un portefeuille, explorez le réseau ou trouvez une app à essayer.",
    ecosystemAll: "Toutes les applications",
    ecosystemItems: [
      { title: "YNX Wallet", description: "Retrouvez les téléchargements du portefeuille et les guides d’installation pour votre plateforme.", action: "Télécharger Wallet" },
      { title: "Explorateur", description: "Consultez les blocs, les transactions et les adresses du testnet public.", action: "Ouvrir l’explorateur" },
      { title: "Faucet", description: "Demandez des YNXT de test pour les frais de réseau et vos essais d’apps.", action: "Obtenir des YNXT de test" },
      { title: "Apps de l’écosystème", description: "Découvrez les apps YNX, leurs accès et leur état actuel sur le testnet.", action: "Voir les apps" },
    ],
    developerEyebrow: "Pour les développeurs",
    developerTitle: "Créez avec vos outils familiers.",
    developerLead: "Utilisez vos outils EVM sur YNX. Commencez par le guide réseau, la documentation et le SDK.",
    developerAction: "Commencer à développer",
    networkDetails: "Détails du réseau",
    networkLead: "Données en direct et configuration réseau, selon leur disponibilité.",
    addressDetails: "Outils d’adresses",
    readinessDetails: "Avancées et limites du testnet",
    readinessScopeTitle: "Périmètre du testnet public",
    readinessScope: ["Réseau 6423 et actif de test YNXT", "Données du réseau et des transactions", "Accès à l’écosystème et état actuel des produits", "Documentation, SDK et guides d’installation"],
    resourcesTitle: "Trouvez votre prochaine étape.",
    menuLabel: "Plus",
    networkAction: "Réseau",
    guide: "Guide d’installation",
    productAction: "Voir les détails",
    productReference: "Référence du testnet",
    productReachable: "Service accessible",
    endpointCopy: ["Copier","Copié","Copie indisponible"],
    resourceItems: [
      { label: "Explorateur", detail: "Blocs, transactions et validateurs" },
      { label: "Moniteur réseau", detail: "État du réseau et des services" },
      { label: "Faucet", detail: "Demander des YNXT de test" },
      { label: "Documentation", detail: "Guides et intégration RPC et SDK" },
      { label: "Code de la chaîne", detail: "Code d’exécution et de vérification du réseau" },
      { label: "Apps de l’écosystème", detail: "Apps et leur état actuel sur le testnet" },
    ],
  },
  de: {
    heroTitle: "Ein Netzwerk. Neue Möglichkeiten.",
    heroLead: "Eine EVM-kompatible Layer 1 für Menschen, Apps und KI-Agenten. Entdecke das öffentliche YNX-Testnet.",
    download: "Wallet herunterladen",
    explore: "Ökosystem entdecken",
    testnetNote: "Öffentliches Testnet · Test-Assets haben keinen Geldwert.",
    ecosystemEyebrow: "Das YNX-Ökosystem",
    ecosystemTitle: "Dein Einstieg in YNX.",
    ecosystemLead: "Starte mit einer Wallet, erkunde das Netzwerk oder finde eine App zum Ausprobieren.",
    ecosystemAll: "Alle Anwendungen",
    ecosystemItems: [
      { title: "YNX Wallet", description: "Finde Wallet-Downloads und Installationsanleitungen für deine Plattform.", action: "Wallet herunterladen" },
      { title: "Explorer", description: "Sieh dir Blöcke, Transaktionen und Adressen im öffentlichen Testnet an.", action: "Explorer öffnen" },
      { title: "Faucet", description: "Fordere Test-YNXT für Netzwerkgebühren und zum Ausprobieren von Apps an.", action: "Test-YNXT erhalten" },
      { title: "Apps im Ökosystem", description: "Entdecke YNX-Apps, ihre Zugangswege und ihren aktuellen Testnet-Status.", action: "Apps ansehen" },
    ],
    developerEyebrow: "Für Entwickler",
    developerTitle: "Baue auf dem auf, was du kennst.",
    developerLead: "Nutze deine EVM-Tools auf YNX. Starte mit dem Netzwerkleitfaden, der Entwicklerdokumentation und dem SDK.",
    developerAction: "Entwicklung starten",
    networkDetails: "Netzwerkdetails",
    networkLead: "Live-Daten und Netzwerkkonfiguration, soweit verfügbar.",
    addressDetails: "Adresswerkzeuge",
    readinessDetails: "Fortschritt und Grenzen des Testnets",
    readinessScopeTitle: "Umfang des öffentlichen Testnets",
    readinessScope: ["Netzwerk 6423 und Test-Asset YNXT", "Netzwerk- und Transaktionsdaten", "Zugänge zum Ökosystem und aktueller Produktstatus", "Entwicklerdokumentation, SDK und Installationsanleitungen"],
    resourcesTitle: "Finde deinen nächsten Schritt.",
    menuLabel: "Mehr",
    networkAction: "Netzwerk",
    guide: "Installationsanleitung",
    productAction: "Details ansehen",
    productReference: "Testnet-Referenz",
    productReachable: "Dienst erreichbar",
    endpointCopy: ["Kopieren","Kopiert","Kopieren nicht möglich"],
    resourceItems: [
      { label: "Explorer", detail: "Blöcke, Transaktionen und Validatoren" },
      { label: "Netzwerkmonitor", detail: "Status von Netzwerk und Diensten" },
      { label: "Faucet", detail: "Test-YNXT anfordern" },
      { label: "Entwicklerdokumentation", detail: "Anleitungen sowie RPC- und SDK-Integration" },
      { label: "Chain-Quellcode", detail: "Code für Netzwerkbetrieb und Verifizierung" },
      { label: "Apps im Ökosystem", detail: "Apps und ihr aktueller Testnet-Status" },
    ],
  },
  pt: {
    heroTitle: "Uma rede. Novas possibilidades.",
    heroLead: "Uma Layer 1 compatível com EVM para pessoas, apps e agentes de IA. Explore a testnet pública da YNX.",
    download: "Baixar Wallet",
    explore: "Explorar o ecossistema",
    testnetNote: "Testnet pública · Os ativos de teste não têm valor monetário.",
    ecosystemEyebrow: "O ecossistema YNX",
    ecosystemTitle: "Seu ponto de partida na YNX.",
    ecosystemLead: "Comece com uma carteira, explore a rede ou encontre um app para experimentar.",
    ecosystemAll: "Todos os aplicativos",
    ecosystemItems: [
      { title: "YNX Wallet", description: "Encontre downloads da carteira e guias de instalação para sua plataforma.", action: "Baixar Wallet" },
      { title: "Explorador", description: "Consulte blocos, transações e endereços da testnet pública.", action: "Abrir explorador" },
      { title: "Faucet", description: "Solicite YNXT de teste para taxas de rede e para experimentar apps.", action: "Obter YNXT de teste" },
      { title: "Apps do ecossistema", description: "Conheça os apps YNX, as formas de acesso e o status atual na testnet.", action: "Ver apps" },
    ],
    developerEyebrow: "Para desenvolvedores",
    developerTitle: "Crie com o que você já conhece.",
    developerLead: "Use suas ferramentas EVM na YNX. Comece pelo guia de rede, pela documentação e pelo SDK.",
    developerAction: "Começar a desenvolver",
    networkDetails: "Detalhes da rede",
    networkLead: "Dados ao vivo e configuração da rede, quando disponíveis.",
    addressDetails: "Ferramentas de endereços",
    readinessDetails: "Progresso e limites da testnet",
    readinessScopeTitle: "Escopo da testnet pública",
    readinessScope: ["Rede 6423 e ativo de teste YNXT", "Dados de rede e transações", "Acessos ao ecossistema e status atual dos produtos", "Documentação, SDK e guias de instalação"],
    resourcesTitle: "Encontre seu próximo passo.",
    menuLabel: "Mais",
    networkAction: "Rede",
    guide: "Guia de instalação",
    productAction: "Ver detalhes",
    productReference: "Referência da testnet",
    productReachable: "Serviço acessível",
    endpointCopy: ["Copiar","Copiado","Não é possível copiar"],
    resourceItems: [
      { label: "Explorador", detail: "Blocos, transações e validadores" },
      { label: "Monitor de rede", detail: "Status da rede e dos serviços" },
      { label: "Faucet", detail: "Solicite YNXT de teste" },
      { label: "Documentação", detail: "Guias e integração de RPC e SDK" },
      { label: "Código da rede", detail: "Código de execução e verificação da rede" },
      { label: "Apps do ecossistema", detail: "Apps e seu status atual na testnet" },
    ],
  },
  ru: {
    heroTitle: "Одна сеть. Новые возможности.",
    heroLead: "Совместимая с EVM сеть Layer 1 для людей, приложений и ИИ-агентов. Откройте публичную тестовую сеть YNX.",
    download: "Скачать Wallet",
    explore: "Открыть экосистему",
    testnetNote: "Публичная тестовая сеть · Тестовые активы не имеют денежной стоимости.",
    ecosystemEyebrow: "Экосистема YNX",
    ecosystemTitle: "Ваш первый шаг в YNX.",
    ecosystemLead: "Начните с кошелька, изучите сеть или найдите приложение, которое хочется попробовать.",
    ecosystemAll: "Все приложения",
    ecosystemItems: [
      { title: "YNX Wallet", description: "Найдите кошелёк для своей платформы и руководство по установке.", action: "Скачать Wallet" },
      { title: "Обозреватель", description: "Просматривайте блоки, транзакции и адреса публичной тестовой сети.", action: "Открыть обозреватель" },
      { title: "Faucet", description: "Запросите тестовые YNXT для сетевых комиссий и проверки приложений.", action: "Получить тестовые YNXT" },
      { title: "Приложения экосистемы", description: "Узнайте о приложениях YNX, способах доступа и их текущем статусе в тестовой сети.", action: "Смотреть приложения" },
    ],
    developerEyebrow: "Разработчикам",
    developerTitle: "Создавайте знакомыми инструментами.",
    developerLead: "Используйте свои EVM-инструменты в YNX. Начните с руководства по сети, документации и SDK.",
    developerAction: "Начать разработку",
    networkDetails: "Данные сети",
    networkLead: "Актуальные данные и настройки сети, когда они доступны.",
    addressDetails: "Инструменты для адресов",
    readinessDetails: "Прогресс и ограничения тестовой сети",
    readinessScopeTitle: "Состав публичной тестовой сети",
    readinessScope: ["Сеть 6423 и тестовый актив YNXT", "Данные сети и транзакций", "Доступ к экосистеме и текущий статус продуктов", "Документация, SDK и руководства по установке"],
    resourcesTitle: "Выберите следующий шаг.",
    menuLabel: "Ещё",
    networkAction: "Сеть",
    guide: "Руководство по установке",
    productAction: "Подробнее",
    productReference: "Материалы тестовой сети",
    productReachable: "Сервис доступен",
    endpointCopy: ["Копировать","Скопировано","Не удалось скопировать"],
    resourceItems: [
      { label: "Обозреватель", detail: "Блоки, транзакции и валидаторы" },
      { label: "Монитор сети", detail: "Состояние сети и сервисов" },
      { label: "Faucet", detail: "Запрос тестовых YNXT" },
      { label: "Документация", detail: "Руководства, интеграция RPC и SDK" },
      { label: "Исходный код сети", detail: "Код работы и проверки сети" },
      { label: "Приложения экосистемы", detail: "Приложения и их статус в тестовой сети" },
    ],
  },
  ar: {
    heroTitle: "شبكة واحدة. إمكانات جديدة.",
    heroLead: "شبكة من الطبقة الأولى متوافقة مع EVM للأفراد والتطبيقات ووكلاء الذكاء الاصطناعي. استكشف شبكة اختبار YNX العامة.",
    download: "تنزيل Wallet",
    explore: "استكشف المنظومة",
    testnetNote: "شبكة اختبار عامة · الأصول التجريبية ليس لها قيمة نقدية.",
    ecosystemEyebrow: "منظومة YNX",
    ecosystemTitle: "من هنا تبدأ رحلتك مع YNX.",
    ecosystemLead: "ابدأ بمحفظة، أو استكشف الشبكة، أو اختر تطبيقًا لتجربته.",
    ecosystemAll: "جميع التطبيقات",
    ecosystemItems: [
      { title: "YNX Wallet", description: "اعثر على تنزيلات المحفظة وأدلة التثبيت المناسبة لجهازك.", action: "تنزيل Wallet" },
      { title: "مستكشف الشبكة", description: "تصفّح الكتل والمعاملات والعناوين على شبكة الاختبار العامة.", action: "فتح المستكشف" },
      { title: "صنبور الاختبار", description: "اطلب YNXT تجريبية لرسوم الشبكة وتجربة التطبيقات.", action: "الحصول على YNXT تجريبية" },
      { title: "تطبيقات المنظومة", description: "اكتشف تطبيقات YNX وطرق الوصول إليها وحالتها الحالية على شبكة الاختبار.", action: "تصفّح التطبيقات" },
    ],
    developerEyebrow: "للمطوّرين",
    developerTitle: "طوّر بأدواتك المألوفة.",
    developerLead: "استخدم أدوات EVM على YNX. ابدأ بدليل الشبكة ووثائق المطوّرين وحزمة SDK.",
    developerAction: "ابدأ التطوير",
    networkDetails: "تفاصيل الشبكة",
    networkLead: "بيانات مباشرة وإعدادات الشبكة، عند توفرها.",
    addressDetails: "أدوات العناوين",
    readinessDetails: "تقدّم شبكة الاختبار وحدودها",
    readinessScopeTitle: "نطاق شبكة الاختبار العامة",
    readinessScope: ["الشبكة 6423 والأصل التجريبي YNXT", "بيانات الشبكة والمعاملات", "مداخل المنظومة وحالة المنتجات الحالية", "وثائق المطوّرين وحزمة SDK وأدلة التثبيت"],
    resourcesTitle: "اختر خطوتك التالية.",
    menuLabel: "المزيد",
    networkAction: "الشبكة",
    guide: "دليل التثبيت",
    productAction: "عرض التفاصيل",
    productReference: "مرجع شبكة الاختبار",
    productReachable: "الخدمة متاحة للاتصال",
    endpointCopy: ["نسخ","تم النسخ","النسخ غير متاح"],
    resourceItems: [
      { label: "مستكشف الشبكة", detail: "الكتل والمعاملات والمدقّقون" },
      { label: "مراقب الشبكة", detail: "حالة الشبكة والخدمات" },
      { label: "صنبور الاختبار", detail: "طلب YNXT تجريبية" },
      { label: "وثائق المطوّرين", detail: "أدلة التطوير وتكامل RPC وSDK" },
      { label: "شفرة الشبكة", detail: "شفرة تشغيل الشبكة والتحقق منها" },
      { label: "تطبيقات المنظومة", detail: "التطبيقات وحالتها الحالية على شبكة الاختبار" },
    ],
  },
  id: {
    heroTitle: "Satu jaringan. Kemungkinan baru.",
    heroLead: "Layer 1 yang kompatibel dengan EVM untuk pengguna, aplikasi, dan agen AI. Jelajahi testnet publik YNX.",
    download: "Unduh Wallet",
    explore: "Jelajahi ekosistem",
    testnetNote: "Testnet publik · Aset uji tidak memiliki nilai moneter.",
    ecosystemEyebrow: "Ekosistem YNX",
    ecosystemTitle: "Langkah awal Anda di YNX.",
    ecosystemLead: "Mulai dengan dompet, jelajahi jaringan, atau temukan aplikasi untuk dicoba.",
    ecosystemAll: "Semua aplikasi",
    ecosystemItems: [
      { title: "YNX Wallet", description: "Temukan unduhan dompet dan panduan instalasi untuk platform Anda.", action: "Unduh Wallet" },
      { title: "Explorer", description: "Telusuri blok, transaksi, dan alamat di testnet publik.", action: "Buka Explorer" },
      { title: "Faucet", description: "Minta YNXT uji untuk biaya jaringan dan mencoba aplikasi.", action: "Dapatkan YNXT uji" },
      { title: "Aplikasi ekosistem", description: "Kenali aplikasi YNX, cara mengaksesnya, dan status testnet saat ini.", action: "Lihat aplikasi" },
    ],
    developerEyebrow: "Untuk pengembang",
    developerTitle: "Berkarya dengan alat yang Anda kenal.",
    developerLead: "Gunakan alat EVM Anda di YNX. Mulai dari panduan jaringan, dokumentasi pengembang, dan SDK.",
    developerAction: "Mulai mengembangkan",
    networkDetails: "Detail jaringan",
    networkLead: "Data langsung dan konfigurasi jaringan, jika tersedia.",
    addressDetails: "Alat alamat",
    readinessDetails: "Progres dan batasan testnet",
    readinessScopeTitle: "Cakupan testnet publik",
    readinessScope: ["Jaringan 6423 dan aset uji YNXT", "Data jaringan dan transaksi", "Akses ekosistem dan status produk saat ini", "Dokumentasi pengembang, SDK, dan panduan instalasi"],
    resourcesTitle: "Temukan langkah Anda berikutnya.",
    menuLabel: "Lainnya",
    networkAction: "Jaringan",
    guide: "Panduan instalasi",
    productAction: "Lihat detail",
    productReference: "Referensi testnet",
    productReachable: "Layanan dapat diakses",
    endpointCopy: ["Salin","Tersalin","Tidak dapat menyalin"],
    resourceItems: [
      { label: "Explorer", detail: "Blok, transaksi, dan validator" },
      { label: "Monitor Jaringan", detail: "Status jaringan dan layanan" },
      { label: "Faucet", detail: "Minta YNXT uji" },
      { label: "Dokumentasi pengembang", detail: "Panduan serta integrasi RPC dan SDK" },
      { label: "Kode sumber jaringan", detail: "Kode operasi dan verifikasi jaringan" },
      { label: "Aplikasi ekosistem", detail: "Aplikasi dan status testnet saat ini" },
    ],
  },
};

export function getHomeRedesignCopy(locale) {
  return Object.hasOwn(HOME_REDESIGN_COPY, locale)
    ? HOME_REDESIGN_COPY[locale]
    : HOME_REDESIGN_COPY.en;
}
