export const HOME_COPY = {
  en: ["Public Testnet", "Auditable Web4 execution for people, apps, and AI agents.", "YNX is an EVM-compatible Layer-1 Testnet. YNXT pays testnet gas and fees; Mainnet and market value are not claimed.", "Open Explorer", "Get Testnet YNXT", "Add 6423 to wallet", "Network", "Chain ID", "Native asset", "Indexer", "Verified", "Checking", "Unavailable", "Latest height", "Data source"],
  "zh-CN": ["公开测试网", "让人、应用与 AI Agent 在可审计边界内执行 Web4。", "YNX 是兼容 EVM 的 Layer-1 测试网。YNXT 用于测试网 Gas 与手续费；本站不宣称主网或市场价值。", "打开 Explorer", "领取测试 YNXT", "将 6423 添加到钱包", "网络", "链 ID", "原生资产", "索引器", "已核验", "正在核验", "暂不可用", "最新高度", "数据来源"],
  "zh-TW": ["公開測試網", "讓人、應用與 AI Agent 在可稽核邊界內執行 Web4。", "YNX 是相容 EVM 的 Layer-1 測試網。YNXT 用於測試網 Gas 與手續費；本站不宣稱主網或市場價值。", "開啟 Explorer", "領取測試 YNXT", "將 6423 加入錢包", "網路", "鏈 ID", "原生資產", "索引器", "已核驗", "正在核驗", "暫不可用", "最新高度", "資料來源"],
  ja: ["公開テストネット", "監査可能な境界で人・アプリ・AI Agent が Web4 を実行。", "YNX は EVM 互換 Layer-1 テストネットです。YNXT はテスト用 Gas と手数料に使われ、Mainnet や市場価値を主張しません。", "Explorer を開く", "テスト YNXT を取得", "6423 をウォレットへ追加", "ネットワーク", "チェーン ID", "ネイティブ資産", "インデクサー", "検証済み", "確認中", "利用不可", "最新の高さ", "データソース"],
  ko: ["공개 테스트넷", "사람·앱·AI Agent를 위한 감사 가능한 Web4 실행.", "YNX는 EVM 호환 Layer-1 테스트넷입니다. YNXT는 테스트 Gas와 수수료에만 사용되며 Mainnet이나 시장 가치를 주장하지 않습니다.", "Explorer 열기", "테스트 YNXT 받기", "지갑에 6423 추가", "네트워크", "체인 ID", "네이티브 자산", "인덱서", "검증됨", "확인 중", "사용 불가", "최신 높이", "데이터 원본"],
  es: ["Testnet pública", "Ejecución Web4 auditable para personas, aplicaciones y agentes de IA.", "YNX es una Layer-1 compatible con EVM en Testnet. YNXT sirve para gas y comisiones de prueba; no se afirma Mainnet ni valor de mercado.", "Abrir Explorer", "Obtener YNXT de prueba", "Añadir 6423 al monedero", "Red", "ID de cadena", "Activo nativo", "Indexador", "Verificado", "Comprobando", "No disponible", "Altura reciente", "Fuente de datos"],
  fr: ["Testnet publique", "Exécution Web4 auditable pour les personnes, applications et agents IA.", "YNX est une Layer-1 compatible EVM en Testnet. YNXT sert au gas et aux frais de test ; aucun Mainnet ni valeur de marché n'est revendiqué.", "Ouvrir Explorer", "Obtenir du YNXT de test", "Ajouter 6423 au portefeuille", "Réseau", "ID de chaîne", "Actif natif", "Indexeur", "Vérifié", "Vérification", "Indisponible", "Dernière hauteur", "Source des données"],
  de: ["Öffentliches Testnet", "Prüfbare Web4-Ausführung für Menschen, Apps und KI-Agenten.", "YNX ist ein EVM-kompatibles Layer-1-Testnet. YNXT dient Test-Gas und Gebühren; Mainnet oder Marktwert werden nicht behauptet.", "Explorer öffnen", "Test-YNXT erhalten", "6423 zur Wallet hinzufügen", "Netzwerk", "Chain-ID", "Native Anlage", "Indexer", "Geprüft", "Prüfung", "Nicht verfügbar", "Neueste Höhe", "Datenquelle"],
  pt: ["Testnet pública", "Execução Web4 auditável para pessoas, apps e agentes de IA.", "YNX é uma Layer-1 compatível com EVM em Testnet. YNXT serve para gas e taxas de teste; não há alegação de Mainnet ou valor de mercado.", "Abrir Explorer", "Obter YNXT de teste", "Adicionar 6423 à carteira", "Rede", "ID da cadeia", "Ativo nativo", "Indexador", "Verificado", "Verificando", "Indisponível", "Altura recente", "Fonte de dados"],
  ru: ["Публичная тестовая сеть", "Проверяемое выполнение Web4 для людей, приложений и ИИ-агентов.", "YNX — совместимая с EVM тестовая Layer-1. YNXT используется для тестового газа и комиссий; Mainnet и рыночная стоимость не заявлены.", "Открыть Explorer", "Получить тестовый YNXT", "Добавить 6423 в кошелёк", "Сеть", "ID цепи", "Нативный актив", "Индексатор", "Проверено", "Проверка", "Недоступно", "Последняя высота", "Источник данных"],
  ar: ["شبكة اختبار عامة", "تنفيذ Web4 قابل للتدقيق للأشخاص والتطبيقات ووكلاء الذكاء الاصطناعي.", "YNX شبكة Layer-1 متوافقة مع EVM في مرحلة الاختبار. تُستخدم YNXT للغاز والرسوم الاختبارية؛ ولا ندّعي وجود Mainnet أو قيمة سوقية.", "فتح Explorer", "الحصول على YNXT اختباري", "إضافة 6423 إلى المحفظة", "الشبكة", "معرّف السلسلة", "الأصل الأصلي", "المفهرس", "متحقق", "جارٍ التحقق", "غير متاح", "أحدث ارتفاع", "مصدر البيانات"],
  id: ["Testnet publik", "Eksekusi Web4 yang dapat diaudit untuk manusia, aplikasi, dan agen AI.", "YNX adalah Layer-1 kompatibel EVM dalam Testnet. YNXT dipakai untuk gas dan biaya uji; tidak ada klaim Mainnet atau nilai pasar.", "Buka Explorer", "Dapatkan YNXT uji", "Tambahkan 6423 ke dompet", "Jaringan", "Chain ID", "Aset native", "Indexer", "Terverifikasi", "Memeriksa", "Tidak tersedia", "Tinggi terbaru", "Sumber data"],
};

export function getHomeCopy(locale) {
  const value = HOME_COPY[locale];
  return value ? {
    eyebrow: value[0], title: value[1], lead: value[2], actions: value.slice(3, 6),
    labels: { network: value[6], chain: value[7], asset: value[8], indexer: value[9], verified: value[10], checking: value[11], unavailable: value[12], height: value[13], source: value[14] },
  } : null;
}
