export const NETWORK_METRIC_COPY = Object.freeze({
  en: { blockAge: "Block age at check", rpcRead: "RPC collection (incl. queue)", explorerRead: "Explorer collection (incl. queue)", evmRead: "EVM collection (incl. queue)", lag: "Indexer lag", growth: "Block growth at check", observed: "Observed", notObserved: "Not observed", unverified: "Unverified", timeout: "Timed out", blocks: "blocks", refresh: "Refresh status", refreshing: "Refreshing…" },
  "zh-CN": { blockAge: "核验时区块年龄", rpcRead: "RPC 采集耗时（含排队）", explorerRead: "Explorer 采集耗时（含排队）", evmRead: "EVM 采集耗时（含排队）", lag: "Indexer 落后", growth: "核验时区块增长", observed: "已观察到", notObserved: "未观察到", unverified: "无法核验", timeout: "读取超时", blocks: "个区块", refresh: "刷新状态", refreshing: "正在刷新…" },
  "zh-TW": { blockAge: "核驗時區塊年齡", rpcRead: "RPC 擷取耗時（含排隊）", explorerRead: "Explorer 擷取耗時（含排隊）", evmRead: "EVM 擷取耗時（含排隊）", lag: "Indexer 落後", growth: "核驗時區塊增長", observed: "已觀察到", notObserved: "未觀察到", unverified: "無法核驗", timeout: "讀取逾時", blocks: "個區塊", refresh: "重新整理狀態", refreshing: "正在重新整理…" },
  ja: { blockAge: "確認時のブロック経過時間", rpcRead: "RPC 収集時間（待機含む）", explorerRead: "Explorer 収集時間（待機含む）", evmRead: "EVM 収集時間（待機含む）", lag: "Indexer の遅れ", growth: "確認時のブロック増加", observed: "確認済み", notObserved: "確認できず", unverified: "未検証", timeout: "タイムアウト", blocks: "ブロック", refresh: "状態を更新", refreshing: "更新中…" },
  ko: { blockAge: "확인 시 블록 경과 시간", rpcRead: "RPC 수집 시간(대기 포함)", explorerRead: "Explorer 수집 시간(대기 포함)", evmRead: "EVM 수집 시간(대기 포함)", lag: "Indexer 지연", growth: "확인 시 블록 증가", observed: "관찰됨", notObserved: "관찰되지 않음", unverified: "확인 불가", timeout: "시간 초과", blocks: "블록", refresh: "상태 새로고침", refreshing: "새로고침 중…" },
  es: { blockAge: "Edad del bloque al comprobar", rpcRead: "Lectura RPC (con espera)", explorerRead: "Lectura Explorer (con espera)", evmRead: "Lectura EVM (con espera)", lag: "Retraso del indexador", growth: "Avance de bloques al comprobar", observed: "Observado", notObserved: "No observado", unverified: "Sin verificar", timeout: "Tiempo agotado", blocks: "bloques", refresh: "Actualizar estado", refreshing: "Actualizando…" },
  fr: { blockAge: "Âge du bloc au contrôle", rpcRead: "Collecte RPC (attente incluse)", explorerRead: "Collecte Explorer (attente incluse)", evmRead: "Collecte EVM (attente incluse)", lag: "Retard de l’indexeur", growth: "Progression des blocs au contrôle", observed: "Observée", notObserved: "Non observée", unverified: "Non vérifiée", timeout: "Délai dépassé", blocks: "blocs", refresh: "Actualiser l’état", refreshing: "Actualisation…" },
  de: { blockAge: "Blockalter bei Prüfung", rpcRead: "RPC-Erfassung (inkl. Wartezeit)", explorerRead: "Explorer-Erfassung (inkl. Wartezeit)", evmRead: "EVM-Erfassung (inkl. Wartezeit)", lag: "Indexer-Rückstand", growth: "Blockwachstum bei Prüfung", observed: "Beobachtet", notObserved: "Nicht beobachtet", unverified: "Nicht verifiziert", timeout: "Zeitüberschreitung", blocks: "Blöcke", refresh: "Status aktualisieren", refreshing: "Aktualisierung…" },
  pt: { blockAge: "Idade do bloco na verificação", rpcRead: "Coleta RPC (inclui espera)", explorerRead: "Coleta Explorer (inclui espera)", evmRead: "Coleta EVM (inclui espera)", lag: "Atraso do indexador", growth: "Avanço de blocos na verificação", observed: "Observado", notObserved: "Não observado", unverified: "Não verificado", timeout: "Tempo esgotado", blocks: "blocos", refresh: "Atualizar estado", refreshing: "Atualizando…" },
  ru: { blockAge: "Возраст блока при проверке", rpcRead: "Сбор RPC (с ожиданием)", explorerRead: "Сбор Explorer (с ожиданием)", evmRead: "Сбор EVM (с ожиданием)", lag: "Отставание индексатора", growth: "Рост блоков при проверке", observed: "Наблюдался", notObserved: "Не наблюдался", unverified: "Не проверено", timeout: "Время истекло", blocks: "блоков", refresh: "Обновить статус", refreshing: "Обновление…" },
  ar: { blockAge: "عمر الكتلة عند الفحص", rpcRead: "جمع RPC (يشمل الانتظار)", explorerRead: "جمع Explorer (يشمل الانتظار)", evmRead: "جمع EVM (يشمل الانتظار)", lag: "تأخر المفهرس", growth: "تقدم الكتل عند الفحص", observed: "تم رصده", notObserved: "لم يُرصد", unverified: "غير متحقق", timeout: "انتهت المهلة", blocks: "كتل", refresh: "تحديث الحالة", refreshing: "جارٍ التحديث…" },
  id: { blockAge: "Usia blok saat diperiksa", rpcRead: "Pengumpulan RPC (termasuk antrean)", explorerRead: "Pengumpulan Explorer (termasuk antrean)", evmRead: "Pengumpulan EVM (termasuk antrean)", lag: "Ketertinggalan indexer", growth: "Pertumbuhan blok saat diperiksa", observed: "Teramati", notObserved: "Tidak teramati", unverified: "Belum terverifikasi", timeout: "Waktu habis", blocks: "blok", refresh: "Perbarui status", refreshing: "Memperbarui…" },
});

export function getNetworkMetricCopy(locale) {
  return NETWORK_METRIC_COPY[locale] || NETWORK_METRIC_COPY.en;
}
