/* Proposed shared product-page UI labels. Pure data; not integrated into a product.
 * Keep product facts, availability checks and installation limitations authoritative.
 * These labels do not translate product.detail, release notes or dynamic error reasons.
 * Resolve unsupported locales to PRODUCT_UI_FALLBACK_LOCALE in the consuming app.
 */
export const PRODUCT_UI_FALLBACK_LOCALE = "en";
export const PRODUCT_UI_DIRECTIONS = { ar: "rtl" };
export const PRODUCT_PLATFORM_NAMES = {
  web: "Web", pwa: "PWA", chromeEdge: "Chrome / Edge", firefox: "Firefox",
  android: "Android", ios: "iOS", macos: "macOS", windows: "Windows",
  windowsX64: "Windows (x64)", windowsArm64: "Windows (arm64)", linux: "Linux"
};
export const PRODUCT_SECTION_LABEL_KEYS = {
  overview: "overview",
  features: "features",
  "open-download": "openDownload",
  "docs-api": "docsApi",
  "security-privacy-status-support": "helpSafety",
  "integrations-web4": "integrations",
  risks: "usageNotes",
  releases: "releases"
};

export const PRODUCT_UI_COPY = {
  "zh-CN": {
    overview: "产品介绍", features: "功能", openDownload: "打开与下载",
    docs: "文档", api: "API", docsApi: "文档与 API", helpSafety: "帮助与安全",
    integrations: "集成", usageNotes: "使用须知", releases: "版本记录",
    openInBrowser: "在浏览器中打开", download: "下载", unavailableYet: "暂未提供",
    releaseDetails: "版本详情", requirements: "使用要求", knownLimitations: "已知限制",
    testnetPreview: "测试网预览版", choosePlatform: "选择你的平台",
    downloadCenter: "下载中心", version: "版本", architecture: "芯片架构",
    fileSize: "文件大小", signature: "签名状态", installation: "安装说明",
    showDetails: "查看详情", hideDetails: "收起详情", security: "安全",
    privacy: "隐私", serviceStatus: "服务状态", support: "帮助与支持",
    readBeforeUse: "使用前请阅读", noDownload: "暂未提供安装包",
    noWebVersion: "暂未提供网页版", productSections: "产品导航",
    installNotice: "测试网预览版本，未完成正式签名或商店上架。",
    walletProviderRequired: "网页版需要已安装的钱包来确认操作。",
    unavailable: "此平台版本正在完善。",
    macLegacyBlocked: "此旧版无法完成账户授权；新版正在验收，请先使用其他可用入口。",
    previewUnverified: "安装包可下载，账户及交易流程仍在验收。",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  "zh-TW": {
    overview: "產品介紹", features: "功能", openDownload: "開啟與下載",
    docs: "文件", api: "API", docsApi: "文件與 API", helpSafety: "協助與安全",
    integrations: "整合", usageNotes: "使用須知", releases: "版本紀錄",
    openInBrowser: "在瀏覽器中開啟", download: "下載", unavailableYet: "尚未提供",
    releaseDetails: "版本詳情", requirements: "使用需求", knownLimitations: "已知限制",
    testnetPreview: "測試網預覽版", choosePlatform: "選擇你的平台",
    downloadCenter: "下載中心", version: "版本", architecture: "處理器架構",
    fileSize: "檔案大小", signature: "簽章狀態", installation: "安裝說明",
    showDetails: "查看詳情", hideDetails: "收合詳情", security: "安全",
    privacy: "隱私", serviceStatus: "服務狀態", support: "協助與支援",
    readBeforeUse: "使用前請閱讀", noDownload: "尚未提供安裝檔",
    noWebVersion: "尚未提供網頁版", productSections: "產品導覽",
    installNotice: "測試網預覽版本，尚未完成正式簽章或商店上架。",
    walletProviderRequired: "網頁版需要已安裝的錢包來確認操作。",
    unavailable: "此平台版本仍在完善中。",
    macLegacyBlocked: "此舊版無法完成帳戶授權；新版正在驗收，請先使用其他可用入口。",
    previewUnverified: "可下載安裝檔，帳戶及交易流程仍在驗收中。",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  en: {
    overview: "Overview", features: "Features", openDownload: "Open & download",
    docs: "Docs", api: "API", docsApi: "Docs & API", helpSafety: "Help & safety",
    integrations: "Integrations", usageNotes: "Usage notes", releases: "Release history",
    openInBrowser: "Open in browser", download: "Download", unavailableYet: "Not available yet",
    releaseDetails: "Release details", requirements: "Requirements", knownLimitations: "Known limitations",
    testnetPreview: "Testnet preview", choosePlatform: "Choose your platform",
    downloadCenter: "Download center", version: "Version", architecture: "Architecture",
    fileSize: "File size", signature: "Signing status", installation: "Installation guide",
    showDetails: "Show details", hideDetails: "Hide details", security: "Security",
    privacy: "Privacy", serviceStatus: "Service status", support: "Help & support",
    readBeforeUse: "Read before use", noDownload: "No installer available yet",
    noWebVersion: "No web version available yet", productSections: "Product navigation",
    installNotice: "Testnet preview. Production signing and app store release are not complete.",
    walletProviderRequired: "The web version needs an installed wallet to confirm actions.",
    unavailable: "This platform version is still being refined.",
    macLegacyBlocked: "This older version cannot complete account authorization. The new version is under review; please use another available option for now.",
    previewUnverified: "The installer is available. Account and transaction flows are still being verified.",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  ja: {
    overview: "製品概要", features: "機能", openDownload: "開く・ダウンロード",
    docs: "ドキュメント", api: "API", docsApi: "ドキュメント・API", helpSafety: "ヘルプ・安全性",
    integrations: "連携", usageNotes: "利用上の注意", releases: "リリース履歴",
    openInBrowser: "ブラウザーで開く", download: "ダウンロード", unavailableYet: "未提供",
    releaseDetails: "リリース詳細", requirements: "利用要件", knownLimitations: "既知の制限",
    testnetPreview: "テストネットプレビュー版", choosePlatform: "プラットフォームを選択",
    downloadCenter: "ダウンロードセンター", version: "バージョン", architecture: "アーキテクチャ",
    fileSize: "ファイルサイズ", signature: "署名の状態", installation: "インストール手順",
    showDetails: "詳細を表示", hideDetails: "詳細を閉じる", security: "セキュリティ",
    privacy: "プライバシー", serviceStatus: "サービス状況", support: "ヘルプ・サポート",
    readBeforeUse: "ご利用前にお読みください", noDownload: "インストーラーは未提供です",
    noWebVersion: "Web 版は未提供です", productSections: "製品ナビゲーション",
    installNotice: "テストネットのプレビュー版です。正式な署名とストア公開は完了していません。",
    walletProviderRequired: "Web 版で操作を確認するには、インストール済みのウォレットが必要です。",
    unavailable: "このプラットフォーム向けのバージョンは現在調整中です。",
    macLegacyBlocked: "この旧版ではアカウントのアクセス許可を完了できません。新版は検証中のため、当面は他の利用可能な方法をお使いください。",
    previewUnverified: "インストーラーはダウンロードできます。アカウントと取引の操作は引き続き検証中です。",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  ko: {
    overview: "제품 소개", features: "기능", openDownload: "열기 및 다운로드",
    docs: "문서", api: "API", docsApi: "문서 및 API", helpSafety: "도움말 및 안전",
    integrations: "연동", usageNotes: "이용 안내", releases: "출시 이력",
    openInBrowser: "브라우저에서 열기", download: "다운로드", unavailableYet: "아직 제공되지 않음",
    releaseDetails: "버전 상세 정보", requirements: "사용 요구 사항", knownLimitations: "알려진 제한 사항",
    testnetPreview: "테스트넷 미리 보기 버전", choosePlatform: "플랫폼 선택",
    downloadCenter: "다운로드 센터", version: "버전", architecture: "아키텍처",
    fileSize: "파일 크기", signature: "서명 상태", installation: "설치 안내",
    showDetails: "상세 정보 보기", hideDetails: "상세 정보 접기", security: "보안",
    privacy: "개인정보 보호", serviceStatus: "서비스 상태", support: "도움말 및 지원",
    readBeforeUse: "사용 전 확인해 주세요", noDownload: "설치 파일이 아직 제공되지 않습니다",
    noWebVersion: "웹 버전이 아직 제공되지 않습니다", productSections: "제품 탐색",
    installNotice: "테스트넷 미리 보기 버전입니다. 정식 서명과 앱 스토어 출시는 완료되지 않았습니다.",
    walletProviderRequired: "웹 버전에서 작업을 확인하려면 설치된 지갑이 필요합니다.",
    unavailable: "이 플랫폼 버전은 개선 중입니다.",
    macLegacyBlocked: "이 이전 버전에서는 계정 접근 승인을 완료할 수 없습니다. 새 버전은 검증 중이므로 당분간 다른 이용 가능한 방법을 사용해 주세요.",
    previewUnverified: "설치 파일을 다운로드할 수 있습니다. 계정 및 거래 흐름은 아직 검증 중입니다.",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  es: {
    overview: "Descripción", features: "Funciones", openDownload: "Abrir y descargar",
    docs: "Documentación", api: "API", docsApi: "Documentación y API", helpSafety: "Ayuda y seguridad",
    integrations: "Integraciones", usageNotes: "Notas de uso", releases: "Historial de versiones",
    openInBrowser: "Abrir en el navegador", download: "Descargar", unavailableYet: "Aún no disponible",
    releaseDetails: "Detalles de la versión", requirements: "Requisitos", knownLimitations: "Limitaciones conocidas",
    testnetPreview: "Versión preliminar de testnet", choosePlatform: "Elige tu plataforma",
    downloadCenter: "Centro de descargas", version: "Versión", architecture: "Arquitectura",
    fileSize: "Tamaño del archivo", signature: "Estado de la firma", installation: "Guía de instalación",
    showDetails: "Ver detalles", hideDetails: "Ocultar detalles", security: "Seguridad",
    privacy: "Privacidad", serviceStatus: "Estado del servicio", support: "Ayuda y soporte",
    readBeforeUse: "Lee antes de usar", noDownload: "Aún no hay un instalador disponible",
    noWebVersion: "La versión web aún no está disponible", productSections: "Navegación del producto",
    installNotice: "Versión preliminar de testnet. La firma de producción y la publicación en tiendas de aplicaciones no están completas.",
    walletProviderRequired: "La versión web requiere una cartera instalada para confirmar las acciones.",
    unavailable: "La versión para esta plataforma sigue en desarrollo.",
    macLegacyBlocked: "Esta versión anterior no puede completar la autorización de la cuenta. La nueva versión está en revisión; por ahora, usa otra opción disponible.",
    previewUnverified: "El instalador está disponible. Los procesos de cuenta y transacciones siguen en verificación.",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  fr: {
    overview: "Présentation", features: "Fonctionnalités", openDownload: "Ouvrir et télécharger",
    docs: "Documentation", api: "API", docsApi: "Documentation et API", helpSafety: "Aide et sécurité",
    integrations: "Intégrations", usageNotes: "Notes d’utilisation", releases: "Historique des versions",
    openInBrowser: "Ouvrir dans le navigateur", download: "Télécharger", unavailableYet: "Pas encore disponible",
    releaseDetails: "Détails de la version", requirements: "Prérequis", knownLimitations: "Limites connues",
    testnetPreview: "Version d’essai sur testnet", choosePlatform: "Choisissez votre plateforme",
    downloadCenter: "Centre de téléchargement", version: "Version", architecture: "Architecture",
    fileSize: "Taille du fichier", signature: "État de la signature", installation: "Guide d’installation",
    showDetails: "Afficher les détails", hideDetails: "Masquer les détails", security: "Sécurité",
    privacy: "Confidentialité", serviceStatus: "État du service", support: "Aide et assistance",
    readBeforeUse: "À lire avant utilisation", noDownload: "Aucun programme d’installation disponible pour le moment",
    noWebVersion: "La version web n’est pas encore disponible", productSections: "Navigation du produit",
    installNotice: "Version d’essai sur testnet. La signature de production et la publication dans les boutiques d’applications ne sont pas finalisées.",
    walletProviderRequired: "La version web nécessite un portefeuille installé pour confirmer les actions.",
    unavailable: "La version pour cette plateforme est encore en cours d’amélioration.",
    macLegacyBlocked: "Cette ancienne version ne peut pas finaliser l’autorisation du compte. La nouvelle version est en cours de vérification ; utilisez une autre option disponible pour le moment.",
    previewUnverified: "Le programme d’installation est disponible. Les parcours de compte et de transaction sont encore en cours de vérification.",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  de: {
    overview: "Übersicht", features: "Funktionen", openDownload: "Öffnen und herunterladen",
    docs: "Dokumentation", api: "API", docsApi: "Dokumentation und API", helpSafety: "Hilfe und Sicherheit",
    integrations: "Integrationen", usageNotes: "Nutzungshinweise", releases: "Versionsverlauf",
    openInBrowser: "Im Browser öffnen", download: "Herunterladen", unavailableYet: "Noch nicht verfügbar",
    releaseDetails: "Versionsdetails", requirements: "Voraussetzungen", knownLimitations: "Bekannte Einschränkungen",
    testnetPreview: "Testnet-Vorschau", choosePlatform: "Plattform auswählen",
    downloadCenter: "Downloadcenter", version: "Version", architecture: "Architektur",
    fileSize: "Dateigröße", signature: "Signaturstatus", installation: "Installationsanleitung",
    showDetails: "Details anzeigen", hideDetails: "Details ausblenden", security: "Sicherheit",
    privacy: "Datenschutz", serviceStatus: "Dienststatus", support: "Hilfe und Support",
    readBeforeUse: "Vor der Nutzung lesen", noDownload: "Noch kein Installationsprogramm verfügbar",
    noWebVersion: "Noch keine Webversion verfügbar", productSections: "Produktnavigation",
    installNotice: "Testnet-Vorschau. Die Produktionssignierung und die Veröffentlichung im App-Store sind noch nicht abgeschlossen.",
    walletProviderRequired: "Die Webversion benötigt eine installierte Wallet, um Aktionen zu bestätigen.",
    unavailable: "Die Version für diese Plattform wird noch überarbeitet.",
    macLegacyBlocked: "Diese ältere Version kann die Kontozugriffsfreigabe nicht abschließen. Die neue Version wird geprüft. Bitte nutzen Sie vorerst eine andere verfügbare Möglichkeit.",
    previewUnverified: "Das Installationsprogramm ist verfügbar. Konto- und Transaktionsabläufe werden noch geprüft.",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  pt: {
    overview: "Visão geral", features: "Funcionalidades", openDownload: "Abrir e baixar",
    docs: "Documentação", api: "API", docsApi: "Documentação e API", helpSafety: "Ajuda e segurança",
    integrations: "Integrações", usageNotes: "Notas de uso", releases: "Histórico de versões",
    openInBrowser: "Abrir no navegador", download: "Baixar", unavailableYet: "Ainda não disponível",
    releaseDetails: "Detalhes da versão", requirements: "Requisitos", knownLimitations: "Limitações conhecidas",
    testnetPreview: "Prévia da testnet", choosePlatform: "Escolha sua plataforma",
    downloadCenter: "Central de downloads", version: "Versão", architecture: "Arquitetura",
    fileSize: "Tamanho do arquivo", signature: "Status da assinatura", installation: "Guia de instalação",
    showDetails: "Mostrar detalhes", hideDetails: "Ocultar detalhes", security: "Segurança",
    privacy: "Privacidade", serviceStatus: "Status do serviço", support: "Ajuda e suporte",
    readBeforeUse: "Leia antes de usar", noDownload: "Ainda não há instalador disponível",
    noWebVersion: "A versão web ainda não está disponível", productSections: "Navegação do produto",
    installNotice: "Prévia da testnet. A assinatura de produção e a publicação nas lojas de aplicativos ainda não foram concluídas.",
    walletProviderRequired: "A versão web precisa de uma carteira instalada para confirmar as ações.",
    unavailable: "A versão para esta plataforma ainda está sendo aprimorada.",
    macLegacyBlocked: "Esta versão antiga não consegue concluir a autorização da conta. A nova versão está em análise; por enquanto, use outra opção disponível.",
    previewUnverified: "O instalador está disponível. Os fluxos de conta e transação ainda estão sendo verificados.",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  ru: {
    overview: "О продукте", features: "Возможности", openDownload: "Открыть и скачать",
    docs: "Документация", api: "API", docsApi: "Документация и API", helpSafety: "Помощь и безопасность",
    integrations: "Интеграции", usageNotes: "Примечания по использованию", releases: "История версий",
    openInBrowser: "Открыть в браузере", download: "Скачать", unavailableYet: "Пока недоступно",
    releaseDetails: "Сведения о версии", requirements: "Требования", knownLimitations: "Известные ограничения",
    testnetPreview: "Предварительная версия для тестовой сети", choosePlatform: "Выберите платформу",
    downloadCenter: "Центр загрузок", version: "Версия", architecture: "Архитектура",
    fileSize: "Размер файла", signature: "Статус подписи", installation: "Инструкция по установке",
    showDetails: "Показать подробности", hideDetails: "Скрыть подробности", security: "Безопасность",
    privacy: "Конфиденциальность", serviceStatus: "Состояние сервиса", support: "Помощь и поддержка",
    readBeforeUse: "Прочитайте перед использованием", noDownload: "Установщик пока недоступен",
    noWebVersion: "Веб-версия пока недоступна", productSections: "Навигация по продукту",
    installNotice: "Предварительная версия для тестовой сети. Подпись для выпуска и публикация в магазинах приложений ещё не завершены.",
    walletProviderRequired: "Для подтверждения действий в веб-версии нужен установленный кошелёк.",
    unavailable: "Версия для этой платформы ещё дорабатывается.",
    macLegacyBlocked: "Эта старая версия не может завершить предоставление доступа к аккаунту. Новая версия проходит проверку; пока воспользуйтесь другим доступным вариантом.",
    previewUnverified: "Установщик доступен. Работа с аккаунтами и транзакциями ещё проверяется.",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  ar: {
    overview: "عن المنتج", features: "الميزات", openDownload: "الفتح والتنزيل",
    docs: "الوثائق", api: "API", docsApi: "الوثائق وواجهة API", helpSafety: "المساعدة والأمان",
    integrations: "عمليات التكامل", usageNotes: "إرشادات الاستخدام", releases: "سجل الإصدارات",
    openInBrowser: "فتح في المتصفح", download: "تنزيل", unavailableYet: "غير متاح بعد",
    releaseDetails: "تفاصيل الإصدار", requirements: "المتطلبات", knownLimitations: "القيود المعروفة",
    testnetPreview: "نسخة معاينة لشبكة الاختبار", choosePlatform: "اختر منصتك",
    downloadCenter: "مركز التنزيلات", version: "الإصدار", architecture: "بنية المعالج",
    fileSize: "حجم الملف", signature: "حالة التوقيع", installation: "دليل التثبيت",
    showDetails: "عرض التفاصيل", hideDetails: "إخفاء التفاصيل", security: "الأمان",
    privacy: "الخصوصية", serviceStatus: "حالة الخدمة", support: "المساعدة والدعم",
    readBeforeUse: "اقرأ قبل الاستخدام", noDownload: "برنامج التثبيت غير متاح بعد",
    noWebVersion: "نسخة الويب غير متاحة بعد", productSections: "التنقل في المنتج",
    installNotice: "نسخة معاينة لشبكة الاختبار. لم يكتمل التوقيع الرسمي أو النشر في متاجر التطبيقات.",
    walletProviderRequired: "تحتاج نسخة الويب إلى محفظة مثبتة لتأكيد الإجراءات.",
    unavailable: "نسخة هذه المنصة لا تزال قيد التحسين.",
    macLegacyBlocked: "لا يمكن لهذا الإصدار القديم إكمال تفويض الوصول إلى الحساب. الإصدار الجديد قيد التحقق؛ يرجى استخدام خيار آخر متاح حاليًا.",
    previewUnverified: "برنامج التثبيت متاح للتنزيل. لا تزال إجراءات الحساب والمعاملات قيد التحقق.",
    platformNames: PRODUCT_PLATFORM_NAMES
  },
  id: {
    overview: "Tentang produk", features: "Fitur", openDownload: "Buka dan unduh",
    docs: "Dokumentasi", api: "API", docsApi: "Dokumentasi dan API", helpSafety: "Bantuan dan keamanan",
    integrations: "Integrasi", usageNotes: "Panduan penggunaan", releases: "Riwayat versi",
    openInBrowser: "Buka di browser", download: "Unduh", unavailableYet: "Belum tersedia",
    releaseDetails: "Detail versi", requirements: "Persyaratan", knownLimitations: "Batasan yang diketahui",
    testnetPreview: "Versi pratinjau testnet", choosePlatform: "Pilih platform Anda",
    downloadCenter: "Pusat unduhan", version: "Versi", architecture: "Arsitektur",
    fileSize: "Ukuran file", signature: "Status tanda tangan", installation: "Panduan instalasi",
    showDetails: "Tampilkan detail", hideDetails: "Sembunyikan detail", security: "Keamanan",
    privacy: "Privasi", serviceStatus: "Status layanan", support: "Bantuan dan dukungan",
    readBeforeUse: "Baca sebelum menggunakan", noDownload: "Penginstal belum tersedia",
    noWebVersion: "Versi web belum tersedia", productSections: "Navigasi produk",
    installNotice: "Versi pratinjau testnet. Penandatanganan produksi dan penerbitan di toko aplikasi belum selesai.",
    walletProviderRequired: "Versi web memerlukan dompet yang sudah terpasang untuk mengonfirmasi tindakan.",
    unavailable: "Versi untuk platform ini masih disempurnakan.",
    macLegacyBlocked: "Versi lama ini tidak dapat menyelesaikan otorisasi akun. Versi baru sedang diverifikasi; gunakan opsi lain yang tersedia untuk sementara.",
    previewUnverified: "Penginstal tersedia untuk diunduh. Alur akun dan transaksi masih diverifikasi.",
    platformNames: PRODUCT_PLATFORM_NAMES
  }
};
