import { buildCompactRuntimeCopy } from "./runtimeLocaleContent.js";

const compact = {
  ja: ["ライブネットワーク", "現在の公開テストネット", "更新", "検証可能なバリデータ役割", "各役割の高さは個別に報告され、可用性だけでは収束や公開 BFT 投票を証明しません。", "フルスタック・エコシステム", "一つのチェーン、つながる運用面", "開発者向け", "実際のエンドポイントへ接続。", "現在と目標を分離", "確認済み", "今後必要", "虚偽の主張なし", "最新ネットワーク記録", "最新ブロック", "インデックス済み取引", "利用不可", "現在"],
  ko: ["실시간 네트워크", "현재 공개 테스트넷 상태", "업데이트", "검사 가능한 검증자 역할", "각 역할은 높이를 따로 보고하며 가용성만으로 수렴이나 공개 BFT 투표를 증명하지 않습니다.", "풀스택 생태계", "하나의 체인, 연결된 운영 화면", "개발자 화면", "실제 엔드포인트에 연결하세요.", "현재와 목표 분리", "현재 검증됨", "추가 필요", "허위 주장 없음", "최신 네트워크 기록", "최신 블록", "인덱싱된 거래", "사용 불가", "현재"],
  es: ["Red en vivo", "Estado actual de la Testnet pública", "Actualizado", "Roles de validador inspeccionables", "Cada rol informa su altura; la disponibilidad no demuestra convergencia ni votación BFT pública.", "Ecosistema integral", "Una cadena y superficies conectadas", "Superficie de desarrollo", "Conecta con endpoints reales.", "Estado actual y objetivo separados", "Verificado ahora", "Aún necesario", "Sin afirmaciones falsas", "Registros recientes", "Bloques recientes", "Transacciones indexadas", "No disponible", "ahora"],
  fr: ["Réseau en direct", "État actuel du Testnet public", "Mis à jour", "Rôles validateurs inspectables", "Chaque rôle publie sa hauteur ; la disponibilité ne prouve ni convergence ni vote BFT public.", "Écosystème complet", "Une chaîne et des surfaces connectées", "Surface développeur", "Connectez-vous aux vrais endpoints.", "État actuel et cible séparés", "Vérifié maintenant", "Encore requis", "Aucune fausse déclaration", "Derniers enregistrements", "Derniers blocs", "Transactions indexées", "Indisponible", "maintenant"],
  de: ["Live-Netzwerk", "Aktueller öffentlicher Testnet-Status", "Aktualisiert", "Prüfbare Validator-Rollen", "Jede Rolle meldet ihre Höhe; Verfügbarkeit beweist weder Konvergenz noch öffentliche BFT-Abstimmung.", "Vollständiges Ökosystem", "Eine Chain, verbundene Betriebsflächen", "Entwicklerbereich", "Mit echten Endpunkten verbinden.", "Ist- und Zielzustand getrennt", "Jetzt geprüft", "Noch erforderlich", "Keine falschen Behauptungen", "Neueste Netzwerkdaten", "Neueste Blöcke", "Indexierte Transaktionen", "Nicht verfügbar", "jetzt"],
  pt: ["Rede ao vivo", "Estado atual da Testnet pública", "Atualizado", "Papéis de validador inspecionáveis", "Cada papel informa sua altura; disponibilidade não prova convergência nem votação BFT pública.", "Ecossistema completo", "Uma cadeia e superfícies conectadas", "Área do desenvolvedor", "Conecte-se a endpoints reais.", "Estado atual e alvo separados", "Verificado agora", "Ainda necessário", "Sem alegações falsas", "Registros recentes", "Blocos recentes", "Transações indexadas", "Indisponível", "agora"],
  ru: ["Сеть в реальном времени", "Текущее состояние публичной Testnet", "Обновлено", "Проверяемые роли валидаторов", "Каждая роль сообщает свою высоту; доступность не доказывает сходимость или публичное BFT-голосование.", "Полная экосистема", "Одна цепь и связанные сервисы", "Для разработчиков", "Подключайтесь к реальным endpoint.", "Текущее и целевое состояния разделены", "Проверено сейчас", "Ещё требуется", "Без ложных заявлений", "Последние сетевые записи", "Последние блоки", "Индексированные транзакции", "Недоступно", "сейчас"],
  ar: ["الشبكة المباشرة", "حالة Testnet العامة الحالية", "آخر تحديث", "أدوار مدققين قابلة للفحص", "يبلغ كل دور عن ارتفاعه؛ ولا يثبت التوفر وحده التقارب أو تصويت BFT العام.", "المنظومة المتكاملة", "سلسلة واحدة وواجهات تشغيل مترابطة", "واجهة المطور", "اتصل بنقاط نهاية حقيقية.", "فصل الحالة الحالية عن الهدف", "متحقق الآن", "ما يزال مطلوبًا", "بلا ادعاءات زائفة", "أحدث سجلات الشبكة", "أحدث الكتل", "المعاملات المفهرسة", "غير متاح", "الآن"],
  id: ["Jaringan langsung", "Status Testnet publik saat ini", "Diperbarui", "Peran validator yang dapat diperiksa", "Setiap peran melaporkan tingginya; ketersediaan tidak membuktikan konvergensi atau voting BFT publik.", "Ekosistem lengkap", "Satu chain dan permukaan operasi terhubung", "Permukaan pengembang", "Hubungkan ke endpoint nyata.", "Status kini dan target dipisahkan", "Terverifikasi sekarang", "Masih diperlukan", "Tanpa klaim palsu", "Catatan jaringan terbaru", "Blok terbaru", "Transaksi terindeks", "Tidak tersedia", "sekarang"],
};

const normalize = (value) => ({
  network: { eyebrow: value.network[0], title: value.network[1], updated: value.network[2], metrics: value.network.slice(3, 9), growing: value.network[9], labels: value.network.slice(10, 15) },
  validators: { eyebrow: value.validators[0], title: value.validators[1], lead: value.validators[2], headers: value.validators.slice(3, 7), current: value.validators[7], behind: value.validators[8], pending: value.validators[9], unavailable: value.validators[10], connecting: value.validators[11] },
  ecosystem: { eyebrow: value.ecosystem[0], title: value.ecosystem[1], lead: value.ecosystem[2], products: Array.from({ length: 10 }, (_, index) => ({ title: value.ecosystem[3 + index * 2], text: value.ecosystem[4 + index * 2] })) },
  developer: { eyebrow: value.developer[0], title: value.developer[1], lead: value.developer[2], action: value.developer[3], copy: value.developer.slice(4, 7) },
  readiness: { eyebrow: value.readiness[0], title: value.readiness[1], verifiedTitle: value.readiness[2], requiredTitle: value.readiness[3], boundaryTitle: value.readiness[4], boundary: value.readiness[5], action: value.readiness[6], verified: value.readiness[7], required: value.readiness[8], resourcesEyebrow: value.readiness[9], resourcesTitle: value.readiness[10] },
  records: { aria: value.records[0], blocks: value.records.slice(1, 5), transactions: value.records.slice(5, 10) },
  utility: { loading: value.utility[0], moved: value.utility.slice(1, 5), noWallet: value.utility[5], now: value.utility[6] },
});

export const EXTENDED_RUNTIME_COPY = Object.fromEntries(Object.entries(compact).map(([locale, value]) => [locale, normalize(buildCompactRuntimeCopy(value))]));
