// Exact GitHub Testnet prerelease APK. This is not a production-signed or store build.
export const WALLET_ANDROID27 = {
  id: "android-121-008aa8b07",
  version: "1.0.21-testnet-preview",
  versionCode: 27,
  architecture: "universal",
  installation: "apk",
  artifactPath: "ynx-wallet-1.0.21-testnet-preview-008aa8b07-universal-local-test-signed.apk",
  sizeBytes: 116815538,
  sha256: "76e218b75ce3a1ef9d9427b21df81fab6fdcd838841309f2c19e2200ccbe037a",
  sourceCommit: "008aa8b07e04be3de363d848121e6b9ef95ecf20",
  publicUrl: "https://github.com/JiahaoAlbus/YNX-Chain/releases/download/wallet-android-testnet-preview-1.0.21-008aa8b07/ynx-wallet-1.0.21-testnet-preview-008aa8b07-universal-local-test-signed.apk",
  fallbackUrl: "https://github.com/JiahaoAlbus/YNX-Chain/releases/download/wallet-android-testnet-preview-1.0.21-008aa8b07/ynx-wallet-1.0.21-testnet-preview-008aa8b07-universal-local-test-signed.apk",
  releaseTag: "wallet-android-testnet-preview-1.0.21-008aa8b07",
  releaseImmutable: false,
  publisherCanReplaceAssets: true,
  downloadTimeSha256Verified: false,
  releaseMetadataObservedAt: "2026-09-24T16:33:21Z",
  publicationEvidence: "/releases/wallet-downloads/20260925-android27.json",
  signingClass: "Android Debug QA test-signed; not production signed or store released",
  canonicalDownload: true,
  downloadApproved: true,
  historicalPreview: false,
  publicDownloadVerified: true,
  productionSigned: false,
  storeReleased: false,
  fullInstalledE2E: false,
  newWalletGoalsAccepted: false,
  releaseBatch: "wallet-android27-20260925",
  installProof: "Exact published APK upgraded versionCode26 to 27 and retained an unlocked disposable biometric account on Android API 36 emulator. Funded balance, pending outbox, physical device, Finance and Relay E2E remain NOT_VERIFIED.",
  mimeType: "application/vnd.android.package-archive",
  previousRelease: "/releases/wallet-downloads/20260924-android26.json",
  walletConnectRelayE2E: false,
  liveChainTransferExecuted: false,
  installedFinanceE2E: false,
  androidInstallVerified: true,
  androidInstallScope: "API 36 emulator exact published APK code26-to-27 only",
  fundedBalanceNonceVerified: false,
  physicalDeviceVerified: false
};
