export const WALLET_ANDROID24 = {
  "id": "android-118-2fdd679f9",
  "version": "1.0.18-testnet-preview",
  "versionCode": 24,
  "architecture": "universal",
  "installation": "apk",
  "artifactPath": "ynx-wallet-1.0.18-testnet-preview-2fdd679f9-universal-local-test-signed.apk",
  "sizeBytes": 116737714,
  "sha256": "45fd5004c9156d4fb5880d9caa2056f5b2238e85ca63a13ddf73f25dea96266a",
  "sourceCommit": "2fdd679f9044a51e4facfa5b71b6e57864bb6508",
  "publicUrl": "https://github.com/JiahaoAlbus/YNX-Chain/releases/download/wallet-android-testnet-preview-1.0.18-2fdd679f9/ynx-wallet-1.0.18-testnet-preview-2fdd679f9-universal-local-test-signed.apk",
  "fallbackUrl": "https://github.com/JiahaoAlbus/YNX-Chain/releases/download/wallet-android-testnet-preview-1.0.18-2fdd679f9/ynx-wallet-1.0.18-testnet-preview-2fdd679f9-universal-local-test-signed.apk",
  "releaseTag": "wallet-android-testnet-preview-1.0.18-2fdd679f9",
  "releaseImmutable": false,
  "publisherCanReplaceAssets": true,
  "downloadTimeSha256Verified": false,
  "releaseMetadataObservedAt": "2026-09-20T19:38:22Z",
  "publicationEvidence": "/releases/wallet-downloads/20260921-android24.json",
  "signingClass": "Local test signed; not production signed or store released",
  "canonicalDownload": true,
  "downloadApproved": true,
  "historicalPreview": false,
  "publicDownloadVerified": true,
  "productionSigned": false,
  "storeReleased": false,
  "fullInstalledE2E": false,
  "newWalletGoalsAccepted": false,
  "releaseBatch": "wallet-android24-20260921",
  "installProof": "Owner evidence: fresh APK/AAB digests and fixed-path two-build outputs matched. Android install/cold launch and physical-device use are NOT_VERIFIED; no installed Finance, live transfer or Relay acceptance.",
  "mimeType": "application/vnd.android.package-archive",
  "previousRelease": "/releases/wallet-downloads/20260920-android23.json",
  "walletConnectRelayE2E": false,
  "liveChainTransferExecuted": false,
  "installedFinanceE2E": false,
  "androidInstallVerified": false,
  "physicalDeviceVerified": false
};
