export const WALLET_ANDROID26 = {
  "id": "android-120-f3a12abad",
  "version": "1.0.20-testnet-preview",
  "versionCode": 26,
  "architecture": "universal",
  "installation": "apk",
  "artifactPath": "ynx-wallet-1.0.20-testnet-preview-f3a12abad-universal-local-test-signed.apk",
  "sizeBytes": 116741810,
  "sha256": "143835c4931b190f0249818f04de6f82b1f2aaa0eb155684e929f365f3b1bfc0",
  "sourceCommit": "f3a12abadad793f250df42f1123e417ba6e8a5a6",
  "publicUrl": "https://github.com/JiahaoAlbus/YNX-Chain/releases/download/wallet-android-testnet-preview-1.0.20-f3a12abad/ynx-wallet-1.0.20-testnet-preview-f3a12abad-universal-local-test-signed.apk",
  "fallbackUrl": "https://github.com/JiahaoAlbus/YNX-Chain/releases/download/wallet-android-testnet-preview-1.0.20-f3a12abad/ynx-wallet-1.0.20-testnet-preview-f3a12abad-universal-local-test-signed.apk",
  "releaseTag": "wallet-android-testnet-preview-1.0.20-f3a12abad",
  "releaseImmutable": false,
  "publisherCanReplaceAssets": true,
  "downloadTimeSha256Verified": false,
  "releaseMetadataObservedAt": "2026-09-24T13:56:36Z",
  "publicationEvidence": "/releases/wallet-downloads/20260924-android26.json",
  "signingClass": "Local test signed; not production signed or store released",
  "canonicalDownload": true,
  "downloadApproved": true,
  "historicalPreview": false,
  "publicDownloadVerified": true,
  "productionSigned": false,
  "storeReleased": false,
  "fullInstalledE2E": false,
  "newWalletGoalsAccepted": false,
  "releaseBatch": "wallet-android26-20260924",
  "installProof": "GitHub Testnet Preview APK/AAB metadata verified; 1.0.20 installation, login (including PR188), physical device, transfer, Finance, Relay and Sandbox E2E are NOT_VERIFIED.",
  "mimeType": "application/vnd.android.package-archive",
  "previousRelease": "/releases/wallet-downloads/20260921-android25.json",
  "walletConnectRelayE2E": false,
  "liveChainTransferExecuted": false,
  "installedFinanceE2E": false,
  "androidInstallVerified": false,
  "androidInstallScope": "NOT_VERIFIED",
  "fundedBalanceNonceVerified": false,
  "physicalDeviceVerified": false
};
