export const WALLET_ANDROID25 = {
  "id": "android-119-d58ce00dc",
  "version": "1.0.19-testnet-preview",
  "versionCode": 25,
  "architecture": "universal",
  "installation": "apk",
  "artifactPath": "ynx-wallet-1.0.19-testnet-preview-d58ce00dc-universal-local-test-signed.apk",
  "sizeBytes": 116639211,
  "sha256": "437973258f40e4f7b3a2d3d603bbf67e932d1fca8082ed8eb9e8ff7b84514730",
  "sourceCommit": "d58ce00dc4e83f4c24747dfef7e0b59395d6b789",
  "publicUrl": "https://github.com/JiahaoAlbus/YNX-Chain/releases/download/wallet-android-testnet-preview-1.0.19-d58ce00dc/ynx-wallet-1.0.19-testnet-preview-d58ce00dc-universal-local-test-signed.apk",
  "fallbackUrl": "https://github.com/JiahaoAlbus/YNX-Chain/releases/download/wallet-android-testnet-preview-1.0.19-d58ce00dc/ynx-wallet-1.0.19-testnet-preview-d58ce00dc-universal-local-test-signed.apk",
  "releaseTag": "wallet-android-testnet-preview-1.0.19-d58ce00dc",
  "releaseImmutable": false,
  "publisherCanReplaceAssets": true,
  "downloadTimeSha256Verified": false,
  "releaseMetadataObservedAt": "2026-09-20T22:41:00Z",
  "publicationEvidence": "/releases/wallet-downloads/20260921-android25.json",
  "signingClass": "Local test signed; not production signed or store released",
  "canonicalDownload": true,
  "downloadApproved": true,
  "historicalPreview": false,
  "publicDownloadVerified": true,
  "productionSigned": false,
  "storeReleased": false,
  "fullInstalledE2E": false,
  "newWalletGoalsAccepted": false,
  "releaseBatch": "wallet-android25-20260921",
  "installProof": "Owner evidence: 1.0.19 APK installed on a fresh API 36 emulator; cold launch, locked recovery and strong biometrics passed. Read-only result: NO_ON_CHAIN_ACCOUNT_RECORD. Funded balance/nonce, physical device, transfer, Finance and Relay remain unverified.",
  "mimeType": "application/vnd.android.package-archive",
  "previousRelease": "/releases/wallet-downloads/20260921-android24.json",
  "walletConnectRelayE2E": false,
  "liveChainTransferExecuted": false,
  "installedFinanceE2E": false,
  "androidInstallVerified": true,
  "androidInstallScope": "API 36 emulator only",
  "fundedBalanceNonceVerified": false,
  "physicalDeviceVerified": false
};
