export const WALLET_DOWNLOAD_COPY = {
  "zh-CN": {
    "downloadWallet": "下载 Wallet",
    "close": "关闭",
    "otherPlatforms": "其他平台",
    "releasePending": "此平台安装包正在验收，确认发布后即可直接下载。",
    "historicalPreview": "历史预览版",
    "historicalBoundary": "历史预览版。此安装包的安装、连接与签名能力尚未通过当前 Wallet 要求的验收。",
    "loading": "正在加载下载选项…",
    "desktopPreviewBoundary": "收款二维码、创建账户、授权回调、签名及转账流程尚未验证。",
    "limitedCiLaunch": "原生 CI 已核对 83 个 Wallet/SDK 运行文件及两次锁定冷启动；仅属于有限安装证据。",
    "appImageNotInstalled": "AppImage 仅完成构建和哈希核验，尚未测试安装与启动。",
    "unsignedPreview": "尚无生产签名或商店发布。",
    "firefoxPermissionHold": "Firefox 下载暂停，等待权限审查。",
    "downloadManifest": "下载清单",
    "previewManifest": "预览与验证说明",
    "sourceCode": "源码提交",
    "browserPreviewBoundary": "新版实装界面、权限升级及公开发送流程尚未验证。",
    "manualExtension": "扩展 ZIP 需手动安装，尚未上架 Chrome 或 Edge 商店。",
    "pwaArchiveOnly": "仅提供 PWA 静态 ZIP；没有已部署入口、启动网址、已安装 PWA 或 Auth 回调验证。",
    "androidPreviewBoundary": "最新产品登录、Pixel 等真机、公开 code4/code5 升级及完整转账流程尚未验证。",
    "androidLimitedProof": "独立模拟器已验证 code7→8 保留账户数据升级、受保护密钥的系统指纹解锁及只读 Auth 账户清单。",
    "qaSignedPreview": "Android Debug QA 签名；不是生产签名或商店版本。",
    "macosPreviewBoundary": "密码解锁、剪贴板及完整账户／转账流程尚未验证；金额单位能力未验证时，发送保持禁用。",
    "macosLimitedProof": "已检查 DMG 安装及有限的锁定启动，并保留原有加密钱包。",
    "macosAdHocSignature": "临时 ad-hoc 签名；Gatekeeper 检查未通过，尚无 Developer ID 签名或公证。",
    "androidUniversalLabel": "Android · 通用包",
    "androidUniversalProof": "包含四种 ABI；升级与系统解锁仅在 ARM64 模拟器上做了有限检查，其他 ABI 和真机尚未验证。",
    "downloadHistory": "发布历史"
  },
  "zh-TW": {
    "downloadWallet": "下載 Wallet",
    "close": "關閉",
    "otherPlatforms": "其他平台",
    "releasePending": "此平台安裝檔正在驗收，確認發布後即可直接下載。",
    "historicalPreview": "歷史預覽版",
    "historicalBoundary": "歷史預覽版。此安裝檔的安裝、連線與簽署功能尚未通過目前 Wallet 要求的驗收。",
    "loading": "正在載入下載選項…",
    "desktopPreviewBoundary": "收款 QR 碼、建立帳戶、授權回呼、簽章及轉帳流程尚未驗證。",
    "limitedCiLaunch": "原生 CI 已核對 83 個 Wallet/SDK 執行檔案及兩次鎖定冷啟動；僅屬有限安裝證據。",
    "appImageNotInstalled": "AppImage 僅完成建置和雜湊核驗，尚未測試安裝與啟動。",
    "unsignedPreview": "尚無正式簽章或商店發布。",
    "firefoxPermissionHold": "Firefox 下載暫停，等待權限審查。",
    "downloadManifest": "下載清單",
    "previewManifest": "預覽與驗證說明",
    "sourceCode": "原始碼提交",
    "browserPreviewBoundary": "新版實裝介面、權限升級及公開傳送流程尚未驗證。",
    "manualExtension": "擴充功能 ZIP 需手動安裝，尚未上架 Chrome 或 Edge 商店。",
    "pwaArchiveOnly": "僅提供 PWA 靜態 ZIP；沒有已部署入口、啟動網址、已安裝 PWA 或 Auth 回呼驗證。",
    "androidPreviewBoundary": "最新產品登入、Pixel 等實機、公開 code4/code5 升級及完整轉帳流程尚未驗證。",
    "androidLimitedProof": "獨立模擬器已驗證 code7→8 保留帳戶資料升級、受保護金鑰的系統指紋解鎖及唯讀 Auth 帳戶清單。",
    "qaSignedPreview": "Android Debug QA 簽章；不是正式簽章或商店版本。",
    "macosPreviewBoundary": "密碼解鎖、剪貼簿及完整帳戶／轉帳流程尚未驗證；金額單位能力未驗證時，傳送保持停用。",
    "macosLimitedProof": "已檢查 DMG 安裝及有限的鎖定啟動，並保留原有加密錢包。",
    "macosAdHocSignature": "臨時 ad-hoc 簽章；Gatekeeper 檢查未通過，尚無 Developer ID 簽章或公證。",
    "androidUniversalLabel": "Android · 通用套件",
    "androidUniversalProof": "包含四種 ABI；升級與系統解鎖僅在 ARM64 模擬器上做了有限檢查，其他 ABI 和實機尚未驗證。",
    "downloadHistory": "發布歷程"
  },
  "en": {
    "downloadWallet": "Download Wallet",
    "close": "Close",
    "otherPlatforms": "Other platforms",
    "releasePending": "This platform package is under review. A direct download will appear once its release is verified.",
    "historicalPreview": "Historical preview",
    "historicalBoundary": "Historical preview. Installation, connection and signing have not been verified against current Wallet requirements for this exact package.",
    "loading": "Loading download options…",
    "desktopPreviewBoundary": "Receive QR, account creation, callback, signing and transfer workflows remain unverified.",
    "limitedCiLaunch": "Native CI checked 83 Wallet/SDK runtime files and two locked cold launches. This is limited installation evidence.",
    "appImageNotInstalled": "AppImage was built and hashed only; installation and launch were not tested.",
    "unsignedPreview": "No production signature or store release.",
    "firefoxPermissionHold": "Firefox downloads are on hold pending permission review.",
    "downloadManifest": "Download manifest",
    "previewManifest": "Preview and verification notes",
    "sourceCode": "Source commit",
    "browserPreviewBoundary": "Current installed UI, permission upgrades and public-sender flows remain unverified.",
    "manualExtension": "Manual-install extension ZIP. No Chrome or Edge store release.",
    "pwaArchiveOnly": "Static PWA ZIP only. No deployed PWA, launch URL, installed-PWA or Auth callback proof.",
    "androidPreviewBoundary": "Latest product login, Pixel/real hardware, upgrades from public code4/code5 and complete transfer flows remain unverified.",
    "androidLimitedProof": "Independent emulator: code7→8 preserved account data; protected-key OS fingerprint unlock and read-only Auth inventory verified.",
    "qaSignedPreview": "Android Debug QA signature; no production signature or store release.",
    "macosPreviewBoundary": "Password unlock, clipboard and complete account/transfer flows remain unverified. Sending stays disabled while amount-unit capability is unverified.",
    "macosLimitedProof": "DMG installation and a limited locked launch were checked while preserving the existing encrypted wallet.",
    "macosAdHocSignature": "Ad-hoc signature; Gatekeeper rejected this build. No Developer ID signature or notarization.",
    "androidUniversalLabel": "Android · Universal",
    "androidUniversalProof": "Four ABIs included. Limited upgrade and OS-unlock checks used an ARM64 emulator; other ABIs and real devices remain unverified.",
    "downloadHistory": "Release history"
  },
  "ja": {
    "downloadWallet": "Wallet をダウンロード",
    "close": "閉じる",
    "otherPlatforms": "その他のプラットフォーム",
    "releasePending": "このプラットフォームのパッケージは検証中です。リリースの確認後、直接ダウンロードできます。",
    "historicalPreview": "過去のプレビュー版",
    "historicalBoundary": "過去のプレビュー版です。このパッケージのインストール、接続、署名は、現在の Wallet 要件に対して検証されていません。",
    "loading": "ダウンロード項目を読み込んでいます…",
    "desktopPreviewBoundary": "受取用 QR、アカウント作成、コールバック、署名、送金のフローは未検証です。",
    "limitedCiLaunch": "ネイティブ CI で Wallet/SDK の実行時ファイル 83 件とロック画面までのコールド起動 2 回を確認。限定的なインストール証拠です。",
    "appImageNotInstalled": "AppImage はビルドとハッシュ確認のみ。インストールと起動は未検証です。",
    "unsignedPreview": "製品版署名とストア公開はありません。",
    "firefoxPermissionHold": "Firefox のダウンロードは権限審査が終わるまで保留中です。",
    "downloadManifest": "ダウンロード一覧",
    "previewManifest": "プレビューと検証の説明",
    "sourceCode": "ソースコミット",
    "browserPreviewBoundary": "現行版のインストール後の画面、権限更新、公開送信フローは未検証です。",
    "manualExtension": "手動インストール用の拡張機能 ZIP。Chrome／Edge ストアでは未公開です。",
    "pwaArchiveOnly": "静的 PWA ZIP のみ。公開 PWA、起動 URL、PWA のインストール、Auth コールバックの検証はありません。",
    "androidPreviewBoundary": "最新の製品ログイン、Pixel などの実機、公開 code4/code5 からの更新、送金の全工程は未検証です。",
    "androidLimitedProof": "独立したエミュレーターで code7→8 のアカウントデータ保持更新、保護鍵の OS 指紋解除、読み取り専用 Auth 一覧を検証済みです。",
    "qaSignedPreview": "Android Debug QA 署名。製品版署名やストア公開はありません。",
    "macosPreviewBoundary": "パスワード解除、クリップボード、アカウントと送金の全工程は未検証です。金額単位の対応が未確認の間は送信を無効にします。",
    "macosLimitedProof": "既存の暗号化ウォレットを保持した状態で、DMG のインストールとロック画面までの限定的な起動を確認しました。",
    "macosAdHocSignature": "ad-hoc 署名。Gatekeeper の評価は不合格です。Developer ID 署名と公証はありません。",
    "androidUniversalLabel": "Android · ユニバーサル",
    "androidUniversalProof": "4 種類の ABI を含みます。更新と OS ロック解除の限定的な確認は ARM64 エミュレーターのみで、他の ABI と実機は未検証です。",
    "downloadHistory": "リリース履歴"
  },
  "ko": {
    "downloadWallet": "Wallet 다운로드",
    "close": "닫기",
    "otherPlatforms": "다른 플랫폼",
    "releasePending": "이 플랫폼의 설치 파일을 검증 중입니다. 출시가 확인되면 바로 다운로드할 수 있습니다.",
    "historicalPreview": "이전 미리 보기 버전",
    "historicalBoundary": "이전 미리 보기 버전입니다. 이 패키지의 설치, 연결 및 서명 기능은 현재 Wallet 요구 사항에 따라 검증되지 않았습니다.",
    "loading": "다운로드 옵션을 불러오는 중…",
    "desktopPreviewBoundary": "수신 QR, 계정 생성, 콜백, 서명 및 전송 흐름은 아직 검증되지 않았습니다.",
    "limitedCiLaunch": "네이티브 CI에서 Wallet/SDK 런타임 파일 83개와 잠금 화면까지의 콜드 실행 2회를 확인했습니다. 제한된 설치 증거입니다.",
    "appImageNotInstalled": "AppImage는 빌드와 해시만 확인했으며 설치와 실행은 테스트하지 않았습니다.",
    "unsignedPreview": "정식 서명이나 스토어 출시는 없습니다.",
    "firefoxPermissionHold": "Firefox 다운로드는 권한 검토가 끝날 때까지 보류됩니다.",
    "downloadManifest": "다운로드 목록",
    "previewManifest": "미리 보기 및 검증 안내",
    "sourceCode": "소스 커밋",
    "browserPreviewBoundary": "현재 버전의 설치 화면, 권한 업데이트, 공개 전송 흐름은 검증되지 않았습니다.",
    "manualExtension": "수동 설치용 확장 프로그램 ZIP입니다. Chrome 또는 Edge 스토어에 출시되지 않았습니다.",
    "pwaArchiveOnly": "정적 PWA ZIP만 제공합니다. 배포된 PWA, 실행 URL, PWA 설치 또는 Auth 콜백 검증은 없습니다.",
    "androidPreviewBoundary": "최신 제품 로그인, Pixel 등 실기기, 공개 code4/code5에서의 업그레이드와 전체 전송 흐름은 미검증 상태입니다.",
    "androidLimitedProof": "독립 에뮬레이터에서 code7→8 계정 데이터 보존 업그레이드, 보호 키의 OS 지문 잠금 해제, 읽기 전용 Auth 계정 목록을 검증했습니다.",
    "qaSignedPreview": "Android Debug QA 서명이며, 정식 서명이나 스토어 출시는 아닙니다.",
    "macosPreviewBoundary": "비밀번호 잠금 해제, 클립보드, 전체 계정 및 전송 흐름은 미검증 상태입니다. 금액 단위 지원이 확인될 때까지 전송은 비활성화됩니다.",
    "macosLimitedProof": "기존 암호화 지갑을 보존한 상태에서 DMG 설치와 잠금 화면까지의 제한된 실행을 확인했습니다.",
    "macosAdHocSignature": "ad-hoc 서명입니다. Gatekeeper 검사를 통과하지 못했으며 Developer ID 서명이나 공증은 없습니다.",
    "androidUniversalLabel": "Android · 범용 패키지",
    "androidUniversalProof": "ABI 4종을 포함합니다. 업그레이드와 OS 잠금 해제는 ARM64 에뮬레이터에서만 제한적으로 확인했으며 다른 ABI와 실기기는 미검증입니다.",
    "downloadHistory": "출시 이력"
  },
  "es": {
    "downloadWallet": "Descargar Wallet",
    "close": "Cerrar",
    "otherPlatforms": "Otras plataformas",
    "releasePending": "El paquete para esta plataforma está en revisión. La descarga directa estará disponible tras verificar la versión.",
    "historicalPreview": "Versión preliminar histórica",
    "historicalBoundary": "Versión preliminar histórica. La instalación, conexión y firma de este paquete no se han verificado según los requisitos actuales de Wallet.",
    "loading": "Cargando opciones de descarga…",
    "desktopPreviewBoundary": "Sin verificar: QR de recepción, creación de cuenta, retorno de autorización, firma y transferencias.",
    "limitedCiLaunch": "CI nativa comprobó 83 archivos de ejecución Wallet/SDK y dos arranques en frío hasta el bloqueo. Evidencia de instalación limitada.",
    "appImageNotInstalled": "AppImage solo fue compilada y verificada por hash; no se probaron instalación ni arranque.",
    "unsignedPreview": "Sin firma de producción ni publicación en tiendas.",
    "firefoxPermissionHold": "Las descargas de Firefox están suspendidas hasta revisar los permisos.",
    "downloadManifest": "Manifiesto de descargas",
    "previewManifest": "Notas de vista previa y verificación",
    "sourceCode": "Commit de origen",
    "browserPreviewBoundary": "La interfaz instalada actual, los cambios de permisos y el envío público siguen sin verificarse.",
    "manualExtension": "ZIP de extensión para instalación manual. Sin publicación en las tiendas de Chrome o Edge.",
    "pwaArchiveOnly": "Solo un ZIP estático de PWA. Sin PWA desplegada, URL de inicio ni verificación de instalación o retorno de Auth.",
    "androidPreviewBoundary": "Sin verificar: inicio de sesión actual, Pixel u otros dispositivos físicos, actualización desde code4/code5 públicos y transferencias completas.",
    "androidLimitedProof": "En un emulador independiente se verificaron la actualización code7→8 conservando la cuenta, el desbloqueo de claves protegidas con huella del SO y el inventario Auth de solo lectura.",
    "qaSignedPreview": "Firma Android Debug QA; sin firma de producción ni publicación en tiendas.",
    "macosPreviewBoundary": "El desbloqueo por contraseña, el portapapeles y los flujos completos de cuenta y transferencia siguen sin verificarse. El envío permanece desactivado mientras no se verifiquen las unidades de importe.",
    "macosLimitedProof": "Se comprobaron la instalación del DMG y un arranque limitado hasta el bloqueo, conservando la cartera cifrada existente.",
    "macosAdHocSignature": "Firma ad-hoc; Gatekeeper rechazó esta versión. Sin firma Developer ID ni notarización.",
    "androidUniversalLabel": "Android · Universal",
    "androidUniversalProof": "Incluye cuatro ABI. Las pruebas limitadas de actualización y desbloqueo del SO usaron un emulador ARM64; otras ABI y dispositivos físicos siguen sin verificarse.",
    "downloadHistory": "Historial de versiones"
  },
  "fr": {
    "downloadWallet": "Télécharger Wallet",
    "close": "Fermer",
    "otherPlatforms": "Autres plateformes",
    "releasePending": "Le paquet pour cette plateforme est en cours de vérification. Le téléchargement direct sera proposé après validation de la version.",
    "historicalPreview": "Ancienne version préliminaire",
    "historicalBoundary": "Ancienne version préliminaire. L’installation, la connexion et la signature de ce paquet n’ont pas été vérifiées selon les exigences actuelles de Wallet.",
    "loading": "Chargement des options de téléchargement…",
    "desktopPreviewBoundary": "Le QR de réception, la création de compte, le retour d’autorisation, la signature et les transferts restent non vérifiés.",
    "limitedCiLaunch": "La CI native a contrôlé 83 fichiers d’exécution Wallet/SDK et deux démarrages à froid jusqu’au verrouillage. Preuves d’installation limitées.",
    "appImageNotInstalled": "AppImage a seulement été compilée et hachée ; installation et lancement non testés.",
    "unsignedPreview": "Aucune signature de production ni publication en boutique.",
    "firefoxPermissionHold": "Les téléchargements Firefox sont suspendus dans l’attente de la vérification des permissions.",
    "downloadManifest": "Manifeste des téléchargements",
    "previewManifest": "Notes de préversion et de vérification",
    "sourceCode": "Commit source",
    "browserPreviewBoundary": "L’interface installée actuelle, la mise à jour des autorisations et l’envoi public restent non vérifiés.",
    "manualExtension": "Extension ZIP à installer manuellement. Aucune publication dans les boutiques Chrome ou Edge.",
    "pwaArchiveOnly": "ZIP statique de PWA uniquement. Aucune PWA déployée, URL de lancement ni preuve d’installation ou de retour Auth.",
    "androidPreviewBoundary": "Non vérifiés : connexion actuelle au produit, Pixel ou autres appareils physiques, mise à niveau depuis les versions publiques code4/code5 et transferts complets.",
    "androidLimitedProof": "Émulateur indépendant : mise à niveau code7→8 conservant le compte, déverrouillage des clés protégées par empreinte du système et inventaire Auth en lecture seule vérifiés.",
    "qaSignedPreview": "Signature Android Debug QA ; aucune signature de production ni publication en boutique.",
    "macosPreviewBoundary": "Le déverrouillage par mot de passe, le presse-papiers et les parcours complets de compte et transfert restent non vérifiés. L’envoi reste désactivé tant que les unités de montant ne sont pas validées.",
    "macosLimitedProof": "Installation du DMG et démarrage limité jusqu’au verrouillage vérifiés, avec conservation du portefeuille chiffré existant.",
    "macosAdHocSignature": "Signature ad-hoc ; Gatekeeper a rejeté cette version. Aucune signature Developer ID ni notarisation.",
    "androidUniversalLabel": "Android · Universel",
    "androidUniversalProof": "Quatre ABI incluses. Les vérifications limitées de mise à niveau et de déverrouillage système ont utilisé un émulateur ARM64 ; autres ABI et appareils physiques non vérifiés.",
    "downloadHistory": "Historique des versions"
  },
  "de": {
    "downloadWallet": "Wallet herunterladen",
    "close": "Schließen",
    "otherPlatforms": "Weitere Plattformen",
    "releasePending": "Das Paket für diese Plattform wird geprüft. Nach der Prüfung der Veröffentlichung wird der direkte Download verfügbar.",
    "historicalPreview": "Ältere Vorschauversion",
    "historicalBoundary": "Ältere Vorschauversion. Installation, Verbindung und Signierung dieses Pakets wurden nicht anhand der aktuellen Wallet-Anforderungen geprüft.",
    "loading": "Downloadoptionen werden geladen…",
    "desktopPreviewBoundary": "Empfangs-QR, Kontoerstellung, Autorisierungsrückkehr, Signatur und Überweisungsabläufe sind ungeprüft.",
    "limitedCiLaunch": "Native CI prüfte 83 Wallet/SDK-Laufzeitdateien und zwei Kaltstarts bis zur Sperransicht. Begrenzte Installationsnachweise.",
    "appImageNotInstalled": "AppImage wurde nur gebaut und gehasht; Installation und Start wurden nicht getestet.",
    "unsignedPreview": "Keine Produktionssignatur oder Store-Veröffentlichung.",
    "firefoxPermissionHold": "Firefox-Downloads sind bis zur Berechtigungsprüfung ausgesetzt.",
    "downloadManifest": "Downloadmanifest",
    "previewManifest": "Vorschau- und Prüfhinweise",
    "sourceCode": "Quellcommit",
    "browserPreviewBoundary": "Die aktuelle installierte Oberfläche, Berechtigungsupdates und öffentliche Sendeabläufe sind noch ungeprüft.",
    "manualExtension": "Erweiterung als ZIP zur manuellen Installation. Keine Veröffentlichung im Chrome- oder Edge-Store.",
    "pwaArchiveOnly": "Nur ein statisches PWA-ZIP. Keine bereitgestellte PWA, Start-URL oder geprüfte PWA-Installation bzw. Auth-Rückkehr.",
    "androidPreviewBoundary": "Ungeprüft bleiben die aktuelle Produktanmeldung, Pixel und andere echte Geräte, Updates von öffentlichem code4/code5 und vollständige Überweisungen.",
    "androidLimitedProof": "Auf einem unabhängigen Emulator geprüft: code7→8 mit Erhalt der Kontodaten, OS-Fingerabdruckentsperrung geschützter Schlüssel und schreibgeschützte Auth-Kontoliste.",
    "qaSignedPreview": "Android-Debug-QA-Signatur; keine Produktionssignatur oder Store-Veröffentlichung.",
    "macosPreviewBoundary": "Passwortentsperrung, Zwischenablage und vollständige Konto- und Überweisungsabläufe sind ungeprüft. Das Senden bleibt gesperrt, solange die Betragseinheiten nicht verifiziert sind.",
    "macosLimitedProof": "DMG-Installation und begrenzter Start bis zur Sperransicht wurden unter Erhalt der vorhandenen verschlüsselten Wallet geprüft.",
    "macosAdHocSignature": "Ad-hoc-Signatur; Gatekeeper hat diese Version abgelehnt. Keine Developer-ID-Signatur oder Notarisierung.",
    "androidUniversalLabel": "Android · Universal",
    "androidUniversalProof": "Vier ABIs enthalten. Begrenzte Update- und OS-Entsperrprüfungen nutzten einen ARM64-Emulator; andere ABIs und echte Geräte sind ungeprüft.",
    "downloadHistory": "Versionsverlauf"
  },
  "pt": {
    "downloadWallet": "Baixar Wallet",
    "close": "Fechar",
    "otherPlatforms": "Outras plataformas",
    "releasePending": "O pacote desta plataforma está em análise. O download direto estará disponível após a verificação da versão.",
    "historicalPreview": "Prévia histórica",
    "historicalBoundary": "Prévia histórica. A instalação, conexão e assinatura deste pacote não foram verificadas conforme os requisitos atuais da Wallet.",
    "loading": "Carregando opções de download…",
    "desktopPreviewBoundary": "QR de recebimento, criação de conta, retorno de autorização, assinatura e transferências ainda não foram verificados.",
    "limitedCiLaunch": "A CI nativa verificou 83 arquivos de execução Wallet/SDK e duas inicializações a frio até a tela bloqueada. Evidência de instalação limitada.",
    "appImageNotInstalled": "AppImage foi apenas compilada e teve o hash verificado; instalação e execução não foram testadas.",
    "unsignedPreview": "Sem assinatura de produção ou publicação em loja.",
    "firefoxPermissionHold": "Os downloads do Firefox estão suspensos até a revisão das permissões.",
    "downloadManifest": "Manifesto de downloads",
    "previewManifest": "Notas da prévia e verificação",
    "sourceCode": "Commit de origem",
    "browserPreviewBoundary": "A interface instalada atual, as atualizações de permissões e o envio público continuam sem verificação.",
    "manualExtension": "Extensão ZIP para instalação manual. Sem publicação nas lojas Chrome ou Edge.",
    "pwaArchiveOnly": "Apenas ZIP estático de PWA. Sem PWA publicada, URL de abertura ou prova de instalação e retorno Auth.",
    "androidPreviewBoundary": "Ainda não verificados: login atual no produto, Pixel ou outros aparelhos físicos, atualização do code4/code5 público e transferências completas.",
    "androidLimitedProof": "Em emulador independente: atualização code7→8 preservando a conta, desbloqueio de chaves protegidas por impressão digital do sistema e inventário Auth somente leitura verificados.",
    "qaSignedPreview": "Assinatura Android Debug QA; sem assinatura de produção ou publicação em loja.",
    "macosPreviewBoundary": "O desbloqueio por senha, a área de transferência e os fluxos completos de conta e transferência continuam sem verificação. O envio permanece desativado enquanto as unidades de valor não forem verificadas.",
    "macosLimitedProof": "Instalação do DMG e inicialização limitada até a tela bloqueada verificadas, preservando a carteira criptografada existente.",
    "macosAdHocSignature": "Assinatura ad-hoc; Gatekeeper rejeitou esta versão. Sem assinatura Developer ID ou notarização.",
    "androidUniversalLabel": "Android · Universal",
    "androidUniversalProof": "Inclui quatro ABIs. Os testes limitados de atualização e desbloqueio do sistema usaram um emulador ARM64; outras ABIs e aparelhos físicos não foram verificados.",
    "downloadHistory": "Histórico de versões"
  },
  "ru": {
    "downloadWallet": "Скачать Wallet",
    "close": "Закрыть",
    "otherPlatforms": "Другие платформы",
    "releasePending": "Пакет для этой платформы проходит проверку. Прямая загрузка появится после подтверждения выпуска.",
    "historicalPreview": "Архивная предварительная версия",
    "historicalBoundary": "Архивная предварительная версия. Установка, подключение и подпись этого пакета не проверены по текущим требованиям Wallet.",
    "loading": "Загрузка вариантов скачивания…",
    "desktopPreviewBoundary": "Не проверены QR для получения, создание аккаунта, возврат авторизации, подпись и переводы.",
    "limitedCiLaunch": "В нативной CI проверены 83 файла среды Wallet/SDK и два холодных запуска до блокировки. Это ограниченные доказательства установки.",
    "appImageNotInstalled": "Для AppImage проверены только сборка и хеш; установка и запуск не тестировались.",
    "unsignedPreview": "Нет производственной подписи и публикации в магазине.",
    "firefoxPermissionHold": "Загрузки Firefox приостановлены до проверки разрешений.",
    "downloadManifest": "Манифест загрузок",
    "previewManifest": "Примечания о предварительной версии и проверке",
    "sourceCode": "Коммит источника",
    "browserPreviewBoundary": "Текущий установленный интерфейс, обновление разрешений и публичная отправка пока не проверены.",
    "manualExtension": "ZIP расширения для ручной установки. Публикации в магазинах Chrome или Edge нет.",
    "pwaArchiveOnly": "Только статический ZIP PWA. Нет развёрнутой PWA, URL запуска или проверки установки PWA и возврата Auth.",
    "androidPreviewBoundary": "Не проверены: актуальный вход в продукт, Pixel и другие реальные устройства, обновление с публичных code4/code5 и полный цикл перевода.",
    "androidLimitedProof": "На независимом эмуляторе проверены обновление code7→8 с сохранением аккаунта, разблокировка защищённых ключей отпечатком через ОС и список Auth только для чтения.",
    "qaSignedPreview": "Подпись Android Debug QA; производственной подписи и публикации в магазине нет.",
    "macosPreviewBoundary": "Разблокировка паролем, буфер обмена и полные операции с аккаунтом и переводами не проверены. Отправка отключена, пока поддержка единиц суммы не подтверждена.",
    "macosLimitedProof": "Проверены установка DMG и ограниченный запуск до экрана блокировки с сохранением существующего зашифрованного кошелька.",
    "macosAdHocSignature": "Подпись ad-hoc; Gatekeeper отклонил эту сборку. Подписи Developer ID и нотариального заверения Apple нет.",
    "androidUniversalLabel": "Android · Универсальный",
    "androidUniversalProof": "Включены четыре ABI. Ограниченные проверки обновления и разблокировки ОС выполнены на эмуляторе ARM64; другие ABI и реальные устройства не проверены.",
    "downloadHistory": "История выпусков"
  },
  "ar": {
    "downloadWallet": "تنزيل Wallet",
    "close": "إغلاق",
    "otherPlatforms": "منصات أخرى",
    "releasePending": "حزمة هذه المنصة قيد التحقق. سيتوفر التنزيل المباشر بعد التحقق من الإصدار.",
    "historicalPreview": "نسخة معاينة سابقة",
    "historicalBoundary": "نسخة معاينة سابقة. لم يتم التحقق من تثبيت هذه الحزمة واتصالها وتوقيعها وفق متطلبات Wallet الحالية.",
    "loading": "جارٍ تحميل خيارات التنزيل…",
    "desktopPreviewBoundary": "لم تُتحقق مسارات QR للاستلام، وإنشاء الحساب، وعودة التفويض، والتوقيع، والتحويل.",
    "limitedCiLaunch": "فحصت CI الأصلية 83 ملف تشغيل Wallet/SDK وتشغيلين باردين حتى شاشة القفل. هذه أدلة تثبيت محدودة.",
    "appImageNotInstalled": "بُني AppImage وتُحقق تجزئته فقط؛ لم يُختبر التثبيت أو التشغيل.",
    "unsignedPreview": "لا توقيع إنتاج أو إصدار في متجر.",
    "firefoxPermissionHold": "تنزيلات Firefox معلّقة حتى مراجعة الأذونات.",
    "downloadManifest": "بيان التنزيلات",
    "previewManifest": "ملاحظات النسخة التجريبية والتحقق",
    "sourceCode": "معرّف نسخة المصدر",
    "browserPreviewBoundary": "لم تُتحقق واجهة الإصدار الحالي بعد التثبيت، وترقية الأذونات، ومسارات الإرسال العام.",
    "manualExtension": "ملف ZIP لإضافة تُثبّت يدوياً. لم تُنشر في متجر Chrome أو Edge.",
    "pwaArchiveOnly": "ملف ZIP ثابت لـ PWA فقط. لا توجد PWA منشورة أو رابط تشغيل أو إثبات لتثبيت PWA وعودة Auth.",
    "androidPreviewBoundary": "لم تُتحقق أحدث عملية دخول للمنتج، وأجهزة Pixel والأجهزة الفعلية، والترقية من code4/code5 العامّين، ومسار التحويل الكامل.",
    "androidLimitedProof": "تم التحقق على محاكي مستقل من ترقية code7→8 مع حفظ الحساب، وفتح المفاتيح المحمية ببصمة النظام، وقائمة حسابات Auth للقراءة فقط.",
    "qaSignedPreview": "توقيع Android Debug QA؛ لا توقيع إنتاج أو إصدار في متجر.",
    "macosPreviewBoundary": "لم تُتحقق إزالة القفل بكلمة المرور والحافظة ومسارات الحساب والتحويل الكاملة. يبقى الإرسال معطلاً ما دامت وحدات المبلغ غير متحقق منها.",
    "macosLimitedProof": "تم فحص تثبيت DMG وتشغيل محدود حتى شاشة القفل، مع الاحتفاظ بالمحفظة المشفرة الموجودة.",
    "macosAdHocSignature": "توقيع ad-hoc؛ رفض Gatekeeper هذا الإصدار. لا توقيع Developer ID أو توثيق من Apple.",
    "androidUniversalLabel": "Android · حزمة شاملة",
    "androidUniversalProof": "تتضمن أربع واجهات ABI. اقتصرت فحوص الترقية وفتح قفل النظام على محاكي ARM64؛ لم تُتحقق الواجهات الأخرى أو الأجهزة الفعلية.",
    "downloadHistory": "سجل الإصدارات"
  },
  "id": {
    "downloadWallet": "Unduh Wallet",
    "close": "Tutup",
    "otherPlatforms": "Platform lain",
    "releasePending": "Paket untuk platform ini sedang ditinjau. Unduhan langsung akan tersedia setelah rilis diverifikasi.",
    "historicalPreview": "Pratinjau versi lama",
    "historicalBoundary": "Pratinjau versi lama. Instalasi, koneksi, dan penandatanganan paket ini belum diverifikasi berdasarkan persyaratan Wallet saat ini.",
    "loading": "Memuat pilihan unduhan…",
    "desktopPreviewBoundary": "QR penerimaan, pembuatan akun, callback otorisasi, penandatanganan, dan transfer belum diverifikasi.",
    "limitedCiLaunch": "CI native memeriksa 83 berkas runtime Wallet/SDK dan dua peluncuran dingin hingga layar terkunci. Bukti pemasangan ini terbatas.",
    "appImageNotInstalled": "AppImage hanya dibangun dan diperiksa hash-nya; pemasangan serta peluncuran belum diuji.",
    "unsignedPreview": "Tanpa tanda tangan produksi atau rilis toko.",
    "firefoxPermissionHold": "Unduhan Firefox ditangguhkan hingga peninjauan izin selesai.",
    "downloadManifest": "Manifes unduhan",
    "previewManifest": "Catatan pratinjau dan verifikasi",
    "sourceCode": "Commit sumber",
    "browserPreviewBoundary": "Antarmuka terpasang versi ini, peningkatan izin, dan alur pengiriman publik belum diverifikasi.",
    "manualExtension": "ZIP ekstensi untuk pemasangan manual. Belum dirilis di toko Chrome atau Edge.",
    "pwaArchiveOnly": "Hanya ZIP PWA statis. Tanpa PWA yang dihosting, URL peluncuran, atau bukti pemasangan PWA dan callback Auth.",
    "androidPreviewBoundary": "Login produk terbaru, Pixel/perangkat fisik, pembaruan dari code4/code5 publik, dan alur transfer lengkap belum diverifikasi.",
    "androidLimitedProof": "Emulator independen memverifikasi pembaruan code7→8 dengan data akun tetap tersimpan, pembukaan kunci terlindungi melalui sidik jari OS, dan daftar akun Auth hanya baca.",
    "qaSignedPreview": "Tanda tangan Android Debug QA; tanpa tanda tangan produksi atau rilis toko.",
    "macosPreviewBoundary": "Pembukaan kunci dengan kata sandi, papan klip, serta alur akun dan transfer lengkap belum diverifikasi. Pengiriman tetap dinonaktifkan selama dukungan satuan nominal belum diverifikasi.",
    "macosLimitedProof": "Pemasangan DMG dan peluncuran terbatas hingga layar terkunci telah diperiksa, dengan dompet terenkripsi yang ada tetap tersimpan.",
    "macosAdHocSignature": "Tanda tangan ad-hoc; Gatekeeper menolak build ini. Tanpa tanda tangan Developer ID atau notarisasi.",
    "androidUniversalLabel": "Android · Universal",
    "androidUniversalProof": "Mencakup empat ABI. Pemeriksaan terbatas pembaruan dan pembukaan kunci OS memakai emulator ARM64; ABI lain dan perangkat fisik belum diverifikasi.",
    "downloadHistory": "Riwayat rilis"
  }
};

for (const [locale, copy] of Object.entries(WALLET_DOWNLOAD_COPY)) {
  copy.android14Boundary = locale === "zh-CN" ? "测试签名预览版。真机、其他 ABI、13→14 升级及完整业务流程尚未验证；原生水龙头暂未启用。" : locale === "zh-TW" ? "測試簽名預覽版。實機、其他 ABI、13→14 升級及完整業務流程尚未驗證；原生水龍頭暫未啟用。" : "Test-signed preview. Physical devices, other ABIs, 13-to-14 upgrade and complete workflows are not verified; native Faucet remains disabled.";
  copy.android14Proof = locale === "zh-CN" ? "API 36 ARM64 模拟器已完成新装和三次冷启动；包含四种 ABI，可独立运行，无需 Metro。" : locale === "zh-TW" ? "API 36 ARM64 模擬器已完成新裝和三次冷啟動；包含四種 ABI，可獨立執行，無需 Metro。" : "API 36 ARM64 emulator: fresh installation and three cold starts verified. Four ABIs packaged; standalone Hermes, no Metro required.";
}
