export const WALLET_DOWNLOAD_COPY = {
  "zh-CN": {
    "downloadWallet": "下载 Wallet",
    "close": "关闭",
    "otherPlatforms": "其他平台",
    "releasePending": "此平台安装包正在验收，确认发布后即可直接下载。",
    "historicalPreview": "历史预览版",
    "historicalBoundary": "历史预览版。此安装包的安装、连接与签名能力尚未通过当前 Wallet 要求的验收。",
    "loading": "正在加载下载选项…",
    "desktopPreviewBoundary": "测试网预览版。安装后的账户、回调、签名与转账完整流程仍未验证。",
    "limitedCiLaunch": "有限的 CI 证据记录了两次启动至锁定界面，不代表已验证完整安装使用流程。",
    "appImageNotInstalled": "AppImage 构建已验证，尚未测试安装。",
    "unsignedPreview": "未签名；没有生产签名或商店发布。",
    "firefoxPermissionHold": "Firefox 下载暂停，等待权限审查。",
    "downloadManifest": "下载清单",
    "previewManifest": "预览与验证说明",
    "sourceCode": "源码提交",
    "browserPreviewBoundary": "新版实装界面、权限升级及公开发送流程尚未验证。",
    "manualExtension": "扩展 ZIP 需手动安装，尚未上架 Chrome 或 Edge 商店。",
    "pwaArchiveOnly": "仅提供 PWA 静态 ZIP；没有已部署入口、启动网址、已安装 PWA 或 Auth 回调验证。",
    "androidPreviewBoundary": "最新产品登录、Pixel 等真机、公开 code4/code5 升级及完整转账流程尚未验证。",
    "androidLimitedProof": "独立模拟器已验证 code7→8 保留账户数据升级、受保护密钥的系统指纹解锁及只读 Auth 账户清单。",
    "qaSignedPreview": "Android Debug QA 签名；不是生产签名或商店版本。",
    "macosPreviewBoundary": "密码解锁、剪贴板及完整账户／转账流程尚未验证；金额单位能力未验证时，发送保持禁用。",
    "macosLimitedProof": "已检查 DMG 安装及有限的锁定启动，并保留原有加密钱包。",
    "macosAdHocSignature": "临时 ad-hoc 签名；Gatekeeper 检查未通过，尚无 Developer ID 签名或公证。"
  },
  "zh-TW": {
    "downloadWallet": "下載 Wallet",
    "close": "關閉",
    "otherPlatforms": "其他平台",
    "releasePending": "此平台安裝檔正在驗收，確認發布後即可直接下載。",
    "historicalPreview": "歷史預覽版",
    "historicalBoundary": "歷史預覽版。此安裝檔的安裝、連線與簽署功能尚未通過目前 Wallet 要求的驗收。",
    "loading": "正在載入下載選項…",
    "desktopPreviewBoundary": "測試網預覽版。安裝後的帳戶、回呼、簽章與轉帳完整流程仍未驗證。",
    "limitedCiLaunch": "有限的 CI 證據記錄了兩次啟動至鎖定畫面，不代表已驗證完整安裝使用流程。",
    "appImageNotInstalled": "AppImage 建置已驗證，尚未測試安裝。",
    "unsignedPreview": "未簽章；沒有正式簽章或商店發布。",
    "firefoxPermissionHold": "Firefox 下載暫停，等待權限審查。",
    "downloadManifest": "下載清單",
    "previewManifest": "預覽與驗證說明",
    "sourceCode": "原始碼提交",
    "browserPreviewBoundary": "新版實裝介面、權限升級及公開傳送流程尚未驗證。",
    "manualExtension": "擴充功能 ZIP 需手動安裝，尚未上架 Chrome 或 Edge 商店。",
    "pwaArchiveOnly": "僅提供 PWA 靜態 ZIP；沒有已部署入口、啟動網址、已安裝 PWA 或 Auth 回呼驗證。",
    "androidPreviewBoundary": "最新產品登入、Pixel 等實機、公開 code4/code5 升級及完整轉帳流程尚未驗證。",
    "androidLimitedProof": "獨立模擬器已驗證 code7→8 保留帳戶資料升級、受保護金鑰的系統指紋解鎖及唯讀 Auth 帳戶清單。",
    "qaSignedPreview": "Android Debug QA 簽章；不是正式簽章或商店版本。",
    "macosPreviewBoundary": "密碼解鎖、剪貼簿及完整帳戶／轉帳流程尚未驗證；金額單位能力未驗證時，傳送保持停用。",
    "macosLimitedProof": "已檢查 DMG 安裝及有限的鎖定啟動，並保留原有加密錢包。",
    "macosAdHocSignature": "臨時 ad-hoc 簽章；Gatekeeper 檢查未通過，尚無 Developer ID 簽章或公證。"
  },
  "en": {
    "downloadWallet": "Download Wallet",
    "close": "Close",
    "otherPlatforms": "Other platforms",
    "releasePending": "This platform package is under review. A direct download will appear once its release is verified.",
    "historicalPreview": "Historical preview",
    "historicalBoundary": "Historical preview. Installation, connection and signing have not been verified against current Wallet requirements for this exact package.",
    "loading": "Loading download options…",
    "desktopPreviewBoundary": "Testnet preview. Account, callback, signing and transfer flows after installation remain unverified.",
    "limitedCiLaunch": "Limited CI evidence records two cold launches to the locked screen; it does not verify the complete installed workflow.",
    "appImageNotInstalled": "AppImage build verified; installation has not been tested.",
    "unsignedPreview": "Unsigned; no production signature or store release.",
    "firefoxPermissionHold": "Firefox downloads are on hold pending permission review.",
    "downloadManifest": "Download manifest",
    "previewManifest": "Preview and verification notes",
    "sourceCode": "Source commit",
    "browserPreviewBoundary": "Current installed UI, permission upgrades and public-sender flows remain unverified.",
    "manualExtension": "Manual-install extension ZIP. No Chrome or Edge store release.",
    "pwaArchiveOnly": "Static PWA ZIP only. No deployed PWA, launch URL, installed-PWA or Auth callback proof.",
    "androidPreviewBoundary": "Latest product login, Pixel/real hardware, upgrades from public code4/code5 and complete transfer flows remain unverified.",
    "androidLimitedProof": "Independent emulator: code7→8 preserved account data; protected-key OS fingerprint unlock and read-only Auth inventory verified.",
    "qaSignedPreview": "Android Debug QA signature; no production signature or store release.",
    "macosPreviewBoundary": "Password unlock, clipboard and complete account/transfer flows remain unverified. Sending stays disabled while amount-unit capability is unverified.",
    "macosLimitedProof": "DMG installation and a limited locked launch were checked while preserving the existing encrypted wallet.",
    "macosAdHocSignature": "Ad-hoc signature; Gatekeeper rejected this build. No Developer ID signature or notarization."
  },
  "ja": {
    "downloadWallet": "Wallet をダウンロード",
    "close": "閉じる",
    "otherPlatforms": "その他のプラットフォーム",
    "releasePending": "このプラットフォームのパッケージは検証中です。リリースの確認後、直接ダウンロードできます。",
    "historicalPreview": "過去のプレビュー版",
    "historicalBoundary": "過去のプレビュー版です。このパッケージのインストール、接続、署名は、現在の Wallet 要件に対して検証されていません。",
    "loading": "ダウンロード項目を読み込んでいます…",
    "desktopPreviewBoundary": "Testnet プレビューです。インストール後のアカウント、コールバック、署名、送金の一連の操作は未検証です。",
    "limitedCiLaunch": "限定的な CI 証拠では、ロック画面までのコールド起動を2回記録しています。インストール後の全操作の検証ではありません。",
    "appImageNotInstalled": "AppImage のビルドは検証済みですが、インストールは未テストです。",
    "unsignedPreview": "未署名です。製品署名やストア公開はありません。",
    "firefoxPermissionHold": "Firefox のダウンロードは権限審査が終わるまで保留中です。",
    "downloadManifest": "ダウンロード一覧",
    "previewManifest": "プレビューと検証の説明",
    "sourceCode": "ソースコミット",
    "browserPreviewBoundary": "現行版のインストール後の画面、権限更新、公開送信フローは未検証です。",
    "manualExtension": "手動インストール用の拡張機能 ZIP。Chrome／Edge ストアでは未公開です。",
    "pwaArchiveOnly": "静的 PWA ZIP のみ。公開 PWA、起動 URL、PWA のインストール、Auth コールバックの検証はありません。",
    "androidPreviewBoundary": "最新の製品ログイン、Pixel などの実機、公開 code4/code5 からの更新、送金の全工程は未検証です。",
    "androidLimitedProof": "独立したエミュレーターで code7→8 のアカウントデータ保持更新、保護鍵の OS 指紋解除、読み取り専用 Auth 一覧を検証済みです。",
    "qaSignedPreview": "Android Debug QA 署名。製品版署名やストア公開はありません。",
    "macosPreviewBoundary": "パスワード解除、クリップボード、アカウントと送金の全工程は未検証です。金額単位の対応が未確認の間は送信を無効にします。",
    "macosLimitedProof": "既存の暗号化ウォレットを保持した状態で、DMG のインストールとロック画面までの限定的な起動を確認しました。",
    "macosAdHocSignature": "ad-hoc 署名。Gatekeeper の評価は不合格です。Developer ID 署名と公証はありません。"
  },
  "ko": {
    "downloadWallet": "Wallet 다운로드",
    "close": "닫기",
    "otherPlatforms": "다른 플랫폼",
    "releasePending": "이 플랫폼의 설치 파일을 검증 중입니다. 출시가 확인되면 바로 다운로드할 수 있습니다.",
    "historicalPreview": "이전 미리 보기 버전",
    "historicalBoundary": "이전 미리 보기 버전입니다. 이 패키지의 설치, 연결 및 서명 기능은 현재 Wallet 요구 사항에 따라 검증되지 않았습니다.",
    "loading": "다운로드 옵션을 불러오는 중…",
    "desktopPreviewBoundary": "테스트넷 미리 보기입니다. 설치 후 계정, 콜백, 서명, 전송의 전체 흐름은 아직 검증되지 않았습니다.",
    "limitedCiLaunch": "제한적인 CI 증거에는 잠금 화면까지 두 번의 콜드 실행이 기록되어 있습니다. 설치 후 전체 사용 흐름을 검증한 것은 아닙니다.",
    "appImageNotInstalled": "AppImage 빌드는 검증되었지만 설치는 테스트하지 않았습니다.",
    "unsignedPreview": "서명되지 않았으며 정식 서명이나 스토어 출시가 없습니다.",
    "firefoxPermissionHold": "Firefox 다운로드는 권한 검토가 끝날 때까지 보류됩니다.",
    "downloadManifest": "다운로드 목록",
    "previewManifest": "미리 보기 및 검증 안내",
    "sourceCode": "소스 커밋",
    "browserPreviewBoundary": "현재 버전의 설치 화면, 권한 업데이트, 공개 전송 흐름은 검증되지 않았습니다.",
    "manualExtension": "수동 설치용 확장 프로그램 ZIP입니다. Chrome 또는 Edge 스토어에 출시되지 않았습니다.",
    "pwaArchiveOnly": "정적 PWA ZIP만 제공합니다. 배포된 PWA, 실행 URL, PWA 설치 또는 Auth 콜백 검증은 없습니다.",
    "androidPreviewBoundary": "최신 제품 로그인, Pixel 등 실기기, 공개 code4/code5에서의 업그레이드와 전체 전송 흐름은 미검증 상태입니다.",
    "androidLimitedProof": "독립 에뮬레이터에서 code7→8 계정 데이터 보존 업그레이드, 보호 키의 OS 지문 잠금 해제, 읽기 전용 Auth 계정 목록을 검증했습니다.",
    "qaSignedPreview": "Android Debug QA 서명이며, 정식 서명이나 스토어 출시는 아닙니다.",
    "macosPreviewBoundary": "비밀번호 잠금 해제, 클립보드, 전체 계정 및 전송 흐름은 미검증 상태입니다. 금액 단위 지원이 확인될 때까지 전송은 비활성화됩니다.",
    "macosLimitedProof": "기존 암호화 지갑을 보존한 상태에서 DMG 설치와 잠금 화면까지의 제한된 실행을 확인했습니다.",
    "macosAdHocSignature": "ad-hoc 서명입니다. Gatekeeper 검사를 통과하지 못했으며 Developer ID 서명이나 공증은 없습니다."
  },
  "es": {
    "downloadWallet": "Descargar Wallet",
    "close": "Cerrar",
    "otherPlatforms": "Otras plataformas",
    "releasePending": "El paquete para esta plataforma está en revisión. La descarga directa estará disponible tras verificar la versión.",
    "historicalPreview": "Versión preliminar histórica",
    "historicalBoundary": "Versión preliminar histórica. La instalación, conexión y firma de este paquete no se han verificado según los requisitos actuales de Wallet.",
    "loading": "Cargando opciones de descarga…",
    "desktopPreviewBoundary": "Versión de prueba de Testnet. Los flujos completos de cuenta, retorno, firma y transferencia tras la instalación siguen sin verificarse.",
    "limitedCiLaunch": "La evidencia limitada de CI registra dos arranques en frío hasta la pantalla bloqueada; no verifica el flujo completo tras la instalación.",
    "appImageNotInstalled": "Compilación de AppImage verificada; la instalación no se ha probado.",
    "unsignedPreview": "Sin firma; sin firma de producción ni publicación en tiendas.",
    "firefoxPermissionHold": "Las descargas de Firefox están suspendidas hasta revisar los permisos.",
    "downloadManifest": "Manifiesto de descargas",
    "previewManifest": "Notas de vista previa y verificación",
    "sourceCode": "Commit de origen",
    "browserPreviewBoundary": "La interfaz instalada actual, los cambios de permisos y el envío público siguen sin verificarse.",
    "manualExtension": "ZIP de extensión para instalación manual. Sin publicación en las tiendas de Chrome o Edge.",
    "pwaArchiveOnly": "Solo un ZIP estático de PWA. Sin PWA desplegada, URL de inicio ni verificación de instalación o retorno de Auth.",
    "androidPreviewBoundary": "Sin verificar: inicio de sesión actual, Pixel u otros dispositivos físicos, actualización desde code4/code5 públicos y transferencias completas.",
    "androidLimitedProof": "En un emulador independiente se verificaron la actualización code7→8 conservando la cuenta, el desbloqueo de claves protegidas con huella del SO y el inventario Auth de solo lectura.",
    "qaSignedPreview": "Firma Android Debug QA; sin firma de producción ni publicación en tiendas.",
    "macosPreviewBoundary": "El desbloqueo por contraseña, el portapapeles y los flujos completos de cuenta y transferencia siguen sin verificarse. El envío permanece desactivado mientras no se verifiquen las unidades de importe.",
    "macosLimitedProof": "Se comprobaron la instalación del DMG y un arranque limitado hasta el bloqueo, conservando la cartera cifrada existente.",
    "macosAdHocSignature": "Firma ad-hoc; Gatekeeper rechazó esta versión. Sin firma Developer ID ni notarización."
  },
  "fr": {
    "downloadWallet": "Télécharger Wallet",
    "close": "Fermer",
    "otherPlatforms": "Autres plateformes",
    "releasePending": "Le paquet pour cette plateforme est en cours de vérification. Le téléchargement direct sera proposé après validation de la version.",
    "historicalPreview": "Ancienne version préliminaire",
    "historicalBoundary": "Ancienne version préliminaire. L’installation, la connexion et la signature de ce paquet n’ont pas été vérifiées selon les exigences actuelles de Wallet.",
    "loading": "Chargement des options de téléchargement…",
    "desktopPreviewBoundary": "Version préliminaire Testnet. Les parcours complets de compte, de retour, de signature et de transfert après installation restent non vérifiés.",
    "limitedCiLaunch": "Les preuves limitées de CI recensent deux démarrages à froid vers l’écran verrouillé ; elles ne valident pas le parcours complet après installation.",
    "appImageNotInstalled": "Compilation AppImage vérifiée ; installation non testée.",
    "unsignedPreview": "Non signé ; aucune signature de production ni publication en boutique.",
    "firefoxPermissionHold": "Les téléchargements Firefox sont suspendus dans l’attente de la vérification des permissions.",
    "downloadManifest": "Manifeste des téléchargements",
    "previewManifest": "Notes de préversion et de vérification",
    "sourceCode": "Commit source",
    "browserPreviewBoundary": "L’interface installée actuelle, la mise à jour des autorisations et l’envoi public restent non vérifiés.",
    "manualExtension": "Extension ZIP à installer manuellement. Aucune publication dans les boutiques Chrome ou Edge.",
    "pwaArchiveOnly": "ZIP statique de PWA uniquement. Aucune PWA déployée, URL de lancement ni preuve d’installation ou de retour Auth.",
    "androidPreviewBoundary": "Non vérifiés : connexion actuelle au produit, Pixel ou autres appareils physiques, mise à niveau depuis les versions publiques code4/code5 et transferts complets.",
    "androidLimitedProof": "Émulateur indépendant : mise à niveau code7→8 conservant le compte, déverrouillage des clés protégées par empreinte du système et inventaire Auth en lecture seule vérifiés.",
    "qaSignedPreview": "Signature Android Debug QA ; aucune signature de production ni publication en boutique.",
    "macosPreviewBoundary": "Le déverrouillage par mot de passe, le presse-papiers et les parcours complets de compte et transfert restent non vérifiés. L’envoi reste désactivé tant que les unités de montant ne sont pas validées.",
    "macosLimitedProof": "Installation du DMG et démarrage limité jusqu’au verrouillage vérifiés, avec conservation du portefeuille chiffré existant.",
    "macosAdHocSignature": "Signature ad-hoc ; Gatekeeper a rejeté cette version. Aucune signature Developer ID ni notarisation."
  },
  "de": {
    "downloadWallet": "Wallet herunterladen",
    "close": "Schließen",
    "otherPlatforms": "Weitere Plattformen",
    "releasePending": "Das Paket für diese Plattform wird geprüft. Nach der Prüfung der Veröffentlichung wird der direkte Download verfügbar.",
    "historicalPreview": "Ältere Vorschauversion",
    "historicalBoundary": "Ältere Vorschauversion. Installation, Verbindung und Signierung dieses Pakets wurden nicht anhand der aktuellen Wallet-Anforderungen geprüft.",
    "loading": "Downloadoptionen werden geladen…",
    "desktopPreviewBoundary": "Testnet-Vorschau. Vollständige Konto-, Rückruf-, Signatur- und Übertragungsabläufe nach der Installation sind noch ungeprüft.",
    "limitedCiLaunch": "Begrenzte CI-Nachweise dokumentieren zwei Kaltstarts bis zum Sperrbildschirm; sie prüfen nicht den vollständigen Ablauf nach der Installation.",
    "appImageNotInstalled": "AppImage-Build geprüft; die Installation wurde nicht getestet.",
    "unsignedPreview": "Unsigniert; keine Produktionssignatur oder Store-Veröffentlichung.",
    "firefoxPermissionHold": "Firefox-Downloads sind bis zur Berechtigungsprüfung ausgesetzt.",
    "downloadManifest": "Downloadmanifest",
    "previewManifest": "Vorschau- und Prüfhinweise",
    "sourceCode": "Quellcommit",
    "browserPreviewBoundary": "Die aktuelle installierte Oberfläche, Berechtigungsupdates und öffentliche Sendeabläufe sind noch ungeprüft.",
    "manualExtension": "Erweiterung als ZIP zur manuellen Installation. Keine Veröffentlichung im Chrome- oder Edge-Store.",
    "pwaArchiveOnly": "Nur ein statisches PWA-ZIP. Keine bereitgestellte PWA, Start-URL oder geprüfte PWA-Installation bzw. Auth-Rückkehr.",
    "androidPreviewBoundary": "Ungeprüft bleiben die aktuelle Produktanmeldung, Pixel und andere echte Geräte, Updates von öffentlichem code4/code5 und vollständige Überweisungen.",
    "androidLimitedProof": "Auf einem unabhängigen Emulator geprüft: code7→8 mit Erhalt der Kontodaten, OS-Fingerabdruckentsperrung geschützter Schlüssel und schreibgeschützte Auth-Kontoliste.",
    "qaSignedPreview": "Android-Debug-QA-Signatur; keine Produktionssignatur oder Store-Veröffentlichung.",
    "macosPreviewBoundary": "Passwortentsperrung, Zwischenablage und vollständige Konto- und Überweisungsabläufe sind ungeprüft. Das Senden bleibt gesperrt, solange die Betragseinheiten nicht verifiziert sind.",
    "macosLimitedProof": "DMG-Installation und begrenzter Start bis zur Sperransicht wurden unter Erhalt der vorhandenen verschlüsselten Wallet geprüft.",
    "macosAdHocSignature": "Ad-hoc-Signatur; Gatekeeper hat diese Version abgelehnt. Keine Developer-ID-Signatur oder Notarisierung."
  },
  "pt": {
    "downloadWallet": "Baixar Wallet",
    "close": "Fechar",
    "otherPlatforms": "Outras plataformas",
    "releasePending": "O pacote desta plataforma está em análise. O download direto estará disponível após a verificação da versão.",
    "historicalPreview": "Prévia histórica",
    "historicalBoundary": "Prévia histórica. A instalação, conexão e assinatura deste pacote não foram verificadas conforme os requisitos atuais da Wallet.",
    "loading": "Carregando opções de download…",
    "desktopPreviewBoundary": "Prévia da Testnet. Os fluxos completos de conta, retorno, assinatura e transferência após a instalação ainda não foram verificados.",
    "limitedCiLaunch": "As evidências limitadas de CI registram duas inicializações a frio até a tela bloqueada; não verificam o fluxo completo após a instalação.",
    "appImageNotInstalled": "Build AppImage verificado; a instalação não foi testada.",
    "unsignedPreview": "Sem assinatura; sem assinatura de produção ou publicação em loja.",
    "firefoxPermissionHold": "Os downloads do Firefox estão suspensos até a revisão das permissões.",
    "downloadManifest": "Manifesto de downloads",
    "previewManifest": "Notas da prévia e verificação",
    "sourceCode": "Commit de origem",
    "browserPreviewBoundary": "A interface instalada atual, as atualizações de permissões e o envio público continuam sem verificação.",
    "manualExtension": "Extensão ZIP para instalação manual. Sem publicação nas lojas Chrome ou Edge.",
    "pwaArchiveOnly": "Apenas ZIP estático de PWA. Sem PWA publicada, URL de abertura ou prova de instalação e retorno Auth.",
    "androidPreviewBoundary": "Ainda não verificados: login atual no produto, Pixel ou outros aparelhos físicos, atualização do code4/code5 público e transferências completas.",
    "androidLimitedProof": "Em emulador independente: atualização code7→8 preservando a conta, desbloqueio de chaves protegidas por impressão digital do sistema e inventário Auth somente leitura verificados.",
    "qaSignedPreview": "Assinatura Android Debug QA; sem assinatura de produção ou publicação em loja.",
    "macosPreviewBoundary": "O desbloqueio por senha, a área de transferência e os fluxos completos de conta e transferência continuam sem verificação. O envio permanece desativado enquanto as unidades de valor não forem verificadas.",
    "macosLimitedProof": "Instalação do DMG e inicialização limitada até a tela bloqueada verificadas, preservando a carteira criptografada existente.",
    "macosAdHocSignature": "Assinatura ad-hoc; Gatekeeper rejeitou esta versão. Sem assinatura Developer ID ou notarização."
  },
  "ru": {
    "downloadWallet": "Скачать Wallet",
    "close": "Закрыть",
    "otherPlatforms": "Другие платформы",
    "releasePending": "Пакет для этой платформы проходит проверку. Прямая загрузка появится после подтверждения выпуска.",
    "historicalPreview": "Архивная предварительная версия",
    "historicalBoundary": "Архивная предварительная версия. Установка, подключение и подпись этого пакета не проверены по текущим требованиям Wallet.",
    "loading": "Загрузка вариантов скачивания…",
    "desktopPreviewBoundary": "Предварительная версия Testnet. Полные сценарии аккаунта, обратного вызова, подписи и перевода после установки ещё не проверены.",
    "limitedCiLaunch": "Ограниченные данные CI подтверждают два холодных запуска до экрана блокировки, но не полный сценарий работы после установки.",
    "appImageNotInstalled": "Сборка AppImage проверена; установка не тестировалась.",
    "unsignedPreview": "Без подписи; нет производственной подписи или публикации в магазине.",
    "firefoxPermissionHold": "Загрузки Firefox приостановлены до проверки разрешений.",
    "downloadManifest": "Манифест загрузок",
    "previewManifest": "Примечания о предварительной версии и проверке",
    "sourceCode": "Коммит источника",
    "browserPreviewBoundary": "Текущий установленный интерфейс, обновление разрешений и публичная отправка пока не проверены.",
    "manualExtension": "ZIP расширения для ручной установки. Публикации в магазинах Chrome или Edge нет.",
    "pwaArchiveOnly": "Только статический ZIP PWA. Нет развёрнутой PWA, URL запуска или проверки установки PWA и возврата Auth.",
    "androidPreviewBoundary": "Не проверены: актуальный вход в продукт, Pixel и другие реальные устройства, обновление с публичных code4/code5 и полный цикл перевода.",
    "androidLimitedProof": "На независимом эмуляторе проверены обновление code7→8 с сохранением аккаунта, разблокировка защищённых ключей отпечатком через ОС и список Auth только для чтения.",
    "qaSignedPreview": "Подпись Android Debug QA; производственной подписи и публикации в магазине нет.",
    "macosPreviewBoundary": "Разблокировка паролем, буфер обмена и полные операции с аккаунтом и переводами не проверены. Отправка отключена, пока поддержка единиц суммы не подтверждена.",
    "macosLimitedProof": "Проверены установка DMG и ограниченный запуск до экрана блокировки с сохранением существующего зашифрованного кошелька.",
    "macosAdHocSignature": "Подпись ad-hoc; Gatekeeper отклонил эту сборку. Подписи Developer ID и нотариального заверения Apple нет."
  },
  "ar": {
    "downloadWallet": "تنزيل Wallet",
    "close": "إغلاق",
    "otherPlatforms": "منصات أخرى",
    "releasePending": "حزمة هذه المنصة قيد التحقق. سيتوفر التنزيل المباشر بعد التحقق من الإصدار.",
    "historicalPreview": "نسخة معاينة سابقة",
    "historicalBoundary": "نسخة معاينة سابقة. لم يتم التحقق من تثبيت هذه الحزمة واتصالها وتوقيعها وفق متطلبات Wallet الحالية.",
    "loading": "جارٍ تحميل خيارات التنزيل…",
    "desktopPreviewBoundary": "نسخة تجريبية للشبكة الاختبارية. لم تُتحقق بعد مسارات الحساب والعودة والتوقيع والتحويل كاملة بعد التثبيت.",
    "limitedCiLaunch": "تسجّل أدلة CI المحدودة عمليتي تشغيل بارد وصولاً إلى شاشة القفل؛ ولا تثبت سير العمل الكامل بعد التثبيت.",
    "appImageNotInstalled": "تم التحقق من بناء AppImage؛ لم يُختبر التثبيت.",
    "unsignedPreview": "غير موقّع؛ لا توقيع إنتاج أو إصدار في متجر.",
    "firefoxPermissionHold": "تنزيلات Firefox معلّقة حتى مراجعة الأذونات.",
    "downloadManifest": "بيان التنزيلات",
    "previewManifest": "ملاحظات النسخة التجريبية والتحقق",
    "sourceCode": "معرّف نسخة المصدر",
    "browserPreviewBoundary": "لم تُتحقق واجهة الإصدار الحالي بعد التثبيت، وترقية الأذونات، ومسارات الإرسال العام.",
    "manualExtension": "ملف ZIP لإضافة تُثبّت يدوياً. لم تُنشر في متجر Chrome أو Edge.",
    "pwaArchiveOnly": "ملف ZIP ثابت لـ PWA فقط. لا توجد PWA منشورة أو رابط تشغيل أو إثبات لتثبيت PWA وعودة Auth.",
    "androidPreviewBoundary": "لم تُتحقق أحدث عملية دخول للمنتج، وأجهزة Pixel والأجهزة الفعلية، والترقية من code4/code5 العامّين، ومسار التحويل الكامل.",
    "androidLimitedProof": "تم التحقق على محاكي مستقل من ترقية code7→8 مع حفظ الحساب، وفتح المفاتيح المحمية ببصمة النظام، وقائمة حسابات Auth للقراءة فقط.",
    "qaSignedPreview": "توقيع Android Debug QA؛ لا توقيع إنتاج أو إصدار في متجر.",
    "macosPreviewBoundary": "لم تُتحقق إزالة القفل بكلمة المرور والحافظة ومسارات الحساب والتحويل الكاملة. يبقى الإرسال معطلاً ما دامت وحدات المبلغ غير متحقق منها.",
    "macosLimitedProof": "تم فحص تثبيت DMG وتشغيل محدود حتى شاشة القفل، مع الاحتفاظ بالمحفظة المشفرة الموجودة.",
    "macosAdHocSignature": "توقيع ad-hoc؛ رفض Gatekeeper هذا الإصدار. لا توقيع Developer ID أو توثيق من Apple."
  },
  "id": {
    "downloadWallet": "Unduh Wallet",
    "close": "Tutup",
    "otherPlatforms": "Platform lain",
    "releasePending": "Paket untuk platform ini sedang ditinjau. Unduhan langsung akan tersedia setelah rilis diverifikasi.",
    "historicalPreview": "Pratinjau versi lama",
    "historicalBoundary": "Pratinjau versi lama. Instalasi, koneksi, dan penandatanganan paket ini belum diverifikasi berdasarkan persyaratan Wallet saat ini.",
    "loading": "Memuat pilihan unduhan…",
    "desktopPreviewBoundary": "Pratinjau Testnet. Alur lengkap akun, callback, penandatanganan, dan transfer setelah pemasangan belum diverifikasi.",
    "limitedCiLaunch": "Bukti CI terbatas mencatat dua peluncuran dingin hingga layar terkunci; ini tidak memverifikasi seluruh alur setelah pemasangan.",
    "appImageNotInstalled": "Build AppImage telah diverifikasi; pemasangan belum diuji.",
    "unsignedPreview": "Tanpa tanda tangan; belum ditandatangani untuk produksi atau dirilis di toko.",
    "firefoxPermissionHold": "Unduhan Firefox ditangguhkan hingga peninjauan izin selesai.",
    "downloadManifest": "Manifes unduhan",
    "previewManifest": "Catatan pratinjau dan verifikasi",
    "sourceCode": "Commit sumber",
    "browserPreviewBoundary": "Antarmuka terpasang versi ini, peningkatan izin, dan alur pengiriman publik belum diverifikasi.",
    "manualExtension": "ZIP ekstensi untuk pemasangan manual. Belum dirilis di toko Chrome atau Edge.",
    "pwaArchiveOnly": "Hanya ZIP PWA statis. Tanpa PWA yang dihosting, URL peluncuran, atau bukti pemasangan PWA dan callback Auth.",
    "androidPreviewBoundary": "Login produk terbaru, Pixel/perangkat fisik, pembaruan dari code4/code5 publik, dan alur transfer lengkap belum diverifikasi.",
    "androidLimitedProof": "Emulator independen memverifikasi pembaruan code7→8 dengan data akun tetap tersimpan, pembukaan kunci terlindungi melalui sidik jari OS, dan daftar akun Auth hanya baca.",
    "qaSignedPreview": "Tanda tangan Android Debug QA; tanpa tanda tangan produksi atau rilis toko.",
    "macosPreviewBoundary": "Pembukaan kunci dengan kata sandi, papan klip, serta alur akun dan transfer lengkap belum diverifikasi. Pengiriman tetap dinonaktifkan selama dukungan satuan nominal belum diverifikasi.",
    "macosLimitedProof": "Pemasangan DMG dan peluncuran terbatas hingga layar terkunci telah diperiksa, dengan dompet terenkripsi yang ada tetap tersimpan.",
    "macosAdHocSignature": "Tanda tangan ad-hoc; Gatekeeper menolak build ini. Tanpa tanda tangan Developer ID atau notarisasi."
  }
};
