import React from "react";
import docsAuthority from "virtual:ynx-docs-authority";
import runtimeRecord from "../../public/releases/wallet-auth-runtime/6cf3ef845202bd879ed94515a71b323dd2fc9e14/runtime-publication.json";
const words={
 en:['Source records','Read the preserved release evidence','This archived Wallet/Auth record describes its own source version. It does not prove installed-wallet, account, signing, transaction or complete ecosystem acceptance today.','Read runtime record','Read supporting evidence','Installed wallet/client','Account, signing and transaction','Product migrations','Central integration / public readiness','Production signature / store release','Not verified','Verified in this record','Download the documentation archive','Unsigned source archive; its digest verifies the file, not current product readiness.'],
 'zh-CN':['来源记录','阅读保留的发布证据','此 Wallet/Auth 历史记录仅说明对应源码版本，不能证明今天已完成安装钱包、账户、签名、交易或全生态验收。','阅读运行记录','阅读支持证据','安装钱包／客户端','账户、签名与交易','产品迁移','中央集成／公开就绪','生产签名／商店发布','未验证','本记录已验证','下载文档归档','未签署的源码归档；摘要验证文件完整性，不证明当前产品已就绪。'],
 'zh-TW':['來源紀錄','閱讀保留的發布證據','此 Wallet/Auth 歷史紀錄僅說明對應來源版本，不證明目前已完成錢包安裝、帳戶、簽署、交易或全生態驗收。','閱讀執行紀錄','閱讀支持證據','已安裝錢包／用戶端','帳戶、簽署與交易','產品遷移','中央整合／公開就緒','正式簽署／商店發布','未驗證','本紀錄已驗證','下載文件封存','未簽署的來源封存；摘要驗證檔案完整性，不證明目前產品已就緒。'],
 ja:['出典記録','保存されたリリース証拠を読む','この Wallet/Auth 過去記録は対応ソース版の説明です。現在のウォレット導入、アカウント、署名、取引、全製品の受け入れを証明しません。','稼働記録を読む','関連証拠を読む','導入済みウォレット／クライアント','アカウント・署名・取引','製品移行','中央統合／公開準備','製品署名／ストア公開','未検証','この記録で検証済み','資料アーカイブを取得','未署名の出典アーカイブです。ダイジェストはファイルを検証し、現在の製品準備を保証しません。'],
 ko:['출처 기록','보존된 출시 증거 읽기','이 과거 Wallet/Auth 기록은 해당 소스 버전에 관한 것입니다. 현재 지갑 설치, 계정, 서명, 거래 또는 전체 생태계 승인을 증명하지 않습니다.','실행 기록 읽기','관련 증거 읽기','설치된 지갑／클라이언트','계정·서명·거래','제품 이전','중앙 통합／공개 준비','정식 서명／스토어 출시','미검증','이 기록에서 검증','문서 보관본 다운로드','서명되지 않은 소스 보관본입니다. 해시는 파일을 검증하며 현재 제품 준비를 증명하지 않습니다.'],
 es:['Registros de origen','Leer las evidencias conservadas','Este registro histórico de Wallet/Auth corresponde a su versión de origen; no demuestra instalación, cuentas, firmas, transacciones ni aceptación completa del ecosistema actual.','Leer registro','Leer evidencia','Cartera/cliente instalado','Cuenta, firma y transacción','Migraciones de productos','Integración central / preparación pública','Firma de producción / tiendas','No verificado','Verificado en este registro','Descargar archivo documental','Archivo de fuentes sin firma. El hash verifica el archivo, no la preparación actual del producto.'],
 fr:['Documents de preuve','Lire les preuves conservées','Cette archive Wallet/Auth concerne sa propre version source. Elle ne prouve pas les installations, comptes, signatures, transactions ou l’acceptation complète actuelles.','Lire le relevé','Lire les preuves','Portefeuille/client installé','Compte, signature et transaction','Migrations des produits','Intégration centrale / préparation publique','Signature de production / boutique','Non vérifié','Vérifié dans ce relevé','Télécharger les archives','Archive source non signée. Le condensat vérifie le fichier, pas la préparation actuelle du produit.'],
 de:['Quellnachweise','Erhaltene Veröffentlichungsbelege lesen','Dieser historische Wallet/Auth-Nachweis betrifft seinen Quellstand. Er beweist keine heutigen Installationen, Konten, Signaturen, Transaktionen oder vollständige Ökosystem-Abnahme.','Betriebsnachweis lesen','Belege lesen','Installierte Wallet / Client','Konto, Signatur und Transaktion','Produktmigrationen','Zentrale Integration / öffentliche Bereitschaft','Produktionssignatur / Store','Nicht geprüft','In diesem Nachweis geprüft','Dokumentationsarchiv laden','Unsigniertes Quellarchiv. Der Hash prüft die Datei, nicht die aktuelle Produktbereitschaft.'],
 pt:['Registros de origem','Ler evidências preservadas','Este registro histórico Wallet/Auth refere-se à sua versão de origem. Não prova instalação, contas, assinaturas, transações ou aceitação completa atuais.','Ler registro','Ler evidências','Carteira/cliente instalado','Conta, assinatura e transação','Migrações de produtos','Integração central / prontidão pública','Assinatura de produção / loja','Não verificado','Verificado neste registro','Baixar arquivo documental','Arquivo de fontes sem assinatura. O hash verifica o arquivo, não a prontidão atual do produto.'],
 ru:['Исходные записи','Читать сохранённые свидетельства выпуска','Архив Wallet/Auth относится к своей версии исходников. Он не доказывает текущую установку кошельков, работу аккаунтов, подписей, транзакций и полную приёмку экосистемы.','Читать запись','Читать свидетельства','Установленный кошелёк/клиент','Аккаунт, подпись и транзакция','Миграции продуктов','Центральная интеграция / публичная готовность','Рабочая подпись / магазин','Не проверено','Проверено в этой записи','Скачать архив документации','Неподписанный архив исходников. Хеш проверяет файл, а не текущую готовность продукта.'],
 ar:['سجلات المصدر','قراءة أدلة الإصدار المحفوظة','يخص سجل Wallet/Auth التاريخي إصدار مصدره فقط. لا يثبت اكتمال تثبيت المحافظ أو الحسابات أو التوقيع أو المعاملات أو قبول المنظومة اليوم.','قراءة سجل التشغيل','قراءة الأدلة','المحفظة أو العميل المثبّت','الحساب والتوقيع والمعاملة','ترحيل المنتجات','التكامل المركزي / الجاهزية العامة','توقيع الإنتاج / إصدار المتجر','غير متحقق','متحقق في هذا السجل','تنزيل أرشيف الوثائق','أرشيف مصدر غير موقّع. تتحقق التجزئة من الملف، لا من جاهزية المنتج الحالية.'],
 id:['Catatan sumber','Baca bukti rilis tersimpan','Arsip Wallet/Auth ini menjelaskan versi sumbernya sendiri. Ini tidak membuktikan pemasangan, akun, tanda tangan, transaksi, atau penerimaan ekosistem lengkap saat ini.','Baca catatan','Baca bukti','Dompet/klien terpasang','Akun, tanda tangan, transaksi','Migrasi produk','Integrasi pusat / kesiapan publik','Tanda tangan produksi / toko','Belum diverifikasi','Diverifikasi dalam catatan ini','Unduh arsip dokumentasi','Arsip sumber tanpa tanda tangan. Hash memeriksa berkas, bukan kesiapan produk saat ini.'],
};
export function DocsSourceRecords({locale}) {
 const copy=words[locale]||words.en, boundary=runtimeRecord.claimBoundary, artifact=docsAuthority.artifact;
 const state=value=>value===true?copy[11]:copy[10];
 return <section className="learningNetworkNote docsSourceRecords" id="wallet-session-release"><p className="sectionEyebrow">{copy[0]}</p><h2>{copy[1]}</h2><p>{copy[2]}</p><div className="learningLinks"><a href="/releases/wallet-auth-runtime/6cf3ef845202bd879ed94515a71b323dd2fc9e14/runtime-publication.json">{copy[3]}</a><a href={runtimeRecord.verification.evidenceUrl} target="_blank" rel="noopener noreferrer">{copy[4]}</a></div><dl className="learningNetworkSettings"><div><dt>{copy[5]}</dt><dd>{state(boundary.installedWalletClientVerified)}</dd></div><div><dt>{copy[6]}</dt><dd>{state(boundary.accountSigningTransactionVerified)}</dd></div><div><dt>{copy[7]}</dt><dd>{boundary.productMigrations.completed} / {boundary.productMigrations.total}</dd></div><div><dt>{copy[8]}</dt><dd>{state(boundary.integratedCentral)} / {state(boundary.aggregatePublicReady)}</dd></div><div><dt>{copy[9]}</dt><dd>{state(boundary.productionSigned)} / {state(boundary.storeReleased)}</dd></div></dl>{artifact.downloadHosted&&artifact.downloadPath&&<details className="learningHelp"><summary>{copy[12]}</summary><p>{copy[13]}</p><a className="learningTextLink" href={artifact.downloadPath} download>{copy[12]}</a><p>SHA-256 <code dir="ltr">{artifact.sha256}</code></p></details>}</section>;
}
